/**
 * Query hook generator
 *
 * Generates createQuery-based hooks for canister query methods.
 */

import type { MethodInfo, ReactorConfig, HookType } from "../types.js"
import { getHookExportName, getReactorName } from "../utils/naming.js"

export interface QueryHookOptions {
  canisterName: string
  method: MethodInfo
  config: ReactorConfig
  type?: HookType
}

/**
 * Generate a query hook file content
 */
export function generateQueryHook(options: QueryHookOptions): string {
  const { canisterName, method, type = "query" } = options

  const reactorName = getReactorName(canisterName)
  const hookExportName = getHookExportName(method.name, type)

  const isSuspense = type === "suspenseQuery"
  const creatorFn = isSuspense ? "createSuspenseQuery" : "createQuery"
  const factoryFn = isSuspense
    ? "createSuspenseQueryFactory"
    : "createQueryFactory"
  const hookName = isSuspense ? "useSuspenseQuery" : "useQuery"

  if (method.hasArgs) {
    // Query with arguments - use factory pattern
    return `/**
 * Query Factory: ${method.name}
 *
 * Auto-generated by @ic-reactor/cli
 *
 * @example
 * // Use in components
 * const { data } = ${hookExportName}([arg1, arg2]).${hookName}()
 *
 * // Prefetch in loaders
 * const data = await ${hookExportName}([arg1, arg2]).fetch()
 *
 * // Invalidate cache
 * ${hookExportName}([arg1, arg2]).invalidate()
 *
 * // Get query key for cache manipulation
 * const key = ${hookExportName}([arg1, arg2]).getQueryKey()
 */

import { ${factoryFn} } from "@ic-reactor/react"
import { ${reactorName} } from "../reactor"

/**
 * Query factory for ${method.name}
 *
 * Creates a query instance with the provided arguments.
 * Each unique set of args gets its own cached query.
 */
export const ${hookExportName} = ${factoryFn}(${reactorName}, {
  functionName: "${method.name}",
  // Customize your query options:
  // refetchInterval: 60 * 1000, // Refetch every 60 seconds
  // staleTime: 5 * 60 * 1000, // Cache for 5 minutes
  // select: (data) => data,
})
`
  } else {
    // Query without arguments - static instance
    return `/**
 * Query: ${method.name}
 *
 * Auto-generated by @ic-reactor/cli
 *
 * @example
 * // Use in components
 * const { data } = ${hookExportName}.${hookName}()
 *
 * // Prefetch in loaders
 * const data = await ${hookExportName}.fetch()
 *
 * // Invalidate cache
 * ${hookExportName}.invalidate()
 *
 * // Get query key for cache manipulation
 * const key = ${hookExportName}.getQueryKey()
 */

import { ${creatorFn} } from "@ic-reactor/react"
import { ${reactorName} } from "../reactor"

/**
 * Query for ${method.name}
 *
 * Provides:
 * - .${hookName}() - React hook
 * - .fetch() - Direct fetch (for loaders)
 * - .invalidate() - Invalidate cache
 * - .getQueryKey() - Get query key
 * - .getCacheData() - Read from cache
 */
export const ${hookExportName} = ${creatorFn}(${reactorName}, {
  functionName: "${method.name}",
  // Customize your query options:
  // refetchInterval: 60 * 1000, // Refetch every 60 seconds
  // staleTime: 5 * 60 * 1000, // Cache for 5 minutes
  // select: (data) => data,
})
`
  }
}
