/**
 * Query hook generator
 *
 * Generates createQuery-based hooks for canister query methods.
 */

import type { MethodInfo, ReactorConfig } from "../types.js"
import { getHookExportName, getReactorName } from "../utils/naming.js"

export interface QueryHookOptions {
  canisterName: string
  method: MethodInfo
  config: ReactorConfig
}

/**
 * Generate a query hook file content
 */
export function generateQueryHook(options: QueryHookOptions): string {
  const { canisterName, method } = options

  const reactorName = getReactorName(canisterName)
  const hookExportName = getHookExportName(method.name, "query")

  if (method.hasArgs) {
    // Query with arguments - use factory pattern
    return `/**
 * Query Factory: ${method.name}
 *
 * Auto-generated by @ic-reactor/cli
 *
 * @example
 * // Use in components
 * const { data, isLoading } = ${hookExportName}([arg1, arg2]).useQuery()
 *
 * // Prefetch in loaders
 * const data = await ${hookExportName}([arg1, arg2]).fetch()
 *
 * // Invalidate cache
 * ${hookExportName}([arg1, arg2]).invalidate()
 *
 * // Get query key for cache manipulation
 * const key = ${hookExportName}([arg1, arg2]).getQueryKey()
 */

import { createQueryFactory } from "@ic-reactor/react"
import { ${reactorName} } from "../reactor"

/**
 * Query factory for ${method.name}
 *
 * Creates a query instance with the provided arguments.
 * Each unique set of args gets its own cached query.
 */
export const ${hookExportName} = createQueryFactory(${reactorName}, {
  functionName: "${method.name}",
  // Customize your query options:
  // staleTime: 5 * 60 * 1000,
  // select: (data) => data,
})
`
  } else {
    // Query without arguments - static instance
    return `/**
 * Query: ${method.name}
 *
 * Auto-generated by @ic-reactor/cli
 *
 * @example
 * // Use in components
 * const { data, isLoading } = ${hookExportName}.useQuery()
 *
 * // Prefetch in loaders
 * const data = await ${hookExportName}.fetch()
 *
 * // Invalidate cache
 * ${hookExportName}.invalidate()
 *
 * // Get query key for cache manipulation
 * const key = ${hookExportName}.getQueryKey()
 */

import { createQuery } from "@ic-reactor/react"
import { ${reactorName} } from "../reactor"

/**
 * Query for ${method.name}
 *
 * Provides:
 * - .useQuery() - React hook
 * - .fetch() - Direct fetch (for loaders)
 * - .invalidate() - Invalidate cache
 * - .getQueryKey() - Get query key
 * - .getCacheData() - Read from cache
 */
export const ${hookExportName} = createQuery(${reactorName}, {
  functionName: "${method.name}",
  // Customize your query options:
  // staleTime: 5 * 60 * 1000,
  // select: (data) => data,
})
`
  }
}
