/**
 * Reactor file generator
 *
 * Generates the shared reactor instance file for a canister.
 */

import path from "node:path"
import type { ReactorConfig, CanisterConfig } from "../types.js"
import {
  toPascalCase,
  getReactorName,
  getServiceTypeName,
} from "../utils/naming.js"

export interface ReactorGeneratorOptions {
  canisterName: string
  canisterConfig: CanisterConfig
  config: ReactorConfig
  outDir: string
  hasDeclarations?: boolean
}

/**
 * Generate the reactor.ts file content
 */
export function generateReactorFile(options: ReactorGeneratorOptions): string {
  const { canisterName, canisterConfig, hasDeclarations = true } = options

  const pascalName = toPascalCase(canisterName)
  const reactorName = getReactorName(canisterName)
  const serviceName = getServiceTypeName(canisterName)
  const reactorType =
    canisterConfig.useDisplayReactor !== false ? "DisplayReactor" : "Reactor"

  // Calculate relative path to client manager (canister-specific → global → default)
  const clientManagerPath =
    canisterConfig.clientManagerPath ??
    options.config.clientManagerPath ??
    "../../lib/client"

  // Calculate relative path to declarations (use DID file name, not canister name)
  const didFileName = path.basename(canisterConfig.didFile)
  const declarationsPath = `./declarations/${didFileName}`

  if (hasDeclarations) {
    return `/**
 * ${pascalName} Reactor
 *
 * Auto-generated by @ic-reactor/cli
 * This file provides the shared reactor instance for the ${canisterName} canister.
 *
 * You can customize this file to add global configuration.
 */

import { ${reactorType}, createActorHooks, createAuthHooks } from "@ic-reactor/react"
import { clientManager } from "${clientManagerPath}"
import { idlFactory, type _SERVICE } from "${declarationsPath}"

// ═══════════════════════════════════════════════════════════════════════════
// SERVICE TYPE
// ═══════════════════════════════════════════════════════════════════════════

export type ${serviceName} = _SERVICE

// ═══════════════════════════════════════════════════════════════════════════
// REACTOR INSTANCE
// ═══════════════════════════════════════════════════════════════════════════

/**
 * ${pascalName} Reactor with ${canisterConfig.useDisplayReactor !== false ? "Display" : "Candid"} type transformations.
 * ${
   canisterConfig.useDisplayReactor !== false
     ? "Automatically converts bigint → string, Principal → string, etc."
     : "Uses raw Candid types."
 }
 */
export const ${reactorName} = new ${reactorType}<${serviceName}>({
  clientManager,
  idlFactory,
  name: "${canisterName}",
})

// ═══════════════════════════════════════════════════════════════════════════
// BASE HOOKS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Base actor hooks - use these directly or import method-specific hooks.
 */
export const {
  useActorQuery,
  useActorMutation,
  useActorSuspenseQuery,
  useActorInfiniteQuery,
  useActorSuspenseInfiniteQuery,
  useActorMethod,
} = createActorHooks(${reactorName})

/**
 * Auth hooks for the client manager.
 */
export const { useAuth, useAgentState, useUserPrincipal } = createAuthHooks(clientManager)

// ═══════════════════════════════════════════════════════════════════════════
// RE-EXPORTS
// ═══════════════════════════════════════════════════════════════════════════

export { idlFactory }
`
  }

  // Fallback when declarations don't exist
  return `/**
 * ${pascalName} Reactor
 *
 * Auto-generated by @ic-reactor/cli
 * This file provides the shared reactor instance for the ${canisterName} canister.
 *
 * You can customize this file to add global configuration.
 */

import { ${reactorType}, createActorHooks, createAuthHooks } from "@ic-reactor/react"
import { clientManager } from "${clientManagerPath}"

// ═══════════════════════════════════════════════════════════════════════════
// DECLARATIONS
// ═══════════════════════════════════════════════════════════════════════════

// TODO: Generate proper types by running:
// npx @icp-sdk/bindgen --input <path-to-did> --output ./${canisterName}/declarations

// Then uncomment:
// import { idlFactory, type _SERVICE as ${serviceName} } from "${declarationsPath}"

// Fallback generic type - replace with generated types
type ${serviceName} = Record<string, (...args: unknown[]) => Promise<unknown>>

// You'll need to define idlFactory here or import from declarations
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const idlFactory = ({ IDL }: { IDL: any }) => IDL.Service({})

// ═══════════════════════════════════════════════════════════════════════════
// REACTOR INSTANCE
// ═══════════════════════════════════════════════════════════════════════════

/**
 * ${pascalName} Reactor with ${canisterConfig.useDisplayReactor !== false ? "Display" : "Candid"} type transformations.
 * ${
   canisterConfig.useDisplayReactor !== false
     ? "Automatically converts bigint → string, Principal → string, etc."
     : "Uses raw Candid types."
 }
 */
export const ${reactorName} = new ${reactorType}<${serviceName}>({
  clientManager,
  idlFactory,
  name: "${canisterName}",
})

// ═══════════════════════════════════════════════════════════════════════════
// BASE HOOKS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Base actor hooks - use these directly or import method-specific hooks.
 */
export const {
  useActorQuery,
  useActorMutation,
  useActorSuspenseQuery,
  useActorInfiniteQuery,
  useActorSuspenseInfiniteQuery,
  useActorMethod,
} = createActorHooks(${reactorName})

/**
 * Auth hooks for the client manager.
 */
export const { useAuth, useAgentState, useUserPrincipal } = createAuthHooks(clientManager)

// ═══════════════════════════════════════════════════════════════════════════
// RE-EXPORTS
// ═══════════════════════════════════════════════════════════════════════════

export { idlFactory }
export type { ${serviceName} }
`
}
