/**
 * Client Manager Generator
 */

export interface ClientGeneratorOptions {
  /** Optional path to an existing queryClient */
  queryClientPath?: string
}

/**
 * Generate a central client manager file
 */
export function generateClientFile(
  options: ClientGeneratorOptions = {}
): string {
  const { queryClientPath } = options

  return `import { ClientManager } from "@ic-reactor/react"
${
  queryClientPath
    ? `import { queryClient } from "${queryClientPath}"`
    : `import { QueryClient } from "@tanstack/react-query"

export const queryClient = new QueryClient()`
}

/**
 * IC Reactor Client Manager
 * 
 * Auto-generated by @ic-reactor/codegen
 */
export const clientManager = new ClientManager({
  queryClient,
})
`
}
