/**
 * Client Manager Generator
 */

export interface ClientGeneratorOptions {
  queryClientPath?: string
}

export function generateClientFile(
  options: ClientGeneratorOptions = {}
): string {
  const { queryClientPath } = options

  return `/**
 * Client Manager
 *
 * Auto-generated by @ic-reactor/codegen
 * 
 * This file is the central point for managing the Agent (authentication, host, etc.)
 */

import { ClientManager } from "@ic-reactor/react"
${
  queryClientPath
    ? `import { queryClient } from "${queryClientPath}"`
    : `import { QueryClient } from "@tanstack/react-query"

export const queryClient = new QueryClient()`
}

export const clientManager = new ClientManager({ queryClient })
`
}
