/**
 * Client Manager Generator
 */

export interface ClientGeneratorOptions {
  host?: string
}

export function generateClientFile(
  options: ClientGeneratorOptions = {}
): string {
  const { host = "https://icp-api.io" } = options

  return `/**
 * Client Manager
 *
 * Auto-generated by @ic-reactor/codegen
 * 
 * This file is the central point for managing the Agent (authentication, host, etc.)
 */

import { ClientManager } from "@ic-reactor/react"

export const clientManager = new ClientManager({
  host: "${host}",
})
`
}
