/**
 * Infinite Query hook template generator
 *
 * Generates createInfiniteQuery-based hooks for paginated canister methods.
 */

import type { MethodInfo, HookType } from "../types.js"
import {
  getReactorName,
  getServiceTypeName,
  getHookExportName,
  getReactHookName,
} from "../naming.js"

export interface InfiniteQueryHookOptions {
  canisterName: string
  method: MethodInfo
  type?: HookType
}

/**
 * Generate an infinite query hook file content
 */
export function generateInfiniteQueryHook(
  options: InfiniteQueryHookOptions
): string {
  const { canisterName, method, type = "infiniteQuery" } = options

  const reactorName = getReactorName(canisterName)
  const serviceName = getServiceTypeName(canisterName)
  const hookExportName = getHookExportName(method.name, type)
  const reactHookName = getReactHookName(method.name, type)

  return `/**
 * Infinite Query: ${method.name}
 *
 * Auto-generated by @ic-reactor/codegen
 *
 * ⚠️ CUSTOMIZATION REQUIRED: Configure getArgs and getNextPageParam below.
 *
 * @example
 * const { data, fetchNextPage, hasNextPage } = ${hookExportName}.useInfiniteQuery()
 * const allItems = data?.pages.flatMap(page => page.items) ?? []
 */

import { createInfiniteQuery } from "@ic-reactor/react"
import { ${reactorName}, type ${serviceName} } from "../reactor"

/** Define your pagination cursor type */
type PageCursor = number

export const ${hookExportName} = createInfiniteQuery(${reactorName}, {
  functionName: "${method.name}",

  initialPageParam: 0 as PageCursor,

  /** Convert page param to method arguments — customize for your API */
  getArgs: (pageParam: PageCursor) => {
    return [{ offset: pageParam, limit: 10 }] as Parameters<${serviceName}["${method.name}"]>
  },

  /** Extract next page param — return undefined when no more pages */
  getNextPageParam: (lastPage, allPages, lastPageParam) => {
    // Example: offset-based
    // if (lastPage.items.length < 10) return undefined
    // return lastPageParam + 10
    return undefined
  },
})

/** React hook for paginated ${method.name} */
export const ${reactHookName} = ${hookExportName}.useInfiniteQuery
`
}
