/**
 * Mutation hook template generator
 *
 * Generates createMutation-based hooks for canister update methods.
 */

import type { MethodInfo } from "../types.js"
import { toPascalCase, getHookExportName, getReactorName } from "../naming.js"

export interface MutationHookOptions {
  canisterName: string
  method: MethodInfo
}

/**
 * Generate a mutation hook file content
 */
export function generateMutationHook(options: MutationHookOptions): string {
  const { canisterName, method } = options

  const pascalMethod = toPascalCase(method.name)
  const reactorName = getReactorName(canisterName)
  const hookExportName = getHookExportName(method.name, "mutation")

  return `/**
 * Mutation: ${method.name}
 *
 * Auto-generated by @ic-reactor/codegen
 *
 * @example
 * const { mutate, isPending } = ${hookExportName}.useMutation()
 * mutate(${method.hasArgs ? "[arg1, arg2]" : "[]"})
 *
 * // Direct execution (outside React)
 * const result = await ${hookExportName}.execute(${method.hasArgs ? "[arg1, arg2]" : "[]"})
 */

import { createMutation } from "@ic-reactor/react"
import { ${reactorName} } from "../reactor"

export const ${hookExportName} = createMutation(${reactorName}, {
  functionName: "${method.name}",
})

/** React hook for ${method.name} */
export const use${pascalMethod}Mutation = ${hookExportName}.useMutation

/** Execute ${method.name} directly (outside React) */
export const execute${pascalMethod} = ${hookExportName}.execute
`
}
