/**
 * Query hook template generator
 *
 * Generates createQuery/createQueryFactory-based hooks for canister query methods.
 */

import type { MethodInfo, HookType } from "../types.js"
import { getHookExportName, getReactorName } from "../naming.js"

export interface QueryHookOptions {
  canisterName: string
  method: MethodInfo
  type?: HookType
}

/**
 * Generate a query hook file content
 */
export function generateQueryHook(options: QueryHookOptions): string {
  const { canisterName, method, type = "query" } = options

  const reactorName = getReactorName(canisterName)
  const hookExportName = getHookExportName(method.name, type)

  const isSuspense = type === "suspenseQuery"
  const creatorFn = isSuspense ? "createSuspenseQuery" : "createQuery"
  const factoryFn = isSuspense
    ? "createSuspenseQueryFactory"
    : "createQueryFactory"
  const hookName = isSuspense ? "useSuspenseQuery" : "useQuery"

  if (method.hasArgs) {
    return `/**
 * Query Factory: ${method.name}
 *
 * Auto-generated by @ic-reactor/codegen
 *
 * @example
 * const { data } = ${hookExportName}([arg1, arg2]).${hookName}()
 * const data = await ${hookExportName}([arg1, arg2]).fetch()
 * ${hookExportName}([arg1, arg2]).invalidate()
 */

import { ${factoryFn} } from "@ic-reactor/react"
import { ${reactorName} } from "../reactor"

export const ${hookExportName} = ${factoryFn}(${reactorName}, {
  functionName: "${method.name}",
})
`
  }

  return `/**
 * Query: ${method.name}
 *
 * Auto-generated by @ic-reactor/codegen
 *
 * @example
 * const { data } = ${hookExportName}.${hookName}()
 * const data = await ${hookExportName}.fetch()
 * ${hookExportName}.invalidate()
 */

import { ${creatorFn} } from "@ic-reactor/react"
import { ${reactorName} } from "../reactor"

export const ${hookExportName} = ${creatorFn}(${reactorName}, {
  functionName: "${method.name}",
})
`
}
