/**
 * Reactor file template generator
 *
 * Generates the reactor instance file for a canister using DisplayReactor.
 * Standardizes the output to include typed hooks and clean imports.
 */

import path from "node:path"
import type { ReactorGeneratorOptions } from "../types.js"
import { toPascalCase, getReactorName, getServiceTypeName } from "../naming.js"

/**
 * Generate the reactor file content
 */
export function generateReactorFile(options: ReactorGeneratorOptions): string {
  const {
    canisterName,
    canisterConfig,
    globalClientManagerPath,
    hasDeclarations = true,
  } = options

  const pascalName = toPascalCase(canisterName)
  const reactorName = getReactorName(canisterName)
  const serviceName = getServiceTypeName(canisterName)
  // Always use DisplayReactor
  const reactorType = "DisplayReactor"

  const clientManagerPath =
    canisterConfig.clientManagerPath ??
    globalClientManagerPath ??
    "../../lib/client"

  const didFileName = path.basename(canisterConfig.didFile)
  const declarationsPath = `./declarations/${didFileName}`

  const vars: TemplateVars = {
    canisterName,
    pascalName,
    reactorName,
    serviceName,
    reactorType,
    clientManagerPath,
    declarationsPath,
  }

  // If declarations are missing, we can returns a fallback or error.
  // Given "cleanest and very nice", we'll provide a helpful fallback
  // but keeping it simple.
  if (!hasDeclarations) {
    return generateFallbackReactorFile(vars)
  }

  // If we have DID content, we can generate method-specific hooks (clean & typed)
  return generateStandardReactorFile(vars)
}

// ═══════════════════════════════════════════════════════════════════════════
// SHARED TYPES
// ═══════════════════════════════════════════════════════════════════════════

interface TemplateVars {
  canisterName: string
  pascalName: string
  reactorName: string
  serviceName: string
  reactorType: string
  clientManagerPath: string
  declarationsPath: string
}

// ═══════════════════════════════════════════════════════════════════════════
// STANDARD MODE
// ═══════════════════════════════════════════════════════════════════════════

function generateStandardReactorFile(vars: TemplateVars): string {
  const {
    pascalName,
    reactorName,
    serviceName,
    reactorType,
    clientManagerPath,
    declarationsPath,
    canisterName,
  } = vars

  // The user requested "simple and straightforward", "cleanest and very nice".
  // A clean approach is to provide the standard actor hooks.

  return `/**
 * ${pascalName} Reactor
 *
 * Auto-generated by @ic-reactor/codegen
 * 
 * DisplayReactor: automatically converts bigint -> string, Principal -> string, etc.
 */

import { ${reactorType}, createActorHooks } from "@ic-reactor/react"
import { clientManager } from "${clientManagerPath}"
import { idlFactory, type _SERVICE } from "${declarationsPath}"

export type ${serviceName} = _SERVICE

/**
 * ${pascalName} Display Reactor
 */
export const ${reactorName} = new ${reactorType}<${serviceName}>({
  clientManager,
  idlFactory,
  name: "${canisterName}",
})

const {
  useActorQuery: use${pascalName}Query,
  useActorSuspenseQuery: use${pascalName}SuspenseQuery,
  useActorInfiniteQuery: use${pascalName}InfiniteQuery,
  useActorSuspenseInfiniteQuery: use${pascalName}SuspenseInfiniteQuery,
  useActorMutation: use${pascalName}Mutation,
  useActorMethod: use${pascalName}Method,
} = createActorHooks(${reactorName})

export {
  use${pascalName}Query,
  use${pascalName}SuspenseQuery,
  use${pascalName}InfiniteQuery,
  use${pascalName}SuspenseInfiniteQuery,
  use${pascalName}Mutation,
  use${pascalName}Method,
}

export { idlFactory }
`
}

// ═══════════════════════════════════════════════════════════════════════════
// FALLBACK (NO DECLARATIONS)
// ═══════════════════════════════════════════════════════════════════════════

function generateFallbackReactorFile(vars: TemplateVars): string {
  const {
    canisterName,
    pascalName,
    serviceName,
    reactorType,
    clientManagerPath,
    declarationsPath,
    reactorName,
  } = vars

  return `/**
 * ${pascalName} Reactor
 *
 * Auto-generated by @ic-reactor/codegen
 *
 * ⚠️ Declarations were not generated. Run:
 *   npx @icp-sdk/bindgen --input <path-to-did> --output ./${canisterName}/declarations
 * Then uncomment the import below and remove the fallback type.
 */

import { ${reactorType}, createActorHooks } from "@ic-reactor/react"
import { clientManager } from "${clientManagerPath}"

// TODO: Uncomment after generating declarations:
// import { idlFactory, type _SERVICE as ${serviceName} } from "${declarationsPath}"

// Fallback — replace with generated types
type ${serviceName} = Record<string, (...args: unknown[]) => Promise<unknown>>
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const idlFactory = ({ IDL }: { IDL: any }) => IDL.Service({})

export const ${reactorName} = new ${reactorType}<${serviceName}>({
  clientManager,
  idlFactory,
  name: "${canisterName}",
})

const {
  useActorQuery: use${pascalName}Query,
  useActorSuspenseQuery: use${pascalName}SuspenseQuery,
  useActorInfiniteQuery: use${pascalName}InfiniteQuery,
  useActorSuspenseInfiniteQuery: use${pascalName}SuspenseInfiniteQuery,
  useActorMutation: use${pascalName}Mutation,
  useActorMethod: use${pascalName}Method,
} = createActorHooks(${reactorName})

export {
  use${pascalName}Query,
  use${pascalName}SuspenseQuery,
  use${pascalName}InfiniteQuery,
  use${pascalName}SuspenseInfiniteQuery,
  use${pascalName}Mutation,
  use${pascalName}Method,
}

export { idlFactory }
export type { ${serviceName} }
`
}
