/* eslint-disable */
// @ts-nocheck

/**
 * AUTO-GENERATED BY @ic-reactor/vite-plugin
 * DO NOT EDIT MANUALLY
 *
 * Canister: backend
 * Generated: 2026-01-09T08:40:45.249Z
 *
 * This file provides type-safe React hooks for interacting with the
 * backend canister using ic-reactor.
 */

import {
  DisplayReactor,
  createQuery,
  createQueryFactory,
  createMutation,
  createSuspenseQuery,
} from "@ic-reactor/react"
import { safeGetCanisterEnv } from "@icp-sdk/core/agent/canister-env"

// ═══════════════════════════════════════════════════════════════════════════
// USER-PROVIDED CLIENT MANAGER
// ═══════════════════════════════════════════════════════════════════════════
// The clientManager is imported from the user's own configuration file.
// This allows full customization of agent options, network settings, etc.
import { clientManager } from "../../lib/client"

// Import generated declarations from @icp-sdk/bindgen
import {
  idlFactory,
  type _SERVICE,
} from "./declarations/declarations/backend.did"

// ═══════════════════════════════════════════════════════════════════════════
// CANISTER ID RESOLUTION
// ═══════════════════════════════════════════════════════════════════════════

interface BackendCanisterEnv {
  readonly "PUBLIC_CANISTER_ID:backend": string
}

/**
 * Get canister ID from runtime environment (ic_env cookie)
 * Falls back to a placeholder in development
 */
function getBackendCanisterId(): string {
  const env = safeGetCanisterEnv<BackendCanisterEnv>()

  if (env?.["PUBLIC_CANISTER_ID:backend"]) {
    return env["PUBLIC_CANISTER_ID:backend"]
  }

  throw new Error("[ic-reactor] backend canister ID not found in ic_env cookie")
}

// ═══════════════════════════════════════════════════════════════════════════
// REACTOR INSTANCE
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Backend Reactor with Display type transformations.
 * Automatically converts bigint → string, Principal → string, etc.
 */
export const backendReactor = new DisplayReactor<_SERVICE>({
  clientManager,
  canisterId: getBackendCanisterId(),
  idlFactory,
  name: "backend",
})

// ═══════════════════════════════════════════════════════════════════════════
// QUERY HOOKS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Query: get_counter
 * No arguments
 * Returns: IDL.Nat
 */
export const getCounterQuery = createQuery(backendReactor, {
  functionName: "get_counter",
})
export const useGetCounter = getCounterQuery.useQuery
export const useGetCounterSuspense = createSuspenseQuery(backendReactor, {
  functionName: "get_counter",
}).useSuspenseQuery

/**
 * Query: get_message
 * No arguments
 * Returns: IDL.Opt(IDL.Text)
 */
export const getMessageQuery = createQuery(backendReactor, {
  functionName: "get_message",
})
export const useGetMessage = getMessageQuery.useQuery
export const useGetMessageSuspense = createSuspenseQuery(backendReactor, {
  functionName: "get_message",
}).useSuspenseQuery

/**
 * Query: greet
 * Args: (IDL.Text)
 * Returns: IDL.Text
 */
export const greetQuery = createQueryFactory(backendReactor, {
  functionName: "greet",
})
// Usage: greetQuery([arg1, arg2]).useQuery() or useGreet({ args: [arg1] })
export const useGreet = (
  options: { args: Parameters<_SERVICE["greet"]> } & Record<string, unknown> = {
    args: [] as any,
  }
) => greetQuery(options.args).useQuery(options)

// ═══════════════════════════════════════════════════════════════════════════
// MUTATION HOOKS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Mutation: increment
 * No arguments
 * Returns: IDL.Nat
 */
export const incrementMutation = createMutation(backendReactor, {
  functionName: "increment",
})
export const useIncrement = incrementMutation.useMutation

/**
 * Mutation: set_message
 * Args: (IDL.Text)
 * Returns: void
 */
export const setMessageMutation = createMutation(backendReactor, {
  functionName: "set_message",
  invalidateQueries: [getMessageQuery.getQueryKey()],
})
export const useSetMessage = setMessageMutation.useMutation

// ═══════════════════════════════════════════════════════════════════════════
// RE-EXPORTS
// ═══════════════════════════════════════════════════════════════════════════

export { idlFactory }
export type { _SERVICE as BackendService }
export { backendReactor as reactor }
