/**
 * Backend Reactor (Advanced)
 *
 * Auto-generated by @ic-reactor/codegen
 * Includes reactor instance, actor hooks, and per-method static hooks.
 */

import {
  DisplayReactor,
  createActorHooks,
  createQuery,
  createMutation,
} from "@ic-reactor/react"
import { clientManager } from "../../lib/client"
import { idlFactory, type _SERVICE } from "./declarations/backend.did"

type BackendService = _SERVICE

/**
 * Backend Reactor — Display mode.
 * Automatically converts bigint → string, Principal → string, etc.
 */
export const backendReactor = new DisplayReactor<BackendService>({
  clientManager,
  idlFactory,
  name: "backend",
})

const {
  useActorQuery: useBackendQuery,
  useActorSuspenseQuery: useBackendSuspenseQuery,
  useActorInfiniteQuery: useBackendInfiniteQuery,
  useActorSuspenseInfiniteQuery: useBackendSuspenseInfiniteQuery,
  useActorMutation: useBackendMutation,
  useActorMethod: useBackendMethod,
} = createActorHooks(backendReactor)

export {
  useBackendQuery,
  useBackendSuspenseQuery,
  useBackendInfiniteQuery,
  useBackendSuspenseInfiniteQuery,
  useBackendMutation,
  useBackendMethod,
}

// Per-method static hooks (no-args methods only)

export const getQuery = createQuery(backendReactor, {
  functionName: "get",
})

export const incMutation = createMutation(backendReactor, {
  functionName: "inc",
})

export { idlFactory }
export type { BackendService }
