/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from "@icp-sdk/core/agent"
import type { IDL } from "@icp-sdk/core/candid"
import type { Principal } from "@icp-sdk/core/principal"

export type ChaosResult = { ok: null } | { err: string }
export interface Log {
  action: string
  timestamp: bigint
  details: string
  caller: Principal
}
export interface Post {
  id: bigint
  content: string
  timestamp: bigint
  caller: Principal
}
export interface _SERVICE {
  batch_create_posts: ActorMethod<[bigint], Array<bigint>>
  create_post: ActorMethod<[string], bigint>
  get_chaos_status: ActorMethod<[], boolean>
  get_likes: ActorMethod<[], Array<Principal>>
  get_logs: ActorMethod<[], Array<Log>>
  get_posts: ActorMethod<[bigint, bigint], Array<Post>>
  get_posts_count: ActorMethod<[], bigint>
  like: ActorMethod<[], ChaosResult>
  toggle_chaos_mode: ActorMethod<[], boolean>
  unlike: ActorMethod<[], ChaosResult>
}
export declare const idlFactory: IDL.InterfaceFactory
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[]
