/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @icp-sdk/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import {
  Actor,
  HttpAgent,
  type HttpAgentOptions,
  type ActorConfig,
  type Agent,
  type ActorSubclass,
} from "@icp-sdk/core/agent"
import type { Principal } from "@icp-sdk/core/principal"
import { idlFactory, type _SERVICE } from "./declarations/hello_world.did"
export interface Some<T> {
  __kind__: "Some"
  value: T
}
export interface None {
  __kind__: "None"
}
export type Option<T> = Some<T> | None
function some<T>(value: T): Some<T> {
  return {
    __kind__: "Some",
    value: value,
  }
}
function none(): None {
  return {
    __kind__: "None",
  }
}
function isNone<T>(option: Option<T>): option is None {
  return option.__kind__ === "None"
}
function isSome<T>(option: Option<T>): option is Some<T> {
  return option.__kind__ === "Some"
}
function unwrap<T>(option: Option<T>): T {
  if (isNone(option)) {
    throw new Error("unwrap: none")
  }
  return option.value
}
function candid_some<T>(value: T): [T] {
  return [value]
}
function candid_none<T>(): [] {
  return []
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
  return arg == null ? undefined : arg
}
/**
 * The backend canister is a simple canister that greets the user by name.
 */
export interface hello_worldInterface {
  /**
   * Greet the user by name.
   * ## Example
   * greet("Alice") -> "Hello, Alice!"
   */
  greet(name: string): Promise<string>
}
export class Hello_world implements hello_worldInterface {
  constructor(private actor: ActorSubclass<_SERVICE>) {}
  async greet(arg0: string): Promise<string> {
    const result = await this.actor.greet(arg0)
    return result
  }
}
export interface CreateActorOptions {
  agent?: Agent
  agentOptions?: HttpAgentOptions
  actorOptions?: ActorConfig
}
export function createActor(
  canisterId: string,
  options: CreateActorOptions = {}
): Hello_world {
  const agent =
    options.agent ||
    HttpAgent.createSync({
      ...options.agentOptions,
    })
  if (options.agent && options.agentOptions) {
    console.warn(
      "Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent."
    )
  }
  const actor = Actor.createActor<_SERVICE>(idlFactory, {
    agent,
    canisterId: canisterId,
    ...options.actorOptions,
  })
  return new Hello_world(actor)
}
