export type { Infer, InferRecord, InferVariant, InferTuple } from "./types"
export { CandidOptCodec, opt } from "./opt"
export { CandidVecCodec, vec } from "./vec"
export { CandidRecordCodec, record } from "./record"
export { CandidVariantCodec, variant } from "./variant"
export { CandidTupleCodec, tuple } from "./tuple"
