/**
 * Rebuilds the web and Node entry points so the parser survives a WebAssembly
 * trap.
 *
 * A Rust panic ends in a trap (`RuntimeError: unreachable`), and deeply nested
 * or very long input can exhaust the stack (`RangeError`, or a trap once the
 * WebAssembly shadow stack runs out). Either way the instance never restores its
 * stack pointer, and every later call on it fails with "memory access out of
 * bounds". The entries this script writes catch those two error types, replace
 * the instance with a fresh one built from the compiled `WebAssembly.Module`
 * they already hold, and rethrow a readable error with the original as `cause`.
 *
 * wasm-bindgen's web and Node glue keep their instance in private variables,
 * and that code changes between releases (0.2.108 declares the Node instance
 * `const`, 0.2.111 `let`, 0.2.126 adds a `wasmInstance` variable), so a patch
 * against it breaks on upgrades. The bundler glue has a stable public shape
 * instead. It is a module of `export function` declarations, the WebAssembly
 * file imports its shims from that module, and `__wbg_set_wasm` binds it to an
 * instance. This script wraps that module in a factory, so each instance gets
 * its own copy of the glue state, and generates entries that call the factory.
 * Every function the bundler entry exports gets a guarded wrapper, so a new
 * `#[wasm_bindgen]` export is covered without touching this file.
 *
 * `dist/bundler` keeps wasm-bindgen's own output. The bundler instantiates that
 * build from its `.wasm` import and never exposes the compiled module, so it
 * cannot be re-instantiated without fetching the file again.
 */
const { readFileSync, writeFileSync } = require("node:fs")
const { join, resolve } = require("node:path")

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/

const HEADER =
  "// Generated by scripts/wrap-glue.js from wasm-bindgen's bundler output. Do not edit."

/**
 * Reads the public export names out of wasm-bindgen's bundler entry, after
 * checking that the entry still starts the instance the way the generated
 * entries do.
 */
function publicExports(entry) {
  const match = entry.match(
    new RegExp(
      [
        '^(?:/\\* @ts-self-types="\\./index\\.d\\.ts" \\*/\\s*)?',
        'import \\* as wasm from "\\./index_bg\\.wasm";\\s*',
        'import \\{ __wbg_set_wasm \\} from "\\./index_bg\\.js";\\s*',
        "__wbg_set_wasm\\(wasm\\);\\s*",
        "wasm\\.__wbindgen_start\\(\\);\\s*",
        'export \\{([^}]*)\\} from "\\./index_bg\\.js";\\s*$',
      ].join("")
    )
  )
  if (!match) {
    throw new Error(
      "wasm-bindgen's bundler entry (dist/bundler/index.js) no longer starts " +
        "the instance the way scripts/wrap-glue.js does (call __wbg_set_wasm, " +
        "then __wbindgen_start). Update the script to match the new output."
    )
  }
  const names = match[1]
    .split(",")
    .map((name) => name.trim())
    .filter(Boolean)
  const invalid = names.find((name) => !IDENTIFIER.test(name))
  if (invalid !== undefined) {
    throw new Error(`The bundler entry exports "${invalid}", not a plain name.`)
  }
  return names
}

/**
 * Checks that the bundler glue can move inside a function and lists the
 * functions it exports with their parameters.
 */
function readGlue(glue) {
  if (/^import\b/m.test(glue) || glue.includes("import.meta")) {
    throw new Error(
      "wasm-bindgen's bundler glue (dist/bundler/index_bg.js) now imports " +
        "other modules or reads import.meta, and neither works inside a " +
        "factory function. Update scripts/wrap-glue.js."
    )
  }

  const functions = new Map()
  for (const line of glue.match(/^export\b.*$/gm) ?? []) {
    const match = line.match(/^export function ([A-Za-z_$][\w$]*)\(([^)]*)\)/)
    const params = match?.[2].split(",").map((param) => param.trim())
    if (!match || params.some((param) => param && !IDENTIFIER.test(param))) {
      throw new Error(
        "wasm-bindgen's bundler glue has an export scripts/wrap-glue.js " +
          `cannot wrap (${JSON.stringify(line)}). The script supports ` +
          "`export function name(a, b)` declarations only."
      )
    }
    functions.set(match[1], params.filter(Boolean).join(", "))
  }

  if (!functions.has("__wbg_set_wasm")) {
    throw new Error(
      "wasm-bindgen's bundler glue no longer exports __wbg_set_wasm, which " +
        "binds the glue to an instance. Update scripts/wrap-glue.js."
    )
  }

  return functions
}

function factory(glue, functions, format) {
  const names = [...functions.keys()].join(", ")
  return [
    ...(format === "cjs" ? ['"use strict";'] : []),
    HEADER,
    "// Every call returns a separate copy of the glue with its own state.",
    `${format === "esm" ? "export " : ""}function createBindings() {`,
    glue.replace(/^export function /gm, "function ").trimEnd(),
    `return { ${names} };`,
    "}",
    ...(format === "cjs" ? ["exports.createBindings = createBindings;"] : []),
    "",
  ].join("\n")
}

/** Code every entry shares. It expects `createBindings` in scope. */
const RUNTIME = `
let wasmModule;
let bindings;
let wasm;

function importsFor(module, next) {
    const imports = {};
    for (const entry of WebAssembly.Module.imports(module)) {
        imports[entry.module] = next;
    }
    return imports;
}

// wasm-bindgen's bundler entry makes the same two calls once the bundler has
// instantiated the module.
function start(module, instance, next) {
    next.__wbg_set_wasm(instance.exports);
    instance.exports.__wbindgen_start();
    wasmModule = module;
    bindings = next;
    wasm = instance.exports;
    return wasm;
}

function instantiateSync(module) {
    const next = createBindings();
    const instance = new WebAssembly.Instance(module, importsFor(module, next));
    return start(module, instance, next);
}

// A trap or a stack overflow leaves the instance's stack pointer where the
// failed call stopped, so later calls on that instance run out of memory.
// Swap in a new instance of the same compiled module before reporting the
// failure. If the new instance cannot be created, that error propagates and
// the next call tries again.
function recover(error) {
    if (!(error instanceof WebAssembly.RuntimeError || error instanceof RangeError)) {
        return error;
    }
    instantiateSync(wasmModule);
    return new Error(
        "The Candid parser could not parse this input. It hit an internal error (" +
            error +
            ") and restarted, so later calls still work.",
        { cause: error }
    );
}
`

function wrappers(names, functions, format) {
  return names
    .map((name) => {
      if (!functions.has(name)) {
        throw new Error(
          `The bundler entry exports ${name}, but the glue does not declare it.`
        )
      }
      const params = functions.get(name)
      return [
        `${format === "esm" ? "export " : ""}function ${name}(${params}) {`,
        "    try {",
        `        return bindings.${name}(${params});`,
        "    } catch (error) {",
        "        throw recover(error);",
        "    }",
        "}",
        ...(format === "cjs" ? [`exports.${name} = ${name};`] : []),
      ].join("\n")
    })
    .join("\n\n")
}

/**
 * Mirrors the loading in wasm-bindgen's web entry (`initSync` and the default
 * `init`), except that it keeps the compiled module for `recover`.
 */
const WEB_LOADER = `
async function instantiateAsync(module) {
    const next = createBindings();
    const instance = await WebAssembly.instantiate(module, importsFor(module, next));
    return start(module, instance, next);
}

function expectedResponseType(type) {
    switch (type) {
        case "basic": case "cors": case "default": return true;
    }
    return false;
}

async function compile(source) {
    if (source instanceof WebAssembly.Module) {
        return source;
    }
    if (typeof Response === "function" && source instanceof Response) {
        if (typeof WebAssembly.compileStreaming === "function") {
            try {
                return await WebAssembly.compileStreaming(source);
            } catch (e) {
                const validResponse = source.ok && expectedResponseType(source.type);

                if (validResponse && source.headers.get("Content-Type") !== "application/wasm") {
                    console.warn("\`WebAssembly.compileStreaming\` failed because your server does not serve Wasm with \`application/wasm\` MIME type. Falling back to \`WebAssembly.compile\` which is slower. Original error:\\n", e);

                } else { throw e; }
            }
        }

        return WebAssembly.compile(await source.arrayBuffer());
    }
    return WebAssembly.compile(source);
}

function initSync(module) {
    if (wasm !== undefined) return wasm;

    if (module !== undefined) {
        if (Object.getPrototypeOf(module) === Object.prototype) {
            ({module} = module)
        } else {
            console.warn("using deprecated parameters for \`initSync()\`; pass a single object instead")
        }
    }

    if (!(module instanceof WebAssembly.Module)) {
        module = new WebAssembly.Module(module);
    }
    return instantiateSync(module);
}

async function __wbg_init(module_or_path) {
    if (wasm !== undefined) return wasm;

    if (module_or_path !== undefined) {
        if (Object.getPrototypeOf(module_or_path) === Object.prototype) {
            ({module_or_path} = module_or_path)
        } else {
            console.warn("using deprecated parameters for the initialization function; pass a single object instead")
        }
    }

    if (module_or_path === undefined) {
        module_or_path = new URL("index_bg.wasm", import.meta.url);
    }

    if (typeof module_or_path === "string" || (typeof Request === "function" && module_or_path instanceof Request) || (typeof URL === "function" && module_or_path instanceof URL)) {
        module_or_path = fetch(module_or_path);
    }

    return instantiateAsync(await compile(await module_or_path));
}

export { initSync, __wbg_init as default };
`

/**
 * Returns the files to write, keyed by path relative to `dist`, for
 * wasm-bindgen's bundler entry (`entry`) and glue (`glue`) sources.
 */
function wrapGlue({ entry, glue }) {
  const names = publicExports(entry)
  const functions = readGlue(glue)
  return {
    "web/index.js": [
      '/* @ts-self-types="./index.d.ts" */',
      HEADER,
      'import { createBindings } from "./index_bg.js";',
      RUNTIME,
      wrappers(names, functions, "esm"),
      WEB_LOADER,
    ].join("\n"),
    "web/index_bg.js": factory(glue, functions, "esm"),
    "nodejs/index.js": [
      '"use strict";',
      HEADER,
      'const { createBindings } = require("./index_bg.js");',
      RUNTIME,
      wrappers(names, functions, "cjs"),
      "",
      "const wasmPath = `${__dirname}/index_bg.wasm`;",
      'const wasmBytes = require("fs").readFileSync(wasmPath);',
      "instantiateSync(new WebAssembly.Module(wasmBytes));",
      "",
    ].join("\n"),
    "nodejs/index_bg.js": factory(glue, functions, "cjs"),
  }
}

function main() {
  const dist = join(resolve(__dirname, ".."), "dist")
  const files = wrapGlue({
    entry: readFileSync(join(dist, "bundler", "index.js"), "utf-8"),
    glue: readFileSync(join(dist, "bundler", "index_bg.js"), "utf-8"),
  })
  for (const [path, content] of Object.entries(files)) {
    writeFileSync(join(dist, path), content, "utf-8")
    console.log(`Wrote ${join(dist, path)}`)
  }
}

module.exports = { wrapGlue }

if (require.main === module) {
  main()
}
