// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $ArchivedRange = { callback: $QueryArchiveFn; start: bigint; length: bigint };
const $ArchivedRange: $.Schema<$ArchivedRange> = $.c.rec(() => $.c.record({ callback: $QueryArchiveFn, start: $.c.nat, length: $.c.nat }));
export { $ArchivedRange as ArchivedRange };

type $Block = { memo: Uint8Array; index: bigint };
const $Block: $.Schema<$Block> = $.c.rec(() => $.c.record({ memo: $.c.blob(), index: $.c.nat }));
export { $Block as Block };

type $BlockRange = { blocks: Array<$Block> };
const $BlockRange: $.Schema<$BlockRange> = $.c.rec(() => $.c.record({ blocks: $.c.vec($Block) }));
export { $BlockRange as BlockRange };

type $GetBlocksArgs = { start: bigint; length: bigint };
const $GetBlocksArgs: $.Schema<$GetBlocksArgs> = $.c.rec(() => $.c.record({ start: $.c.nat, length: $.c.nat }));
export { $GetBlocksArgs as GetBlocksArgs };

type $GetBlocksResponse = { first_index: bigint; blocks: Array<$Block>; archived_blocks: Array<$ArchivedRange> };
const $GetBlocksResponse: $.Schema<$GetBlocksResponse> = $.c.rec(() => $.c.record({ first_index: $.c.nat, blocks: $.c.vec($Block), archived_blocks: $.c.vec($ArchivedRange) }));
export { $GetBlocksResponse as GetBlocksResponse };

/** A callback that writes. */
type $NotifyFn = { principal: $.Principal; method: string };
/** A callback that writes. */
const $NotifyFn: $.Schema<$NotifyFn> = $.c.rec(() => $.c.func([$.c.text], [$.c.nat], "update"));
export { $NotifyFn as NotifyFn };

/**
 * How an archive canister is read: its principal and method arrive in the
 * ledger's reply.
 */
type $QueryArchiveFn = { principal: $.Principal; method: string };
/**
 * How an archive canister is read: its principal and method arrive in the
 * ledger's reply.
 */
const $QueryArchiveFn: $.Schema<$QueryArchiveFn> = $.c.rec(() => $.c.func([$GetBlocksArgs], [$BlockRange], "query"));
export { $QueryArchiveFn as QueryArchiveFn };

/**
 * A ledger whose old blocks live in archive canisters, as ICRC-3 and the ICP
 * ledger keep them: a reply carries a func reference per archived range.
 */
const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ get_blocks: $.c.func([$GetBlocksArgs], [$GetBlocksResponse], "query"), notify_hook: $.c.func([], [$NotifyFn], "query") }));
/**
 * A ledger whose old blocks live in archive canisters, as ICRC-3 and the ICP
 * ledger keep them: a reply carries a func reference per archived range.
 */
type $Actor = {
  get_blocks: (arg0: $GetBlocksArgs) => Promise<$GetBlocksResponse>;
  notify_hook: () => Promise<$NotifyFn>;
};
export { $actor as actor, type $Actor as Actor };
