// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

/** A result whose ok arm carries nothing. */
type $Flag = { tag: "ok" } | { tag: "err"; value: string };
/** A result whose ok arm carries nothing. */
const $Flag: $.Schema<$Flag> = $.c.rec(() => $.c.variant({ ok: $.c.null, err: $.c.text }));
export { $Flag as Flag };

/** A result spelled in lower case. */
type $Outcome = { tag: "ok"; value: bigint } | { tag: "err"; value: string };
/** A result spelled in lower case. */
const $Outcome: $.Schema<$Outcome> = $.c.rec(() => $.c.variant({ ok: $.c.nat64, err: $.c.text }));
export { $Outcome as Outcome };

type $Pair = { left: bigint; right: string };
const $Pair: $.Schema<$Pair> = $.c.rec(() => $.c.record({ left: $.c.nat, right: $.c.text }));
export { $Pair as Pair };

/** Ok, Err and a third arm: not a result, so it is never unwrapped. */
type $Three = { tag: "Ok"; value: bigint } | { tag: "Err"; value: string } | { tag: "Pending" };
/** Ok, Err and a third arm: not a result, so it is never unwrapped. */
const $Three: $.Schema<$Three> = $.c.rec(() => $.c.variant({ Ok: $.c.nat, Err: $.c.text, Pending: $.c.null }));
export { $Three as Three };

/**
 * One method per shape the call path handles: 0, 1 and n results, a void
 * update, a oneway, a composite query, and the values whose JavaScript form
 * differs (nat8 as number, a collapsing opt, a blob, a principal).
 */
const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ one: $.c.func([$.c.nat], [$.c.nat], "query"), who: $.c.func([], [$.c.principal], "query"), maybe: $.c.func([$.c.opt($.c.opt($.c.nat))], [$.c.opt($.c.opt($.c.nat))], "query"), three: $.c.func([], [$Three], "update"), composite: $.c.func([$.c.nat], [$.c.nat], "composite_query"), bump: $.c.func([$.c.nat], [$Outcome], "update"), fire: $.c.func([$.c.text], [], "oneway"), flag: $.c.func([$.c.bool], [$Flag], "update"), many: $.c.func([], [$.c.nat, $.c.text, $.c.bool], "query"), note: $.c.func([$.c.text], [], "update"), pair: $.c.func([$.c.nat, $.c.text], [$Pair], "query"), nothing: $.c.func([], [], "query"), lookup: $.c.func([$.c.principal], [$.c.opt($.c.text)], "query"), small: $.c.func([$.c.nat8], [$.c.nat8], "query"), address: $.c.func([$.c.text], [$.c.text], "update"), bytes: $.c.func([$.c.blob()], [$.c.blob()], "query"), outcome: $.c.func([$.c.nat64], [$Outcome], "query") }));
/**
 * One method per shape the call path handles: 0, 1 and n results, a void
 * update, a oneway, a composite query, and the values whose JavaScript form
 * differs (nat8 as number, a collapsing opt, a blob, a principal).
 */
type $Actor = {
  one: (arg0: bigint) => Promise<bigint>;
  who: () => Promise<$.Principal>;
  maybe: (arg0: { some: bigint | null } | null) => Promise<{ some: bigint | null } | null>;
  three: () => Promise<$Three>;
  composite: (arg0: bigint) => Promise<bigint>;
  bump: (arg0: bigint) => Promise<$Outcome>;
  fire: (arg0: string) => Promise<void>;
  flag: (arg0: boolean) => Promise<$Flag>;
  many: () => Promise<[bigint, string, boolean]>;
  note: (arg0: string) => Promise<void>;
  pair: (arg0: bigint, arg1: string) => Promise<$Pair>;
  nothing: () => Promise<void>;
  lookup: (arg0: $.Principal) => Promise<string | null>;
  small: (arg0: number) => Promise<number>;
  address: (arg0: string) => Promise<string>;
  bytes: (arg0: Uint8Array) => Promise<Uint8Array>;
  outcome: (arg0: bigint) => Promise<$Outcome>;
};
export { $actor as actor, type $Actor as Actor };
