// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $Empty = Record<string, never>;
const $Empty: $.Schema<$Empty> = $.c.rec(() => $.c.unit());
export { $Empty as Empty };

type $Options = { limit: bigint | null; prefix: string | null };
const $Options: $.Schema<$Options> = $.c.rec(() => $.c.record({ limit: $.c.opt($.c.nat), prefix: $.c.opt($.c.text) }));
export { $Options as Options };

/**
 * One method per shape of variables `skipToken` might be assignable to: an
 * empty record, a record of opts alone, an opt, reserved, null, and no
 * arguments. Only a read whose variables cannot hold `skipToken` gives
 * options without `SkipToken` in their `queryFn` type.
 */
const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ no_args: $.c.func([], [$.c.nat], "query"), maybe_nat: $.c.func([$.c.opt($.c.nat)], [$.c.nat], "query"), nothing_at_all: $.c.func([$.c.null], [$.c.nat], "query"), only_opts: $.c.func([$Options], [$.c.nat], "query"), empty_record: $.c.func([$Empty], [$.c.nat], "query"), anything: $.c.func([$.c.reserved], [$.c.nat], "query") }));
/**
 * One method per shape of variables `skipToken` might be assignable to: an
 * empty record, a record of opts alone, an opt, reserved, null, and no
 * arguments. Only a read whose variables cannot hold `skipToken` gives
 * options without `SkipToken` in their `queryFn` type.
 */
type $Actor = {
  no_args: () => Promise<bigint>;
  maybe_nat: (arg0: bigint | null) => Promise<bigint>;
  nothing_at_all: (arg0: null) => Promise<bigint>;
  only_opts: (arg0: $Options) => Promise<bigint>;
  empty_record: (arg0: $Empty) => Promise<bigint>;
  anything: (arg0: unknown) => Promise<bigint>;
};
export { $actor as actor, type $Actor as Actor };
