import { createActorHooks } from "@ic-reactor/react"
import { DisplayReactor } from "@ic-reactor/react"
import { clientManager } from "../../clients"
import { idlFactory, type _SERVICE } from "./declarations/backend"

export type BackendService = _SERVICE

/**
 * Backend Reactor
 *
 * Auto-generated by @ic-reactor/codegen — do not edit.
 * This file is overwritten whenever generation runs.
 */
export const backendReactor = new DisplayReactor<BackendService>({
  clientManager,
  idlFactory,
  name: "backend",
})

export const {
  useActorQuery: useBackendQuery,
  useActorSuspenseQuery: useBackendSuspenseQuery,
  useActorInfiniteQuery: useBackendInfiniteQuery,
  useActorSuspenseInfiniteQuery: useBackendSuspenseInfiniteQuery,
  useActorMutation: useBackendMutation,
  useActorMethod: useBackendMethod,
} = createActorHooks(backendReactor)
