// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ increment: $.c.func([], [$.c.nat], "update"), boom: $.c.func([], [], "update"), count: $.c.func([], [$.c.nat], "query"), greet: $.c.func([$.c.text], [$.c.text], "query"), is_replicated: $.c.func([], [$.c.bool], "query"), whoami: $.c.func([], [$.c.principal], "query"), increment_by: $.c.func([$.c.nat64], [$.c.variant({ Ok: $.c.nat, Err: $.c.text })], "update"), refuse: $.c.func([], [], "update") }));
type $Actor = {
  increment: () => Promise<bigint>;
  boom: () => Promise<void>;
  count: () => Promise<bigint>;
  greet: (arg0: string) => Promise<string>;
  is_replicated: () => Promise<boolean>;
  whoami: () => Promise<$.Principal>;
  increment_by: (arg0: bigint) => Promise<{ tag: "Ok"; value: bigint } | { tag: "Err"; value: string }>;
  refuse: () => Promise<void>;
};
export { $actor as actor, type $Actor as Actor };
