// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $Contact = { owner: $.Principal; name: string };
const $Contact: $.Schema<$Contact> = $.c.rec(() => $.c.record({ owner: $.c.principal, name: $.c.text }));
export { $Contact as Contact };

type $Profile = { name: string };
const $Profile: $.Schema<$Profile> = $.c.rec(() => $.c.record({ name: $.c.text }));
export { $Profile as Profile };

/**
 * Why a write was refused. ic-reactor rejects such a reply as a
 * `canister_err`, with this value in its `err`.
 */
type $Refusal =
  | {
      /** The caller is the anonymous principal. */
      tag: "Anonymous";
    }
  | {
      /** The address book holds at most this many contacts. */
      tag: "Full";
      value: number;
    }
  | {
      /** The address book already has a contact of this name. */
      tag: "DuplicateName";
      value: string;
    }
  | {
      /** The address book has no contact of this name. */
      tag: "NotFound";
      value: string;
    }
  | {
      /** The name is empty, longer than 32 characters, or has a control character. */
      tag: "InvalidName";
      value: string;
    };
/**
 * Why a write was refused. ic-reactor rejects such a reply as a
 * `canister_err`, with this value in its `err`.
 */
const $Refusal: $.Schema<$Refusal> = $.c.rec(() => $.c.variant({ Anonymous: $.c.null, Full: $.c.nat32, DuplicateName: $.c.text, NotFound: $.c.text, InvalidName: $.c.text }));
export { $Refusal as Refusal };

const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ contacts: $.c.func([], [$.c.vec($Contact)], "query"), remove_contact: $.c.func([$.c.text], [$.c.variant({ Ok: $.c.null, Err: $Refusal })], "update"), set_name: $.c.func([$.c.text], [$.c.variant({ Ok: $Profile, Err: $Refusal })], "update"), get_profile: $.c.func([], [$.c.opt($Profile)], "query"), add_contact: $.c.func([$Contact], [$.c.variant({ Ok: $.c.null, Err: $Refusal })], "update") }));
type $Actor = {
  /** The caller's contacts, in the order they were added. */
  contacts: () => Promise<Array<$Contact>>;
  remove_contact: (arg0: string) => Promise<{ tag: "Ok" } | { tag: "Err"; value: $Refusal }>;
  set_name: (arg0: string) => Promise<{ tag: "Ok"; value: $Profile } | { tag: "Err"; value: $Refusal }>;
  /** The caller's profile, or null before their first set_name. */
  get_profile: () => Promise<$Profile | null>;
  add_contact: (arg0: $Contact) => Promise<{ tag: "Ok" } | { tag: "Err"; value: $Refusal }>;
};
export { $actor as actor, type $Actor as Actor };
