// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $Account = { owner: $.Principal; subaccount: $Subaccount | null };
const $Account: $.Schema<$Account> = $.c.rec(() => $.c.record({ owner: $.c.principal, subaccount: $.c.opt($Subaccount) }));
export { $Account as Account };

type $BlockIndex = bigint;
const $BlockIndex: $.Schema<$BlockIndex> = $.c.rec(() => $.c.nat);
export { $BlockIndex as BlockIndex };

type $Subaccount = Uint8Array;
const $Subaccount: $.Schema<$Subaccount> = $.c.rec(() => $.c.blob());
export { $Subaccount as Subaccount };

/** Nanoseconds since the UNIX epoch, in UTC. */
type $Timestamp = bigint;
/** Nanoseconds since the UNIX epoch, in UTC. */
const $Timestamp: $.Schema<$Timestamp> = $.c.rec(() => $.c.nat64);
export { $Timestamp as Timestamp };

type $Tokens = bigint;
const $Tokens: $.Schema<$Tokens> = $.c.rec(() => $.c.nat);
export { $Tokens as Tokens };

type $TransferArg = { to: $Account; fee: bigint | null; memo: $Subaccount | null; from_subaccount: $Subaccount | null; created_at_time: bigint | null; amount: bigint };
const $TransferArg: $.Schema<$TransferArg> = $.c.rec(() => $.c.record({ to: $Account, fee: $.c.opt($.c.nat), memo: $.c.opt($Subaccount), from_subaccount: $.c.opt($Subaccount), created_at_time: $.c.opt($.c.nat64), amount: $.c.nat }));
export { $TransferArg as TransferArg };

type $TransferError = { tag: "GenericError"; value: { message: string; error_code: bigint } } | { tag: "TemporarilyUnavailable" } | { tag: "BadBurn"; value: { min_burn_amount: bigint } } | { tag: "Duplicate"; value: { duplicate_of: bigint } } | { tag: "BadFee"; value: { expected_fee: bigint } } | { tag: "CreatedInFuture"; value: { ledger_time: bigint } } | { tag: "TooOld" } | { tag: "InsufficientFunds"; value: { balance: bigint } };
const $TransferError: $.Schema<$TransferError> = $.c.rec(() => $.c.variant({ GenericError: $.c.record({ message: $.c.text, error_code: $.c.nat }), TemporarilyUnavailable: $.c.null, BadBurn: $.c.record({ min_burn_amount: $.c.nat }), Duplicate: $.c.record({ duplicate_of: $.c.nat }), BadFee: $.c.record({ expected_fee: $.c.nat }), CreatedInFuture: $.c.record({ ledger_time: $.c.nat64 }), TooOld: $.c.null, InsufficientFunds: $.c.record({ balance: $.c.nat }) }));
export { $TransferError as TransferError };

type $TransferResult = { tag: "Ok"; value: bigint } | { tag: "Err"; value: $TransferError };
const $TransferResult: $.Schema<$TransferResult> = $.c.rec(() => $.c.variant({ Ok: $.c.nat, Err: $TransferError }));
export { $TransferResult as TransferResult };

const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ icrc1_balance_of: $.c.func([$Account], [$.c.nat], "query"), icrc1_decimals: $.c.func([], [$.c.nat8], "query"), icrc1_fee: $.c.func([], [$.c.nat], "query"), icrc1_symbol: $.c.func([], [$.c.text], "query"), icrc1_transfer: $.c.func([$TransferArg], [$TransferResult], "update") }));
type $Actor = {
  icrc1_balance_of: (arg0: $Account) => Promise<bigint>;
  icrc1_decimals: () => Promise<number>;
  icrc1_fee: () => Promise<bigint>;
  icrc1_symbol: () => Promise<string>;
  icrc1_transfer: (arg0: $TransferArg) => Promise<$TransferResult>;
};
export { $actor as actor, type $Actor as Actor };
