use std::collections::BTreeSet;

use anyhow::Result;
use candid::types::{Field, Function, Label, SharedLabel, Type, TypeEnv, TypeInner};
use candid_parser::syntax::{self, Binding, IDLMergedProg, IDLType};

use crate::config::GeneratorConfig;
use crate::docs::DocBlock;

const TS_KEYWORDS: &[&str] = &[
    "abstract",
    "any",
    "as",
    "asserts",
    "async",
    "await",
    "bigint",
    "boolean",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "constructor",
    "continue",
    "debugger",
    "declare",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "from",
    "function",
    "get",
    "if",
    "implements",
    "import",
    "in",
    "infer",
    "instanceof",
    "interface",
    "is",
    "keyof",
    "let",
    "module",
    "namespace",
    "never",
    "new",
    "null",
    "number",
    "object",
    "package",
    "private",
    "protected",
    "public",
    "readonly",
    "require",
    "return",
    "satisfies",
    "set",
    "static",
    "string",
    "super",
    "switch",
    "symbol",
    "this",
    "throw",
    "true",
    "try",
    "type",
    "typeof",
    "undefined",
    "unique",
    "unknown",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

pub fn generate_typescript(
    env: &TypeEnv,
    actor: &Option<Type>,
    prog: &IDLMergedProg,
    config: &GeneratorConfig,
) -> Result<String> {
    let mut out = String::new();

    if config.emit_banner {
        out.push_str("// Generated by cod. Do not edit by hand.\n");
    }
    out.push_str("import { c } from \"cod\";\n\n");

    let mut emitted_types = BTreeSet::new();
    for (id, ty) in env.to_sorted_iter() {
        let syntax = prog.lookup(id);
        push_named_schema(&mut out, env, id, ty, syntax, &emitted_types)?;
        emitted_types.insert(id.to_string());
        out.push('\n');
    }

    if let Some(actor_ty) = actor {
        let syntax_actor = prog.resolve_actor().ok().flatten();
        push_actor_schema(
            &mut out,
            config,
            env,
            actor_ty,
            syntax_actor.as_ref().map(|actor| &actor.typ),
            syntax_actor.as_ref().map(|actor| actor.docs.as_slice()),
            &emitted_types,
        )?;
        if !emitted_types.is_empty() {
            out.push('\n');
        }
    }

    Ok(out.trim_end().to_string() + "\n")
}

fn push_named_schema(
    out: &mut String,
    env: &TypeEnv,
    id: &str,
    ty: &Type,
    syntax: Option<&Binding>,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    let docs = syntax
        .map(|binding| DocBlock::parse(&binding.docs))
        .unwrap_or_default();
    push_doc_comment(out, &docs, "");

    let name = type_name(id);
    match ty.as_ref() {
        TypeInner::Service(methods) => {
            out.push_str("export const ");
            out.push_str(&name);
            out.push_str(" = ");
            push_service_schema_expr(
                out,
                env,
                methods,
                syntax.map(|binding| &binding.typ),
                "",
                available_refs,
            )?;
            out.push_str(";\n");
            out.push_str("export type ");
            out.push_str(&name);
            out.push_str(" = c.ActorFor<typeof ");
            out.push_str(&name);
            out.push_str(".methods>;\n");
        }
        _ => {
            out.push_str("export const ");
            out.push_str(&name);
            out.push_str(" = ");
            push_schema_expr(
                out,
                env,
                ty,
                syntax.map(|binding| &binding.typ),
                "",
                available_refs,
            )?;
            out.push_str(";\n");
            out.push_str("export type ");
            out.push_str(&name);
            out.push_str(" = c.Infer<typeof ");
            out.push_str(&name);
            out.push_str(">;\n");
        }
    }

    Ok(())
}

fn push_actor_schema(
    out: &mut String,
    config: &GeneratorConfig,
    env: &TypeEnv,
    actor: &Type,
    syntax: Option<&IDLType>,
    docs: Option<&[String]>,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    if let TypeInner::Class(args, inner) = actor.as_ref() {
        out.push_str("export const initArgs = c.tuple(");
        push_schema_tuple_arg(out, env, args, "", available_refs)?;
        out.push_str(");\n");
        out.push_str("export type InitArgs = c.Infer<typeof initArgs>;\n\n");
        return push_actor_schema(
            out,
            config,
            env,
            inner,
            class_inner_syntax(syntax),
            docs,
            available_refs,
        );
    }

    let docs = docs.map(DocBlock::parse).unwrap_or_default();
    push_doc_comment(out, &docs, "");
    match actor.as_ref() {
        TypeInner::Service(methods) => {
            out.push_str("export const ");
            out.push_str(&canister_export_name(&config.canister_name));
            out.push_str(" = ");
            push_service_schema_expr(out, env, methods, syntax, "", available_refs)?;
            out.push_str(";\n");
        }
        TypeInner::Var(id) => {
            out.push_str("export const ");
            out.push_str(&canister_export_name(&config.canister_name));
            out.push_str(" = ");
            out.push_str(&type_name(id));
            out.push_str(";\n");
        }
        _ => {}
    }

    Ok(())
}

fn push_schema_expr(
    out: &mut String,
    env: &TypeEnv,
    ty: &Type,
    syntax: Option<&IDLType>,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    if ty.is_blob(env) {
        out.push_str("c.blob()");
        return Ok(());
    }

    match (ty.as_ref(), syntax) {
        (TypeInner::Record(fields), Some(IDLType::RecordT(syntax_fields))) => {
            push_record_schema_expr(
                out,
                env,
                fields,
                Some(syntax_fields),
                indent,
                available_refs,
            )
        }
        (TypeInner::Variant(fields), Some(IDLType::VariantT(syntax_fields))) => {
            push_variant_schema_expr(
                out,
                env,
                fields,
                Some(syntax_fields),
                indent,
                available_refs,
            )
        }
        (TypeInner::Opt(inner), Some(IDLType::OptT(syntax_inner))) => push_wrapped_schema_expr(
            out,
            "c.opt",
            env,
            inner,
            Some(syntax_inner),
            indent,
            available_refs,
        ),
        (TypeInner::Vec(inner), Some(IDLType::VecT(syntax_inner))) => push_wrapped_schema_expr(
            out,
            "c.vec",
            env,
            inner,
            Some(syntax_inner),
            indent,
            available_refs,
        ),
        _ => push_schema_expr_plain(out, env, ty, indent, available_refs),
    }
}

fn push_schema_expr_plain(
    out: &mut String,
    env: &TypeEnv,
    ty: &Type,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    match ty.as_ref() {
        TypeInner::Null => out.push_str("c.null()"),
        TypeInner::Bool => out.push_str("c.bool()"),
        TypeInner::Nat => out.push_str("c.nat()"),
        TypeInner::Int => out.push_str("c.int()"),
        TypeInner::Nat8 => out.push_str("c.nat8()"),
        TypeInner::Nat16 => out.push_str("c.nat16()"),
        TypeInner::Nat32 => out.push_str("c.nat32()"),
        TypeInner::Nat64 => out.push_str("c.nat64()"),
        TypeInner::Int8 => out.push_str("c.int8()"),
        TypeInner::Int16 => out.push_str("c.int16()"),
        TypeInner::Int32 => out.push_str("c.int32()"),
        TypeInner::Int64 => out.push_str("c.int64()"),
        TypeInner::Float32 => out.push_str("c.float32()"),
        TypeInner::Float64 => out.push_str("c.float64()"),
        TypeInner::Text => out.push_str("c.text()"),
        TypeInner::Principal => out.push_str("c.principal()"),
        TypeInner::Var(id) => {
            if available_refs.contains(id) {
                out.push_str(&type_name(id));
            } else {
                out.push_str("c.lazy(() => ");
                out.push_str(&type_name(id));
                out.push_str(", ");
                out.push_str(&json_string(id));
                out.push(')');
            }
        }
        TypeInner::Opt(inner) => {
            push_wrapped_schema_expr(out, "c.opt", env, inner, None, indent, available_refs)?;
        }
        TypeInner::Vec(inner) => {
            push_wrapped_schema_expr(out, "c.vec", env, inner, None, indent, available_refs)?;
        }
        TypeInner::Record(fields) => {
            push_record_schema_expr(out, env, fields, None, indent, available_refs)?;
        }
        TypeInner::Variant(fields) => {
            push_variant_schema_expr(out, env, fields, None, indent, available_refs)?;
        }
        TypeInner::Func(_)
        | TypeInner::Service(_)
        | TypeInner::Reserved
        | TypeInner::Unknown
        | TypeInner::Future
        | TypeInner::Empty => {
            push_unsupported_schema_expr(out, env, ty)?;
        }
        TypeInner::Class(_, inner) => {
            push_schema_expr_plain(out, env, inner, indent, available_refs)?;
        }
        TypeInner::Knot(_) => {
            out.push_str("c.unsupported(\"unknown\")");
        }
    }

    Ok(())
}

fn push_wrapped_schema_expr(
    out: &mut String,
    wrapper: &str,
    env: &TypeEnv,
    inner: &Type,
    syntax: Option<&IDLType>,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    out.push_str(wrapper);
    out.push('(');
    push_schema_expr(out, env, inner, syntax, indent, available_refs)?;
    out.push(')');
    Ok(())
}

fn push_record_schema_expr(
    out: &mut String,
    env: &TypeEnv,
    fields: &[Field],
    syntax_fields: Option<&[syntax::TypeField]>,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    if is_tuple_fields(fields) {
        return push_tuple_schema_expr(out, env, fields, syntax_fields, indent, available_refs);
    }

    let child_indent = format!("{indent}  ");
    out.push_str("c.record({\n");
    for field in fields {
        let syntax_field = find_syntax_field(syntax_fields, &field.id);
        let docs = syntax_field
            .map(|field| DocBlock::parse(&field.docs))
            .unwrap_or_default();
        push_doc_comment(out, &docs, &child_indent);
        out.push_str(&child_indent);
        out.push_str(&property_key(&field.id));
        out.push_str(": ");
        push_schema_expr(
            out,
            env,
            &field.ty,
            syntax_field.map(|field| &field.typ),
            &child_indent,
            available_refs,
        )?;
        out.push_str(",\n");
    }
    out.push_str(indent);
    out.push_str("})");
    Ok(())
}

fn push_tuple_schema_expr(
    out: &mut String,
    env: &TypeEnv,
    fields: &[Field],
    syntax_fields: Option<&[syntax::TypeField]>,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    if fields.is_empty() {
        out.push_str("c.tuple([])");
        return Ok(());
    }

    let child_indent = format!("{indent}  ");
    out.push_str("c.tuple([\n");
    for field in fields {
        let syntax_field = find_syntax_field(syntax_fields, &field.id);
        let docs = syntax_field
            .map(|field| DocBlock::parse(&field.docs))
            .unwrap_or_default();
        push_doc_comment(out, &docs, &child_indent);
        out.push_str(&child_indent);
        push_schema_expr(
            out,
            env,
            &field.ty,
            syntax_field.map(|field| &field.typ),
            &child_indent,
            available_refs,
        )?;
        out.push_str(",\n");
    }
    out.push_str(indent);
    out.push_str("])");
    Ok(())
}

fn push_variant_schema_expr(
    out: &mut String,
    env: &TypeEnv,
    fields: &[Field],
    syntax_fields: Option<&[syntax::TypeField]>,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    let child_indent = format!("{indent}  ");
    out.push_str("c.variant({\n");
    for field in fields {
        let syntax_field = find_syntax_field(syntax_fields, &field.id);
        let docs = syntax_field
            .map(|field| DocBlock::parse(&field.docs))
            .unwrap_or_default();
        push_doc_comment(out, &docs, &child_indent);
        out.push_str(&child_indent);
        out.push_str(&property_key(&field.id));
        out.push_str(": ");
        push_schema_expr(
            out,
            env,
            &field.ty,
            syntax_field.map(|field| &field.typ),
            &child_indent,
            available_refs,
        )?;
        out.push_str(",\n");
    }
    out.push_str(indent);
    out.push_str("})");
    Ok(())
}

fn push_service_schema_expr(
    out: &mut String,
    env: &TypeEnv,
    methods: &[(String, Type)],
    syntax: Option<&IDLType>,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    let child_indent = format!("{indent}  ");
    out.push_str("c.service({\n");

    let syntax_methods = service_syntax_methods(syntax);
    for (method, func_ty) in methods {
        let syntax_method =
            syntax_methods.and_then(|methods| methods.iter().find(|m| m.id == *method));
        let docs = syntax_method
            .map(|binding| DocBlock::parse(&binding.docs))
            .unwrap_or_default();
        push_doc_comment(out, &docs, &child_indent);
        out.push_str(&child_indent);
        out.push_str(&object_key(method));
        out.push_str(": ");
        match func_ty.as_ref() {
            TypeInner::Func(func) => {
                push_method_schema_expr(out, env, func, &child_indent, available_refs)?
            }
            _ => push_unsupported_schema_expr(out, env, func_ty)?,
        }
        out.push_str(",\n");
    }

    out.push_str(indent);
    out.push_str("})");
    Ok(())
}

fn push_method_schema_expr(
    out: &mut String,
    env: &TypeEnv,
    func: &Function,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    let builder = if func.modes.iter().any(|mode| {
        matches!(
            mode,
            candid::types::FuncMode::Query | candid::types::FuncMode::CompositeQuery
        )
    }) {
        "c.query"
    } else {
        "c.update"
    };

    out.push_str(builder);
    out.push('(');
    push_schema_tuple_arg(out, env, &func.args, indent, available_refs)?;
    match func.rets.len() {
        0 => {}
        1 => {
            out.push_str(", ");
            push_schema_expr_plain(out, env, &func.rets[0], indent, available_refs)?;
        }
        _ => {
            out.push_str(", ");
            push_schema_tuple_arg(out, env, &func.rets, indent, available_refs)?;
        }
    }
    out.push(')');
    Ok(())
}

fn push_schema_tuple_arg(
    out: &mut String,
    env: &TypeEnv,
    items: &[Type],
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    out.push('[');
    for (index, item) in items.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        push_schema_expr_plain(out, env, item, indent, available_refs)?;
    }
    out.push(']');
    Ok(())
}

fn push_unsupported_schema_expr(out: &mut String, env: &TypeEnv, ty: &Type) -> Result<()> {
    out.push_str("c.unsupported");
    let app_type = unsupported_app_type(env, ty)?;
    if app_type != "unknown" {
        out.push('<');
        out.push_str(&app_type);
        out.push('>');
    }
    out.push('(');
    out.push_str(&json_string(&candid_type_text(env, ty)?));
    out.push(')');
    Ok(())
}

fn unsupported_app_type(env: &TypeEnv, ty: &Type) -> Result<String> {
    Ok(match ty.as_ref() {
        TypeInner::Empty => "never".to_string(),
        TypeInner::Func(_) => "c.CandidFuncReference".to_string(),
        TypeInner::Service(_) => "c.PrincipalLike".to_string(),
        TypeInner::Class(_, inner) => unsupported_app_type(env, inner)?,
        _ => ts_type_plain(env, ty, true)?,
    })
}

fn candid_type_text(env: &TypeEnv, ty: &Type) -> Result<String> {
    if ty.is_blob(env) {
        return Ok("blob".to_string());
    }

    Ok(match ty.as_ref() {
        TypeInner::Null => "null".to_string(),
        TypeInner::Bool => "bool".to_string(),
        TypeInner::Nat => "nat".to_string(),
        TypeInner::Int => "int".to_string(),
        TypeInner::Nat8 => "nat8".to_string(),
        TypeInner::Nat16 => "nat16".to_string(),
        TypeInner::Nat32 => "nat32".to_string(),
        TypeInner::Nat64 => "nat64".to_string(),
        TypeInner::Int8 => "int8".to_string(),
        TypeInner::Int16 => "int16".to_string(),
        TypeInner::Int32 => "int32".to_string(),
        TypeInner::Int64 => "int64".to_string(),
        TypeInner::Float32 => "float32".to_string(),
        TypeInner::Float64 => "float64".to_string(),
        TypeInner::Text => "text".to_string(),
        TypeInner::Principal => "principal".to_string(),
        TypeInner::Reserved | TypeInner::Unknown | TypeInner::Future => "reserved".to_string(),
        TypeInner::Empty => "empty".to_string(),
        TypeInner::Var(id) => id.clone(),
        TypeInner::Opt(inner) => format!("opt {}", candid_type_text(env, inner)?),
        TypeInner::Vec(inner) => format!("vec {}", candid_type_text(env, inner)?),
        TypeInner::Record(fields) => format!(
            "record {{ {} }}",
            fields
                .iter()
                .map(|field| candid_field_text(env, field, false))
                .collect::<Result<Vec<_>>>()?
                .join("; ")
        ),
        TypeInner::Variant(fields) => format!(
            "variant {{ {} }}",
            fields
                .iter()
                .map(|field| candid_field_text(env, field, true))
                .collect::<Result<Vec<_>>>()?
                .join("; ")
        ),
        TypeInner::Func(func) => format!(
            "func ({}) -> ({}){}",
            func.args
                .iter()
                .map(|arg| candid_type_text(env, arg))
                .collect::<Result<Vec<_>>>()?
                .join(", "),
            func.rets
                .iter()
                .map(|ret| candid_type_text(env, ret))
                .collect::<Result<Vec<_>>>()?
                .join(", "),
            func_mode_suffix(func)
        ),
        TypeInner::Service(methods) => format!(
            "service {{ {} }}",
            methods
                .iter()
                .map(|(name, ty)| {
                    let func = env.as_func(ty)?;
                    Ok(format!(
                        "{} : ({}) -> ({}){}",
                        candid_label(name),
                        func.args
                            .iter()
                            .map(|arg| candid_type_text(env, arg))
                            .collect::<Result<Vec<_>>>()?
                            .join(", "),
                        func.rets
                            .iter()
                            .map(|ret| candid_type_text(env, ret))
                            .collect::<Result<Vec<_>>>()?
                            .join(", "),
                        func_mode_suffix(func)
                    ))
                })
                .collect::<Result<Vec<_>>>()?
                .join("; ")
        ),
        TypeInner::Class(_, inner) => candid_type_text(env, inner)?,
        TypeInner::Knot(id) => id.to_string(),
    })
}

fn candid_field_text(env: &TypeEnv, field: &Field, variant: bool) -> Result<String> {
    let label = candid_shared_label(&field.id);
    if variant && matches!(field.ty.as_ref(), TypeInner::Null) {
        return Ok(label);
    }
    Ok(format!("{} : {}", label, candid_type_text(env, &field.ty)?))
}

fn candid_shared_label(label: &SharedLabel) -> String {
    match label.as_ref() {
        Label::Named(name) => candid_label(name),
        Label::Id(id) | Label::Unnamed(id) => id.to_string(),
    }
}

fn candid_label(name: &str) -> String {
    if is_identifier(name) {
        name.to_string()
    } else {
        json_string(name)
    }
}

fn func_mode_suffix(func: &Function) -> &'static str {
    if func
        .modes
        .iter()
        .any(|mode| matches!(mode, candid::types::FuncMode::Oneway))
    {
        " oneway"
    } else if func
        .modes
        .iter()
        .any(|mode| matches!(mode, candid::types::FuncMode::CompositeQuery))
    {
        " composite_query"
    } else if func
        .modes
        .iter()
        .any(|mode| matches!(mode, candid::types::FuncMode::Query))
    {
        " query"
    } else {
        ""
    }
}

fn push_service_type_body(
    out: &mut String,
    env: &TypeEnv,
    methods: &[(String, Type)],
    syntax: Option<&IDLType>,
) -> Result<()> {
    out.push_str("{\n");

    let syntax_methods = service_syntax_methods(syntax);
    for (method, func_ty) in methods {
        let syntax_method =
            syntax_methods.and_then(|methods| methods.iter().find(|m| m.id == *method));
        let docs = syntax_method
            .map(|binding| DocBlock::parse(&binding.docs))
            .unwrap_or_default();
        push_doc_comment(out, &docs, "  ");
        out.push_str("  ");
        out.push_str(&object_key(method));
        out.push_str(": ");

        match func_ty.as_ref() {
            TypeInner::Func(func) => out.push_str(&actor_method_type(env, func)?),
            TypeInner::Var(id) => out.push_str(&type_name(id)),
            _ => out.push_str("never"),
        }

        out.push_str(";\n");
    }

    out.push('}');
    Ok(())
}

fn ts_type(
    env: &TypeEnv,
    ty: &Type,
    syntax: Option<&IDLType>,
    inline_service_as_ref: bool,
) -> Result<String> {
    Ok(match (ty.as_ref(), syntax) {
        (TypeInner::Record(fields), Some(IDLType::RecordT(syntax_fields))) => {
            record_type(env, fields, Some(syntax_fields), inline_service_as_ref)?
        }
        (TypeInner::Variant(fields), Some(IDLType::VariantT(syntax_fields))) => {
            variant_type(env, fields, Some(syntax_fields), inline_service_as_ref)?
        }
        (TypeInner::Opt(inner), Some(IDLType::OptT(syntax_inner))) => {
            format!(
                "[] | [{}]",
                ts_type(env, inner, Some(syntax_inner), inline_service_as_ref)?
            )
        }
        (TypeInner::Vec(inner), Some(IDLType::VecT(syntax_inner))) => {
            vec_type(env, inner, Some(syntax_inner), inline_service_as_ref)?
        }
        (TypeInner::Service(methods), Some(IDLType::ServT(_))) if !inline_service_as_ref => {
            let mut body = String::new();
            push_service_type_body(&mut body, env, methods, syntax)?;
            body
        }
        _ => ts_type_plain(env, ty, inline_service_as_ref)?,
    })
}

fn ts_type_plain(env: &TypeEnv, ty: &Type, inline_service_as_ref: bool) -> Result<String> {
    Ok(match ty.as_ref() {
        TypeInner::Null => "null".to_string(),
        TypeInner::Bool => "boolean".to_string(),
        TypeInner::Nat | TypeInner::Int | TypeInner::Nat64 | TypeInner::Int64 => {
            "bigint".to_string()
        }
        TypeInner::Nat8
        | TypeInner::Nat16
        | TypeInner::Nat32
        | TypeInner::Int8
        | TypeInner::Int16
        | TypeInner::Int32
        | TypeInner::Float32
        | TypeInner::Float64 => "number".to_string(),
        TypeInner::Text => "string".to_string(),
        TypeInner::Reserved | TypeInner::Unknown | TypeInner::Future => "unknown".to_string(),
        TypeInner::Empty => "never".to_string(),
        TypeInner::Principal => "Principal".to_string(),
        TypeInner::Var(id) => {
            let resolved = env.rec_find_type(id)?;
            if inline_service_as_ref && matches!(resolved.as_ref(), TypeInner::Service(_)) {
                "Principal".to_string()
            } else if matches!(resolved.as_ref(), TypeInner::Func(_)) {
                "c.CandidFuncReference".to_string()
            } else {
                type_name(id)
            }
        }
        TypeInner::Opt(inner) => {
            format!(
                "[] | [{}]",
                ts_type_plain(env, inner, inline_service_as_ref)?
            )
        }
        TypeInner::Vec(inner) => vec_type(env, inner, None, inline_service_as_ref)?,
        TypeInner::Record(fields) => record_type(env, fields, None, inline_service_as_ref)?,
        TypeInner::Variant(fields) => variant_type(env, fields, None, inline_service_as_ref)?,
        TypeInner::Func(_) => "c.CandidFuncReference".to_string(),
        TypeInner::Service(methods) => {
            if inline_service_as_ref {
                "Principal".to_string()
            } else {
                let mut body = String::new();
                push_service_type_body(&mut body, env, methods, None)?;
                body
            }
        }
        TypeInner::Class(_, inner) => ts_type_plain(env, inner, inline_service_as_ref)?,
        TypeInner::Knot(_) => "unknown".to_string(),
    })
}

fn record_type(
    env: &TypeEnv,
    fields: &[Field],
    syntax_fields: Option<&[syntax::TypeField]>,
    inline_service_as_ref: bool,
) -> Result<String> {
    if is_tuple_fields(fields) {
        return tuple_type_from_fields(env, fields, syntax_fields, inline_service_as_ref);
    }

    let mut out = String::from("{ ");
    for (index, field) in fields.iter().enumerate() {
        if index > 0 {
            out.push_str("; ");
        }
        let syntax_field = find_syntax_field(syntax_fields, &field.id);
        out.push_str(&property_key(&field.id));
        out.push_str(": ");
        out.push_str(&ts_type(
            env,
            &field.ty,
            syntax_field.map(|field| &field.typ),
            inline_service_as_ref,
        )?);
    }
    out.push_str(" }");
    Ok(out)
}

fn tuple_type_from_fields(
    env: &TypeEnv,
    fields: &[Field],
    syntax_fields: Option<&[syntax::TypeField]>,
    inline_service_as_ref: bool,
) -> Result<String> {
    let mut parts = Vec::with_capacity(fields.len());
    for field in fields {
        let syntax_field = find_syntax_field(syntax_fields, &field.id);
        parts.push(ts_type(
            env,
            &field.ty,
            syntax_field.map(|field| &field.typ),
            inline_service_as_ref,
        )?);
    }
    Ok(format!("[{}]", parts.join(", ")))
}

fn variant_type(
    env: &TypeEnv,
    fields: &[Field],
    syntax_fields: Option<&[syntax::TypeField]>,
    inline_service_as_ref: bool,
) -> Result<String> {
    if fields.is_empty() {
        return Ok("never".to_string());
    }

    let mut arms = Vec::with_capacity(fields.len());
    for field in fields {
        let syntax_field = find_syntax_field(syntax_fields, &field.id);
        arms.push(format!(
            "{{ {}: {} }}",
            property_key(&field.id),
            ts_type(
                env,
                &field.ty,
                syntax_field.map(|field| &field.typ),
                inline_service_as_ref,
            )?
        ));
    }

    Ok(arms.join(" | "))
}

fn vec_type(
    env: &TypeEnv,
    inner: &Type,
    syntax: Option<&IDLType>,
    inline_service_as_ref: bool,
) -> Result<String> {
    let traced = trace_var(env, inner);
    Ok(match traced.map(Type::as_ref) {
        Some(TypeInner::Nat8) => "Uint8Array | number[]".to_string(),
        Some(TypeInner::Nat16) => "Uint16Array | number[]".to_string(),
        Some(TypeInner::Nat32) => "Uint32Array | number[]".to_string(),
        Some(TypeInner::Nat64) => "BigUint64Array | bigint[]".to_string(),
        Some(TypeInner::Int8) => "Int8Array | number[]".to_string(),
        Some(TypeInner::Int16) => "Int16Array | number[]".to_string(),
        Some(TypeInner::Int32) => "Int32Array | number[]".to_string(),
        Some(TypeInner::Int64) => "BigInt64Array | bigint[]".to_string(),
        _ => format!(
            "Array<{}>",
            ts_type(env, inner, syntax, inline_service_as_ref)?
        ),
    })
}

fn actor_method_type(env: &TypeEnv, func: &Function) -> Result<String> {
    let args = func
        .args
        .iter()
        .map(|arg| ts_type_plain(env, arg, true))
        .collect::<Result<Vec<_>>>()?;
    let ret = return_type(env, &func.rets)?;
    Ok(format!(
        "c.CandidActorMethod<[{}], {}>",
        args.join(", "),
        ret
    ))
}

fn return_type(env: &TypeEnv, rets: &[Type]) -> Result<String> {
    Ok(match rets.len() {
        0 => "undefined".to_string(),
        1 => ts_type_plain(env, &rets[0], true)?,
        _ => {
            let items = rets
                .iter()
                .map(|ty| ts_type_plain(env, ty, true))
                .collect::<Result<Vec<_>>>()?;
            format!("[{}]", items.join(", "))
        }
    })
}

fn push_doc_comment(out: &mut String, docs: &DocBlock, indent: &str) {
    if docs.is_empty() {
        return;
    }

    out.push_str(indent);
    out.push_str("/**\n");
    for line in &docs.lines {
        out.push_str(indent);
        out.push_str(" *");
        if !line.is_empty() {
            out.push(' ');
            out.push_str(&line.replace("*/", "*\\/"));
        }
        out.push('\n');
    }
    out.push_str(indent);
    out.push_str(" */\n");
}

fn trace_var<'a>(env: &'a TypeEnv, ty: &'a Type) -> Option<&'a Type> {
    match ty.as_ref() {
        TypeInner::Var(id) => env.rec_find_type(id).ok(),
        _ => Some(ty),
    }
}

fn service_syntax_methods(syntax: Option<&IDLType>) -> Option<&[Binding]> {
    match syntax {
        Some(IDLType::ServT(methods)) => Some(methods),
        _ => None,
    }
}

fn find_syntax_field<'a>(
    fields: Option<&'a [syntax::TypeField]>,
    label: &SharedLabel,
) -> Option<&'a syntax::TypeField> {
    fields?.iter().find(|field| field.label == **label)
}

fn class_inner_syntax(syntax: Option<&IDLType>) -> Option<&IDLType> {
    match syntax {
        Some(IDLType::ClassT(_, inner)) => Some(inner),
        _ => syntax,
    }
}

fn is_tuple_fields(fields: &[Field]) -> bool {
    !fields.is_empty()
        && fields
            .iter()
            .enumerate()
            .all(|(index, field)| field.id.get_id() == index as u32)
}

fn property_key(label: &SharedLabel) -> String {
    match label.as_ref() {
        Label::Named(name) => object_key(name),
        Label::Id(id) | Label::Unnamed(id) => format!("_{}_", id),
    }
}

fn object_key(name: &str) -> String {
    if is_identifier(name) && !TS_KEYWORDS.contains(&name) {
        name.to_string()
    } else {
        json_string(name)
    }
}

fn type_name(name: &str) -> String {
    sanitize_identifier(name, true)
}

fn canister_export_name(name: &str) -> String {
    let mut out = String::new();
    let mut previous_was_separator = false;

    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '$' {
            if out.is_empty() && ch.is_ascii_digit() {
                out.push_str("canister_");
            }
            out.push(ch);
            previous_was_separator = false;
        } else if !out.is_empty() && !previous_was_separator {
            out.push('_');
            previous_was_separator = true;
        }
    }

    while out.ends_with('_') {
        out.pop();
    }

    if out.is_empty() {
        out.push_str("canister");
    }

    if TS_KEYWORDS.contains(&out.as_str()) {
        out.push('_');
    }

    out
}

fn sanitize_identifier(name: &str, pascal: bool) -> String {
    let mut out = String::new();
    let mut capitalize_next = pascal;

    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '$' {
            if out.is_empty() && ch.is_ascii_digit() {
                out.push('_');
            }
            if capitalize_next {
                out.push(ch.to_ascii_uppercase());
                capitalize_next = false;
            } else {
                out.push(ch);
            }
        } else {
            capitalize_next = true;
        }
    }

    if out.is_empty() {
        out.push('_');
    }

    if TS_KEYWORDS.contains(&out.as_str()) {
        out.push('_');
    }

    out
}

fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first.is_ascii_alphabetic() || first == '_' || first == '$')
        && chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_' || ch == '$')
}

fn json_string(value: &str) -> String {
    serde_json::to_string(value).expect("serializing a string cannot fail")
}

#[cfg(test)]
mod tests {
    use crate::{generate_typescript_from_source, GeneratorConfig};

    #[test]
    fn generates_types_with_docs() {
        let source = r#"
// @strict
type User = record {
  // @format email Invalid email
  email : text;
  // @minimum 0
  age : nat8;
  // @elementMinLength 2
  aliases : vec text;
};
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("export const User = c.record({"));
        assert!(ts.contains("export type User = c.Infer<typeof User>;"));
        assert!(ts.contains("import { c } from \"cod\";"));
        assert!(ts.contains("@format email Invalid email"));
        assert!(ts.contains("email: c.text(),"));
        assert!(ts.contains("age: c.nat8(),"));
        assert!(ts.contains("aliases: c.vec(c.text()),"));
        assert!(!ts.contains("export const candidSource = "));
        assert!(!ts.contains("export function createCandidProgram"));
    }

    #[test]
    fn preserves_custom_jsdoc_format_comments() {
        let source = r#"
type Contact = record {
  // @format phone-number Must be a valid phone number.
  phone : text;
};
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("@format phone-number Must be a valid phone number."));
        assert!(ts.contains("phone: c.text(),"));
    }

    #[test]
    fn preserves_element_doc_comments() {
        let source = r#"
type Contacts = record {
  // @elementFormat email
  // @elementPattern ^admin
  emails : vec text;
};
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("@elementFormat email"));
        assert!(ts.contains("@elementPattern ^admin"));
        assert!(ts.contains("emails: c.vec(c.text()),"));
    }

    #[test]
    fn covers_variants_options_vectors_services_and_actor() {
        let source = r#"
type Result = variant { ok : text; err : text };
type Profile = opt record { name : text; tags : vec text };
service : {
  // Returns a result.
  get : (principal, Profile) -> (Result) query;
}
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("export const Result = c.variant({"));
        assert!(ts.contains("ok: c.text(),"));
        assert!(ts.contains("export type Result = c.Infer<typeof Result>;"));
        assert!(ts.contains("export const Profile = c.opt(c.record({"));
        assert!(ts.contains("tags: c.vec(c.text()),"));
        assert!(ts.contains("export const canister = c.service({"));
        assert!(ts.contains("\"get\": c.query([c.principal(), Profile], Result),"));
        assert!(!ts.contains("export type _SERVICE"));
        assert!(!ts.contains("export const methodNames = {"));
        assert!(!ts.contains("createCandidProgram"));
    }

    #[test]
    fn uses_configured_canister_name_for_actor_service_export() {
        let source = r#"
service : {
  greet : (text) -> (text) query;
}
"#;
        let config = GeneratorConfig {
            canister_name: "hello-world".to_string(),
            ..GeneratorConfig::default()
        };

        let ts = generate_typescript_from_source(source, &config).unwrap();

        assert!(ts.contains("export const hello_world = c.service({"));
        assert!(ts.contains("greet: c.query([c.text()], c.text()),"));
        assert!(!ts.contains("export const service = "));
        assert!(!ts.contains("export type _SERVICE"));
    }

    #[test]
    fn emits_tuple_record_types() {
        let source = "type Pair = record { text; nat64 };";
        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("export const Pair = c.tuple(["));
        assert!(ts.contains("c.text(),"));
        assert!(ts.contains("c.nat64(),"));
        assert!(ts.contains("export type Pair = c.Infer<typeof Pair>;"));
    }

    #[test]
    fn covers_candid_primitive_surface() {
        let source = r#"
type Callback = func (text) -> (nat) query;
type All = record {
  n : nat;
  n8 : nat8;
  n16 : nat16;
  n32 : nat32;
  n64 : nat64;
  i : int;
  i8 : int8;
  i16 : int16;
  i32 : int32;
  i64 : int64;
  f32 : float32;
  f64 : float64;
  b : bool;
  t : text;
  z : null;
  p : principal;
  r : reserved;
  e : empty;
  cb : Callback;
  bytes : vec nat8;
};
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("export const Callback = c.unsupported<c.CandidFuncReference>(\"func (text) -> (nat) query\");"));
        assert!(ts.contains("n: c.nat(),"));
        assert!(ts.contains("n8: c.nat8(),"));
        assert!(ts.contains("n64: c.nat64(),"));
        assert!(ts.contains("i: c.int(),"));
        assert!(ts.contains("i64: c.int64(),"));
        assert!(ts.contains("f32: c.float32(),"));
        assert!(ts.contains("b: c.bool(),"));
        assert!(ts.contains("t: c.text(),"));
        assert!(ts.contains("z: c.null(),"));
        assert!(ts.contains("p: c.principal(),"));
        assert!(ts.contains("r: c.unsupported(\"reserved\"),"));
        assert!(ts.contains("e: c.unsupported<never>(\"empty\"),"));
        assert!(ts.contains("cb: c.lazy(() => Callback, \"Callback\"),"));
        assert!(ts.contains("bytes: c.blob(),"));
    }
}
