use std::collections::BTreeSet;

use anyhow::Result;

use crate::config::GeneratorConfig;
use crate::docs::DocBlock;
use crate::{
    CandidArgIr, CandidFieldIr, CandidFieldLabelIr, CandidMethodIr, CandidMethodModeIr,
    CandidTypeDeclIr, CandidTypeIr, ProgramIr,
};

const TS_KEYWORDS: &[&str] = &[
    "abstract",
    "any",
    "as",
    "asserts",
    "async",
    "await",
    "bigint",
    "boolean",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "constructor",
    "continue",
    "debugger",
    "declare",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "from",
    "function",
    "get",
    "if",
    "implements",
    "import",
    "in",
    "infer",
    "instanceof",
    "interface",
    "is",
    "keyof",
    "let",
    "module",
    "namespace",
    "never",
    "new",
    "null",
    "number",
    "object",
    "package",
    "private",
    "protected",
    "public",
    "readonly",
    "require",
    "return",
    "satisfies",
    "set",
    "static",
    "string",
    "super",
    "switch",
    "symbol",
    "this",
    "throw",
    "true",
    "try",
    "type",
    "typeof",
    "undefined",
    "unique",
    "unknown",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

/// The TypeScript emitter formats ProgramIr. It must not structurally interpret
/// Candid frontend or type-checker representations.
#[derive(Debug, Clone)]
pub struct TypeScriptEmitter {
    config: GeneratorConfig,
}

impl TypeScriptEmitter {
    pub fn new(config: &GeneratorConfig) -> Self {
        Self {
            config: config.clone(),
        }
    }

    pub fn emit(&self, program: &ProgramIr) -> Result<String> {
        let mut out = String::new();

        if self.config.emit_banner {
            out.push_str("// Generated by cod. Do not edit by hand.\n");
        }
        out.push_str("import { c } from \"cod\";\n\n");

        let mut emitted_types = BTreeSet::new();
        for declaration in &program.types {
            self.push_named_schema(&mut out, declaration, &emitted_types)?;
            emitted_types.insert(declaration.name.clone());
            out.push('\n');
        }

        self.push_actor_schema(&mut out, program, &emitted_types)?;
        if !emitted_types.is_empty() {
            out.push('\n');
        }

        Ok(out.trim_end().to_string() + "\n")
    }

    fn push_named_schema(
        &self,
        out: &mut String,
        declaration: &CandidTypeDeclIr,
        available_refs: &BTreeSet<String>,
    ) -> Result<()> {
        push_doc_comment(out, &doc_block(&declaration.raw_docs), "");

        let name = type_name(&declaration.name);
        match &declaration.typ {
            CandidTypeIr::Service { methods } => {
                out.push_str("export const ");
                out.push_str(&name);
                out.push_str(" = ");
                push_service_schema_expr(out, methods, "", available_refs)?;
                out.push_str(";\n");
                out.push_str("export type ");
                out.push_str(&name);
                out.push_str(" = c.ActorFor<typeof ");
                out.push_str(&name);
                out.push_str(".methods>;\n");
            }
            typ => {
                out.push_str("export const ");
                out.push_str(&name);
                out.push_str(" = ");
                push_schema_expr(out, typ, "", available_refs)?;
                out.push_str(";\n");
                out.push_str("export type ");
                out.push_str(&name);
                out.push_str(" = c.Infer<typeof ");
                out.push_str(&name);
                out.push_str(">;\n");
            }
        }

        Ok(())
    }

    fn push_actor_schema(
        &self,
        out: &mut String,
        program: &ProgramIr,
        available_refs: &BTreeSet<String>,
    ) -> Result<()> {
        if program.actor.init_args.is_empty() && program.actor.service.methods.is_empty() {
            return Ok(());
        }

        if !program.actor.init_args.is_empty() {
            out.push_str("export const initArgs = c.tuple(");
            push_schema_tuple_arg(out, &program.actor.init_args, "", available_refs)?;
            out.push_str(");\n");
            out.push_str("export type InitArgs = c.Infer<typeof initArgs>;\n\n");
        }

        out.push_str("export const ");
        out.push_str(&canister_export_name(&self.config.canister_name));
        out.push_str(" = ");
        push_service_schema_expr(out, &program.actor.service.methods, "", available_refs)?;
        out.push_str(";\n");
        Ok(())
    }
}

pub fn generate_typescript(program: &ProgramIr, config: &GeneratorConfig) -> Result<String> {
    TypeScriptEmitter::new(config).emit(program)
}

fn push_schema_expr(
    out: &mut String,
    typ: &CandidTypeIr,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    match typ {
        CandidTypeIr::Null => out.push_str("c.null()"),
        CandidTypeIr::Bool => out.push_str("c.bool()"),
        CandidTypeIr::Nat => out.push_str("c.nat()"),
        CandidTypeIr::Int => out.push_str("c.int()"),
        CandidTypeIr::Nat8 => out.push_str("c.nat8()"),
        CandidTypeIr::Nat16 => out.push_str("c.nat16()"),
        CandidTypeIr::Nat32 => out.push_str("c.nat32()"),
        CandidTypeIr::Nat64 => out.push_str("c.nat64()"),
        CandidTypeIr::Int8 => out.push_str("c.int8()"),
        CandidTypeIr::Int16 => out.push_str("c.int16()"),
        CandidTypeIr::Int32 => out.push_str("c.int32()"),
        CandidTypeIr::Int64 => out.push_str("c.int64()"),
        CandidTypeIr::Float32 => out.push_str("c.float32()"),
        CandidTypeIr::Float64 => out.push_str("c.float64()"),
        CandidTypeIr::Text => out.push_str("c.text()"),
        CandidTypeIr::Principal => out.push_str("c.principal()"),
        CandidTypeIr::Blob => out.push_str("c.blob()"),
        CandidTypeIr::Ref { name } => {
            if available_refs.contains(name) {
                out.push_str(&type_name(name));
            } else {
                out.push_str("c.lazy(() => ");
                out.push_str(&type_name(name));
                out.push_str(", ");
                out.push_str(&json_string(name));
                out.push(')');
            }
        }
        CandidTypeIr::Opt { inner } => {
            push_wrapped_schema_expr(out, "c.opt", inner, indent, available_refs)?;
        }
        CandidTypeIr::Vec { inner } => {
            push_wrapped_schema_expr(out, "c.vec", inner, indent, available_refs)?;
        }
        CandidTypeIr::Record { fields } => {
            push_record_schema_expr(out, fields, indent, available_refs)?;
        }
        CandidTypeIr::Variant { fields } => {
            push_variant_schema_expr(out, fields, indent, available_refs)?;
        }
        CandidTypeIr::Reserved
        | CandidTypeIr::Empty
        | CandidTypeIr::Func { .. }
        | CandidTypeIr::Service { .. } => {
            push_unsupported_schema_expr(out, typ)?;
        }
    }

    Ok(())
}

fn push_wrapped_schema_expr(
    out: &mut String,
    wrapper: &str,
    inner: &CandidTypeIr,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    out.push_str(wrapper);
    out.push('(');
    push_schema_expr(out, inner, indent, available_refs)?;
    out.push(')');
    Ok(())
}

fn push_record_schema_expr(
    out: &mut String,
    fields: &[CandidFieldIr],
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    if is_tuple_fields(fields) {
        return push_tuple_schema_expr(out, fields, indent, available_refs);
    }

    let child_indent = format!("{indent}  ");
    out.push_str("c.record({\n");
    for field in fields {
        push_doc_comment(out, &doc_block(&field.raw_docs), &child_indent);
        out.push_str(&child_indent);
        out.push_str(&property_key(field));
        out.push_str(": ");
        push_schema_expr(out, &field.typ, &child_indent, available_refs)?;
        out.push_str(",\n");
    }
    out.push_str(indent);
    out.push_str("})");
    Ok(())
}

fn push_tuple_schema_expr(
    out: &mut String,
    fields: &[CandidFieldIr],
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    if fields.is_empty() {
        out.push_str("c.tuple([])");
        return Ok(());
    }

    let child_indent = format!("{indent}  ");
    out.push_str("c.tuple([\n");
    for field in fields {
        push_doc_comment(out, &doc_block(&field.raw_docs), &child_indent);
        out.push_str(&child_indent);
        push_schema_expr(out, &field.typ, &child_indent, available_refs)?;
        out.push_str(",\n");
    }
    out.push_str(indent);
    out.push_str("])");
    Ok(())
}

fn push_variant_schema_expr(
    out: &mut String,
    fields: &[CandidFieldIr],
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    let child_indent = format!("{indent}  ");
    out.push_str("c.variant({\n");
    for field in fields {
        push_doc_comment(out, &doc_block(&field.raw_docs), &child_indent);
        out.push_str(&child_indent);
        out.push_str(&property_key(field));
        out.push_str(": ");
        push_schema_expr(out, &field.typ, &child_indent, available_refs)?;
        out.push_str(",\n");
    }
    out.push_str(indent);
    out.push_str("})");
    Ok(())
}

fn push_service_schema_expr(
    out: &mut String,
    methods: &[CandidMethodIr],
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    let child_indent = format!("{indent}  ");
    out.push_str("c.service({\n");

    for method in methods {
        push_doc_comment(out, &doc_block(&method.raw_docs), &child_indent);
        out.push_str(&child_indent);
        out.push_str(&object_key(&method.name));
        out.push_str(": ");
        push_method_schema_expr(out, method, &child_indent, available_refs)?;
        out.push_str(",\n");
    }

    out.push_str(indent);
    out.push_str("})");
    Ok(())
}

fn push_method_schema_expr(
    out: &mut String,
    method: &CandidMethodIr,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    out.push_str(method_builder(method.mode));
    out.push('(');
    push_schema_tuple_arg(out, &method.args, indent, available_refs)?;
    match method.returns.len() {
        0 => {}
        1 => {
            out.push_str(", ");
            push_schema_expr(out, &method.returns[0].typ, indent, available_refs)?;
        }
        _ => {
            out.push_str(", ");
            push_schema_tuple_arg(out, &method.returns, indent, available_refs)?;
        }
    }
    out.push(')');
    Ok(())
}

fn push_schema_tuple_arg(
    out: &mut String,
    items: &[CandidArgIr],
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    out.push('[');
    for (index, item) in items.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        push_schema_expr(out, &item.typ, indent, available_refs)?;
    }
    out.push(']');
    Ok(())
}

fn method_builder(mode: CandidMethodModeIr) -> &'static str {
    match mode {
        CandidMethodModeIr::Query => "c.query",
        CandidMethodModeIr::CompositeQuery => "c.compositeQuery",
        CandidMethodModeIr::Update => "c.update",
        CandidMethodModeIr::Oneway => "c.oneway",
    }
}

fn push_unsupported_schema_expr(out: &mut String, typ: &CandidTypeIr) -> Result<()> {
    out.push_str("c.unsupported");
    let app_type = unsupported_app_type(typ)?;
    if app_type != "unknown" {
        out.push('<');
        out.push_str(&app_type);
        out.push('>');
    }
    out.push('(');
    out.push_str(&json_string(&candid_type_text(typ)?));
    out.push(')');
    Ok(())
}

fn unsupported_app_type(typ: &CandidTypeIr) -> Result<String> {
    Ok(match typ {
        CandidTypeIr::Empty => "never".to_string(),
        CandidTypeIr::Func { .. } => "c.CandidFuncReference".to_string(),
        CandidTypeIr::Service { .. } => "c.PrincipalLike".to_string(),
        _ => ts_type(typ, true)?,
    })
}

fn candid_type_text(typ: &CandidTypeIr) -> Result<String> {
    Ok(match typ {
        CandidTypeIr::Null => "null".to_string(),
        CandidTypeIr::Bool => "bool".to_string(),
        CandidTypeIr::Nat => "nat".to_string(),
        CandidTypeIr::Int => "int".to_string(),
        CandidTypeIr::Nat8 => "nat8".to_string(),
        CandidTypeIr::Nat16 => "nat16".to_string(),
        CandidTypeIr::Nat32 => "nat32".to_string(),
        CandidTypeIr::Nat64 => "nat64".to_string(),
        CandidTypeIr::Int8 => "int8".to_string(),
        CandidTypeIr::Int16 => "int16".to_string(),
        CandidTypeIr::Int32 => "int32".to_string(),
        CandidTypeIr::Int64 => "int64".to_string(),
        CandidTypeIr::Float32 => "float32".to_string(),
        CandidTypeIr::Float64 => "float64".to_string(),
        CandidTypeIr::Text => "text".to_string(),
        CandidTypeIr::Principal => "principal".to_string(),
        CandidTypeIr::Blob => "blob".to_string(),
        CandidTypeIr::Reserved => "reserved".to_string(),
        CandidTypeIr::Empty => "empty".to_string(),
        CandidTypeIr::Ref { name } => name.clone(),
        CandidTypeIr::Opt { inner } => format!("opt {}", candid_type_text(inner)?),
        CandidTypeIr::Vec { inner } => format!("vec {}", candid_type_text(inner)?),
        CandidTypeIr::Record { fields } => format!(
            "record {{ {} }}",
            fields
                .iter()
                .map(|field| candid_field_text(field, false))
                .collect::<Result<Vec<_>>>()?
                .join("; ")
        ),
        CandidTypeIr::Variant { fields } => format!(
            "variant {{ {} }}",
            fields
                .iter()
                .map(|field| candid_field_text(field, true))
                .collect::<Result<Vec<_>>>()?
                .join("; ")
        ),
        CandidTypeIr::Func {
            args,
            returns,
            mode,
        } => format!(
            "func ({}) -> ({}){}",
            args.iter()
                .map(|arg| candid_type_text(&arg.typ))
                .collect::<Result<Vec<_>>>()?
                .join(", "),
            returns
                .iter()
                .map(|ret| candid_type_text(&ret.typ))
                .collect::<Result<Vec<_>>>()?
                .join(", "),
            method_mode_suffix(*mode)
        ),
        CandidTypeIr::Service { methods } => format!(
            "service {{ {} }}",
            methods
                .iter()
                .map(|method| {
                    Ok(format!(
                        "{} : ({}) -> ({}){}",
                        candid_label(&method.name),
                        method
                            .args
                            .iter()
                            .map(|arg| candid_type_text(&arg.typ))
                            .collect::<Result<Vec<_>>>()?
                            .join(", "),
                        method
                            .returns
                            .iter()
                            .map(|ret| candid_type_text(&ret.typ))
                            .collect::<Result<Vec<_>>>()?
                            .join(", "),
                        method_mode_suffix(method.mode)
                    ))
                })
                .collect::<Result<Vec<_>>>()?
                .join("; ")
        ),
    })
}

fn candid_field_text(field: &CandidFieldIr, variant: bool) -> Result<String> {
    let label = candid_field_label(&field.label);
    if variant && matches!(field.typ, CandidTypeIr::Null) {
        return Ok(label);
    }
    Ok(format!("{} : {}", label, candid_type_text(&field.typ)?))
}

fn candid_field_label(label: &CandidFieldLabelIr) -> String {
    match label {
        CandidFieldLabelIr::Named { name } => candid_label(name),
        CandidFieldLabelIr::Id { id } | CandidFieldLabelIr::Unnamed { id } => id.to_string(),
    }
}

fn candid_label(name: &str) -> String {
    if is_identifier(name) {
        name.to_string()
    } else {
        json_string(name)
    }
}

fn method_mode_suffix(mode: CandidMethodModeIr) -> &'static str {
    match mode {
        CandidMethodModeIr::Query => " query",
        CandidMethodModeIr::CompositeQuery => " composite_query",
        CandidMethodModeIr::Update => "",
        CandidMethodModeIr::Oneway => " oneway",
    }
}

fn push_service_type_body(out: &mut String, methods: &[CandidMethodIr]) -> Result<()> {
    out.push_str("{\n");

    for method in methods {
        push_doc_comment(out, &doc_block(&method.raw_docs), "  ");
        out.push_str("  ");
        out.push_str(&object_key(&method.name));
        out.push_str(": ");
        out.push_str(&actor_method_type(method)?);
        out.push_str(";\n");
    }

    out.push('}');
    Ok(())
}

fn ts_type(typ: &CandidTypeIr, inline_service_as_ref: bool) -> Result<String> {
    Ok(match typ {
        CandidTypeIr::Null => "null".to_string(),
        CandidTypeIr::Bool => "boolean".to_string(),
        CandidTypeIr::Nat | CandidTypeIr::Int | CandidTypeIr::Nat64 | CandidTypeIr::Int64 => {
            "bigint".to_string()
        }
        CandidTypeIr::Nat8
        | CandidTypeIr::Nat16
        | CandidTypeIr::Nat32
        | CandidTypeIr::Int8
        | CandidTypeIr::Int16
        | CandidTypeIr::Int32
        | CandidTypeIr::Float32
        | CandidTypeIr::Float64 => "number".to_string(),
        CandidTypeIr::Text => "string".to_string(),
        CandidTypeIr::Reserved => "unknown".to_string(),
        CandidTypeIr::Empty => "never".to_string(),
        CandidTypeIr::Principal => "Principal".to_string(),
        CandidTypeIr::Blob => "Uint8Array | number[]".to_string(),
        CandidTypeIr::Ref { name } => type_name(name),
        CandidTypeIr::Opt { inner } => format!("[] | [{}]", ts_type(inner, inline_service_as_ref)?),
        CandidTypeIr::Vec { inner } => vec_type(inner, inline_service_as_ref)?,
        CandidTypeIr::Record { fields } => record_type(fields, inline_service_as_ref)?,
        CandidTypeIr::Variant { fields } => variant_type(fields, inline_service_as_ref)?,
        CandidTypeIr::Func { .. } => "c.CandidFuncReference".to_string(),
        CandidTypeIr::Service { methods } => {
            if inline_service_as_ref {
                "Principal".to_string()
            } else {
                let mut body = String::new();
                push_service_type_body(&mut body, methods)?;
                body
            }
        }
    })
}

fn record_type(fields: &[CandidFieldIr], inline_service_as_ref: bool) -> Result<String> {
    if is_tuple_fields(fields) {
        return tuple_type_from_fields(fields, inline_service_as_ref);
    }

    let mut out = String::from("{ ");
    for (index, field) in fields.iter().enumerate() {
        if index > 0 {
            out.push_str("; ");
        }
        out.push_str(&property_key(field));
        out.push_str(": ");
        out.push_str(&ts_type(&field.typ, inline_service_as_ref)?);
    }
    out.push_str(" }");
    Ok(out)
}

fn tuple_type_from_fields(fields: &[CandidFieldIr], inline_service_as_ref: bool) -> Result<String> {
    let mut parts = Vec::with_capacity(fields.len());
    for field in fields {
        parts.push(ts_type(&field.typ, inline_service_as_ref)?);
    }
    Ok(format!("[{}]", parts.join(", ")))
}

fn variant_type(fields: &[CandidFieldIr], inline_service_as_ref: bool) -> Result<String> {
    if fields.is_empty() {
        return Ok("never".to_string());
    }

    let mut arms = Vec::with_capacity(fields.len());
    for field in fields {
        arms.push(format!(
            "{{ {}: {} }}",
            property_key(field),
            ts_type(&field.typ, inline_service_as_ref)?
        ));
    }

    Ok(arms.join(" | "))
}

fn vec_type(inner: &CandidTypeIr, inline_service_as_ref: bool) -> Result<String> {
    Ok(match inner {
        CandidTypeIr::Nat8 => "Uint8Array | number[]".to_string(),
        CandidTypeIr::Nat16 => "Uint16Array | number[]".to_string(),
        CandidTypeIr::Nat32 => "Uint32Array | number[]".to_string(),
        CandidTypeIr::Nat64 => "BigUint64Array | bigint[]".to_string(),
        CandidTypeIr::Int8 => "Int8Array | number[]".to_string(),
        CandidTypeIr::Int16 => "Int16Array | number[]".to_string(),
        CandidTypeIr::Int32 => "Int32Array | number[]".to_string(),
        CandidTypeIr::Int64 => "BigInt64Array | bigint[]".to_string(),
        _ => format!("Array<{}>", ts_type(inner, inline_service_as_ref)?),
    })
}

fn actor_method_type(method: &CandidMethodIr) -> Result<String> {
    let args = method
        .args
        .iter()
        .map(|arg| ts_type(&arg.typ, true))
        .collect::<Result<Vec<_>>>()?;
    let ret = return_type(&method.returns)?;
    Ok(format!(
        "c.CandidActorMethod<[{}], {}>",
        args.join(", "),
        ret
    ))
}

fn return_type(rets: &[CandidArgIr]) -> Result<String> {
    Ok(match rets.len() {
        0 => "undefined".to_string(),
        1 => ts_type(&rets[0].typ, true)?,
        _ => {
            let items = rets
                .iter()
                .map(|arg| ts_type(&arg.typ, true))
                .collect::<Result<Vec<_>>>()?;
            format!("[{}]", items.join(", "))
        }
    })
}

fn push_doc_comment(out: &mut String, docs: &DocBlock, indent: &str) {
    if docs.is_empty() {
        return;
    }

    out.push_str(indent);
    out.push_str("/**\n");
    for line in &docs.lines {
        out.push_str(indent);
        out.push_str(" *");
        if !line.is_empty() {
            out.push(' ');
            out.push_str(&line.replace("*/", "*\\/"));
        }
        out.push('\n');
    }
    out.push_str(indent);
    out.push_str(" */\n");
}

fn doc_block(raw_docs: &[String]) -> DocBlock {
    DocBlock::parse(raw_docs)
}

fn is_tuple_fields(fields: &[CandidFieldIr]) -> bool {
    !fields.is_empty()
        && fields
            .iter()
            .enumerate()
            .all(|(index, field)| matches!(field.label, CandidFieldLabelIr::Unnamed { id } if id == index as u32))
}

fn property_key(field: &CandidFieldIr) -> String {
    match &field.label {
        CandidFieldLabelIr::Named { name } => object_key(name),
        CandidFieldLabelIr::Id { id } | CandidFieldLabelIr::Unnamed { id } => format!("_{}_", id),
    }
}

fn object_key(name: &str) -> String {
    if is_identifier(name) && !TS_KEYWORDS.contains(&name) {
        name.to_string()
    } else {
        json_string(name)
    }
}

fn type_name(name: &str) -> String {
    sanitize_identifier(name, true)
}

fn canister_export_name(name: &str) -> String {
    let mut out = String::new();
    let mut previous_was_separator = false;

    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '$' {
            if out.is_empty() && ch.is_ascii_digit() {
                out.push_str("canister_");
            }
            out.push(ch);
            previous_was_separator = false;
        } else if !out.is_empty() && !previous_was_separator {
            out.push('_');
            previous_was_separator = true;
        }
    }

    while out.ends_with('_') {
        out.pop();
    }

    if out.is_empty() {
        out.push_str("canister");
    }

    if TS_KEYWORDS.contains(&out.as_str()) {
        out.push('_');
    }

    out
}

fn sanitize_identifier(name: &str, pascal: bool) -> String {
    let mut out = String::new();
    let mut capitalize_next = pascal;

    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '$' {
            if out.is_empty() && ch.is_ascii_digit() {
                out.push('_');
            }
            if capitalize_next {
                out.push(ch.to_ascii_uppercase());
                capitalize_next = false;
            } else {
                out.push(ch);
            }
        } else {
            capitalize_next = true;
        }
    }

    if out.is_empty() {
        out.push('_');
    }

    if TS_KEYWORDS.contains(&out.as_str()) {
        out.push('_');
    }

    out
}

fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first.is_ascii_alphabetic() || first == '_' || first == '$')
        && chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_' || ch == '$')
}

fn json_string(value: &str) -> String {
    serde_json::to_string(value).expect("serializing a string cannot fail")
}

#[cfg(test)]
mod tests {
    use crate::{generate_typescript_from_source, GeneratorConfig};

    #[test]
    fn generates_types_with_docs() {
        let source = r#"
// @strict
type User = record {
  // @format email Invalid email
  email : text;
  // @minimum 0
  age : nat8;
  // @elementMinLength 2
  aliases : vec text;
};
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("export const User = c.record({"));
        assert!(ts.contains("export type User = c.Infer<typeof User>;"));
        assert!(ts.contains("import { c } from \"cod\";"));
        assert!(ts.contains("@format email Invalid email"));
        assert!(ts.contains("email: c.text(),"));
        assert!(ts.contains("age: c.nat8(),"));
        assert!(ts.contains("aliases: c.vec(c.text()),"));
        assert!(!ts.contains("export const candidSource = "));
        assert!(!ts.contains("export function createCandidProgram"));
    }

    #[test]
    fn preserves_custom_jsdoc_format_comments() {
        let source = r#"
type Contact = record {
  // @format phone-number Must be a valid phone number.
  phone : text;
};
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("@format phone-number Must be a valid phone number."));
        assert!(ts.contains("phone: c.text(),"));
    }

    #[test]
    fn preserves_element_doc_comments() {
        let source = r#"
type Contacts = record {
  // @elementFormat email
  // @elementPattern ^admin
  emails : vec text;
};
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("@elementFormat email"));
        assert!(ts.contains("@elementPattern ^admin"));
        assert!(ts.contains("emails: c.vec(c.text()),"));
    }

    #[test]
    fn covers_variants_options_vectors_services_and_actor() {
        let source = r#"
type Result = variant { ok : text; err : text };
type Profile = opt record { name : text; tags : vec text };
service : {
  // Returns a result.
  get : (principal, Profile) -> (Result) query;
}
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("export const Result = c.variant({"));
        assert!(ts.contains("ok: c.text(),"));
        assert!(ts.contains("export type Result = c.Infer<typeof Result>;"));
        assert!(ts.contains("export const Profile = c.opt(c.record({"));
        assert!(ts.contains("tags: c.vec(c.text()),"));
        assert!(ts.contains("export const canister = c.service({"));
        assert!(ts.contains("\"get\": c.query([c.principal(), Profile], Result),"));
        assert!(!ts.contains("export type _SERVICE"));
        assert!(!ts.contains("export const methodNames = {"));
        assert!(!ts.contains("createCandidProgram"));
    }

    #[test]
    fn uses_configured_canister_name_for_actor_service_export() {
        let source = r#"
service : {
  greet : (text) -> (text) query;
}
"#;
        let config = GeneratorConfig {
            canister_name: "hello-world".to_string(),
            ..GeneratorConfig::default()
        };

        let ts = generate_typescript_from_source(source, &config).unwrap();

        assert!(ts.contains("export const hello_world = c.service({"));
        assert!(ts.contains("greet: c.query([c.text()], c.text()),"));
        assert!(!ts.contains("export const service = "));
        assert!(!ts.contains("export type _SERVICE"));
    }

    #[test]
    fn emits_tuple_record_types() {
        let source = "type Pair = record { text; nat64 };";
        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("export const Pair = c.tuple(["));
        assert!(ts.contains("c.text(),"));
        assert!(ts.contains("c.nat64(),"));
        assert!(ts.contains("export type Pair = c.Infer<typeof Pair>;"));
    }

    #[test]
    fn covers_candid_primitive_surface() {
        let source = r#"
type Callback = func (text) -> (nat) query;
type All = record {
  n : nat;
  n8 : nat8;
  n16 : nat16;
  n32 : nat32;
  n64 : nat64;
  i : int;
  i8 : int8;
  i16 : int16;
  i32 : int32;
  i64 : int64;
  f32 : float32;
  f64 : float64;
  b : bool;
  t : text;
  z : null;
  p : principal;
  r : reserved;
  e : empty;
  cb : Callback;
  bytes : vec nat8;
};
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("export const Callback = c.unsupported<c.CandidFuncReference>(\"func (text) -> (nat) query\");"));
        assert!(ts.contains("n: c.nat(),"));
        assert!(ts.contains("n8: c.nat8(),"));
        assert!(ts.contains("n64: c.nat64(),"));
        assert!(ts.contains("i: c.int(),"));
        assert!(ts.contains("i64: c.int64(),"));
        assert!(ts.contains("f32: c.float32(),"));
        assert!(ts.contains("b: c.bool(),"));
        assert!(ts.contains("t: c.text(),"));
        assert!(ts.contains("z: c.null(),"));
        assert!(ts.contains("p: c.principal(),"));
        assert!(ts.contains("r: c.unsupported(\"reserved\"),"));
        assert!(ts.contains("e: c.unsupported<never>(\"empty\"),"));
        assert!(ts.contains("cb: c.lazy(() => Callback, \"Callback\"),"));
        assert!(ts.contains("bytes: c.blob(),"));
    }

    #[test]
    fn emitter_does_not_import_candid_frontend_types() {
        let source = include_str!("generator.rs");
        let forbidden = [
            concat!("candid", "::"),
            concat!("candid_parser", "::"),
            concat!("Type", "Env"),
            concat!("Type", "Inner"),
            concat!("IDL", "Type"),
            concat!("IDL", "MergedProg"),
        ];

        for token in forbidden {
            assert!(
                !source.contains(token),
                "TypeScript emitter must not structurally inspect {token}"
            );
        }
    }
}
