use std::collections::BTreeSet;

use anyhow::{Context, Result};

use crate::config::GeneratorConfig;
use crate::docs::DocBlock;
use crate::{
    ArgIr, FieldIr, FieldLabelIr, MethodId, MethodIr, MethodModeIr, ProgramIr, ProgramIrGraph,
    ProgramSemantics, TypeDeclIr, TypeId, TypeKindIr, TypeRefIr, TypeSemanticIr,
};

const DEFAULT_MODULE_SPECIFIER: &str = "@ic-reactor/cod";

const TS_KEYWORDS: &[&str] = &[
    "abstract",
    "any",
    "as",
    "asserts",
    "async",
    "await",
    "bigint",
    "boolean",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "constructor",
    "continue",
    "debugger",
    "declare",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "from",
    "function",
    "get",
    "if",
    "implements",
    "import",
    "in",
    "infer",
    "instanceof",
    "interface",
    "is",
    "keyof",
    "let",
    "module",
    "namespace",
    "never",
    "new",
    "null",
    "number",
    "object",
    "package",
    "private",
    "protected",
    "public",
    "readonly",
    "require",
    "return",
    "satisfies",
    "set",
    "static",
    "string",
    "super",
    "switch",
    "symbol",
    "this",
    "throw",
    "true",
    "try",
    "type",
    "typeof",
    "undefined",
    "unique",
    "unknown",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

/// The TypeScript emitter formats ProgramIr. It must not structurally interpret
/// Candid frontend or type-checker representations.
#[derive(Debug, Clone)]
pub struct TypeScriptEmitter {
    config: GeneratorConfig,
}

impl TypeScriptEmitter {
    pub fn new(config: &GeneratorConfig) -> Self {
        Self {
            config: config.clone(),
        }
    }

    pub fn emit(&self, program: &ProgramIr) -> Result<String> {
        let graph = program.graph().context("invalid ProgramIR graph")?;
        let semantics = program.semantics().context("invalid ProgramIR semantics")?;
        let mut out = String::new();

        if self.config.emit_banner {
            out.push_str("// Generated by cod. Do not edit by hand.\n");
        }
        out.push_str("import { c } from ");
        out.push_str(&json_string(DEFAULT_MODULE_SPECIFIER));
        out.push_str(";\n\n");

        let mut emitted_types = BTreeSet::new();
        for declaration in graph.declarations() {
            self.push_named_schema(&mut out, &graph, &semantics, declaration, &emitted_types)?;
            emitted_types.insert(declaration.name.clone());
            out.push('\n');
        }

        self.push_actor_schema(&mut out, &graph, &semantics, &emitted_types)?;
        if !emitted_types.is_empty() {
            out.push('\n');
        }

        Ok(out.trim_end().to_string() + "\n")
    }

    fn push_named_schema(
        &self,
        out: &mut String,
        graph: &ProgramIrGraph<'_>,
        semantics: &ProgramSemantics,
        declaration: &TypeDeclIr,
        available_refs: &BTreeSet<String>,
    ) -> Result<()> {
        push_doc_comment(out, &doc_block(&declaration.metadata.raw_docs), "");

        let name = type_name(&declaration.name);
        match graph.type_kind(declaration.typ)? {
            TypeKindIr::Service { methods } => {
                out.push_str("export const ");
                out.push_str(&name);
                out.push_str(" = ");
                push_service_schema_expr(out, graph, semantics, methods, "", available_refs)?;
                out.push_str(";\n");
                out.push_str("export type ");
                out.push_str(&name);
                out.push_str(" = c.ActorFor<typeof ");
                out.push_str(&name);
                out.push_str(".methods>;\n");
            }
            _ => {
                out.push_str("export const ");
                out.push_str(&name);
                out.push_str(" = ");
                push_type_id_schema_expr(
                    out,
                    graph,
                    semantics,
                    declaration.typ,
                    "",
                    available_refs,
                )?;
                out.push_str(";\n");
                out.push_str("export type ");
                out.push_str(&name);
                out.push_str(" = c.Infer<typeof ");
                out.push_str(&name);
                out.push_str(">;\n");
            }
        }

        Ok(())
    }

    fn push_actor_schema(
        &self,
        out: &mut String,
        graph: &ProgramIrGraph<'_>,
        semantics: &ProgramSemantics,
        available_refs: &BTreeSet<String>,
    ) -> Result<()> {
        let Some(actor) = graph.actor() else {
            return Ok(());
        };

        if !actor.init_args.is_empty() {
            out.push_str("export const initArgs = c.tuple(");
            push_arg_tuple_schema_expr(
                out,
                graph,
                semantics,
                &actor.init_args,
                "",
                available_refs,
            )?;
            out.push_str(");\n");
            out.push_str("export type InitArgs = c.Infer<typeof initArgs>;\n\n");
        }

        out.push_str("export const ");
        out.push_str(&canister_export_name(&self.config.canister_name));
        out.push_str(" = ");
        let methods = graph.service_method_ids(actor.service)?;
        push_service_schema_expr(out, graph, semantics, methods, "", available_refs)?;
        out.push_str(";\n");
        Ok(())
    }
}

pub fn generate_typescript(program: &ProgramIr, config: &GeneratorConfig) -> Result<String> {
    TypeScriptEmitter::new(config).emit(program)
}

fn push_type_ref_schema_expr(
    out: &mut String,
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    reference: TypeRefIr,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    match reference {
        TypeRefIr::Type { id } => {
            push_type_id_schema_expr(out, graph, semantics, id, indent, available_refs)?
        }
        TypeRefIr::Decl { id } => {
            let declaration = graph.declaration(id)?;
            push_declaration_schema_ref(out, &declaration.name, available_refs);
        }
    }

    Ok(())
}

fn push_type_id_schema_expr(
    out: &mut String,
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    id: TypeId,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    match graph.type_kind(id)? {
        TypeKindIr::Null => out.push_str("c.null()"),
        TypeKindIr::Bool => out.push_str("c.bool()"),
        TypeKindIr::Nat => out.push_str("c.nat()"),
        TypeKindIr::Int => out.push_str("c.int()"),
        TypeKindIr::Nat8 => out.push_str("c.nat8()"),
        TypeKindIr::Nat16 => out.push_str("c.nat16()"),
        TypeKindIr::Nat32 => out.push_str("c.nat32()"),
        TypeKindIr::Nat64 => out.push_str("c.nat64()"),
        TypeKindIr::Int8 => out.push_str("c.int8()"),
        TypeKindIr::Int16 => out.push_str("c.int16()"),
        TypeKindIr::Int32 => out.push_str("c.int32()"),
        TypeKindIr::Int64 => out.push_str("c.int64()"),
        TypeKindIr::Float32 => out.push_str("c.float32()"),
        TypeKindIr::Float64 => out.push_str("c.float64()"),
        TypeKindIr::Text => out.push_str("c.text()"),
        TypeKindIr::Principal => out.push_str("c.principal()"),
        TypeKindIr::Opt { inner } => {
            push_wrapped_schema_expr(
                out,
                graph,
                semantics,
                "c.opt",
                *inner,
                indent,
                available_refs,
            )?;
        }
        TypeKindIr::Vec { inner } => {
            push_wrapped_schema_expr(
                out,
                graph,
                semantics,
                "c.vec",
                *inner,
                indent,
                available_refs,
            )?;
        }
        TypeKindIr::Record { fields } => {
            if matches!(semantics.semantic(id)?, Some(TypeSemanticIr::Tuple)) {
                push_tuple_schema_expr(out, graph, semantics, fields, indent, available_refs)?;
            } else {
                push_record_schema_expr(out, graph, semantics, fields, indent, available_refs)?;
            }
        }
        TypeKindIr::Variant { fields } => {
            push_variant_schema_expr(out, graph, semantics, fields, indent, available_refs)?;
        }
        TypeKindIr::Reserved
        | TypeKindIr::Empty
        | TypeKindIr::Func { .. }
        | TypeKindIr::Service { .. } => {
            push_unsupported_schema_expr(out, graph, semantics, id)?;
        }
    }

    Ok(())
}

fn push_declaration_schema_ref(out: &mut String, name: &str, available_refs: &BTreeSet<String>) {
    if available_refs.contains(name) {
        out.push_str(&type_name(name));
    } else {
        out.push_str("c.lazy(() => ");
        out.push_str(&type_name(name));
        out.push_str(", ");
        out.push_str(&json_string(name));
        out.push(')');
    }
}

fn push_wrapped_schema_expr(
    out: &mut String,
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    wrapper: &str,
    inner: TypeRefIr,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    out.push_str(wrapper);
    out.push('(');
    push_type_ref_schema_expr(out, graph, semantics, inner, indent, available_refs)?;
    out.push(')');
    Ok(())
}

fn push_record_schema_expr(
    out: &mut String,
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    fields: &[FieldIr],
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    let child_indent = format!("{indent}  ");
    out.push_str("c.record({\n");
    for field in fields {
        push_doc_comment(out, &doc_block(&field.metadata.raw_docs), &child_indent);
        out.push_str(&child_indent);
        out.push_str(&property_key(field));
        out.push_str(": ");
        push_type_ref_schema_expr(
            out,
            graph,
            semantics,
            field.typ,
            &child_indent,
            available_refs,
        )?;
        out.push_str(",\n");
    }
    out.push_str(indent);
    out.push_str("})");
    Ok(())
}

fn push_tuple_schema_expr(
    out: &mut String,
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    fields: &[FieldIr],
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    if fields.is_empty() {
        out.push_str("c.tuple([])");
        return Ok(());
    }

    let child_indent = format!("{indent}  ");
    out.push_str("c.tuple([\n");
    for field in fields {
        push_doc_comment(out, &doc_block(&field.metadata.raw_docs), &child_indent);
        out.push_str(&child_indent);
        push_type_ref_schema_expr(
            out,
            graph,
            semantics,
            field.typ,
            &child_indent,
            available_refs,
        )?;
        out.push_str(",\n");
    }
    out.push_str(indent);
    out.push_str("])");
    Ok(())
}

fn push_variant_schema_expr(
    out: &mut String,
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    fields: &[FieldIr],
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    let child_indent = format!("{indent}  ");
    out.push_str("c.variant({\n");
    for field in fields {
        push_doc_comment(out, &doc_block(&field.metadata.raw_docs), &child_indent);
        out.push_str(&child_indent);
        out.push_str(&property_key(field));
        out.push_str(": ");
        push_type_ref_schema_expr(
            out,
            graph,
            semantics,
            field.typ,
            &child_indent,
            available_refs,
        )?;
        out.push_str(",\n");
    }
    out.push_str(indent);
    out.push_str("})");
    Ok(())
}

fn push_service_schema_expr(
    out: &mut String,
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    methods: &[MethodId],
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    let child_indent = format!("{indent}  ");
    out.push_str("c.service({\n");

    for method_id in methods {
        let method = graph.method(*method_id)?;
        push_doc_comment(out, &doc_block(&method.metadata.raw_docs), &child_indent);
        out.push_str(&child_indent);
        out.push_str(&object_key(&method.name));
        out.push_str(": ");
        push_method_schema_expr(out, graph, semantics, method, &child_indent, available_refs)?;
        out.push_str(",\n");
    }

    out.push_str(indent);
    out.push_str("})");
    Ok(())
}

fn push_method_schema_expr(
    out: &mut String,
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    method: &MethodIr,
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    out.push_str(method_builder(method.mode));
    out.push('(');
    push_arg_tuple_schema_expr(out, graph, semantics, &method.args, indent, available_refs)?;
    if matches!(method.mode, MethodModeIr::Oneway) {
        out.push(')');
        return Ok(());
    }
    match method.returns.len() {
        0 => {}
        1 => {
            out.push_str(", ");
            push_type_ref_schema_expr(
                out,
                graph,
                semantics,
                method.returns[0].typ,
                indent,
                available_refs,
            )?;
        }
        _ => {
            out.push_str(", ");
            push_arg_tuple_schema_expr(
                out,
                graph,
                semantics,
                &method.returns,
                indent,
                available_refs,
            )?;
        }
    }
    out.push(')');
    Ok(())
}

fn push_arg_tuple_schema_expr(
    out: &mut String,
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    items: &[ArgIr],
    indent: &str,
    available_refs: &BTreeSet<String>,
) -> Result<()> {
    out.push('[');
    for (index, item) in items.iter().enumerate() {
        if index > 0 {
            out.push_str(", ");
        }
        push_type_ref_schema_expr(out, graph, semantics, item.typ, indent, available_refs)?;
    }
    out.push(']');
    Ok(())
}

fn method_builder(mode: MethodModeIr) -> &'static str {
    match mode {
        MethodModeIr::Query => "c.query",
        MethodModeIr::CompositeQuery => "c.compositeQuery",
        MethodModeIr::Update => "c.update",
        MethodModeIr::Oneway => "c.oneway",
    }
}

fn push_unsupported_schema_expr(
    out: &mut String,
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    id: TypeId,
) -> Result<()> {
    out.push_str("c.unsupported");
    let app_type = unsupported_app_type(graph, semantics, id)?;
    if app_type != "unknown" {
        out.push('<');
        out.push_str(&app_type);
        out.push('>');
    }
    out.push('(');
    out.push_str(&json_string(&candid_type_text_id(graph, id)?));
    out.push(')');
    Ok(())
}

fn unsupported_app_type(
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    id: TypeId,
) -> Result<String> {
    Ok(match graph.type_kind(id)? {
        TypeKindIr::Empty => "never".to_string(),
        TypeKindIr::Func { .. } => "c.CandidFuncReference".to_string(),
        TypeKindIr::Service { .. } => "c.PrincipalLike".to_string(),
        _ => type_id_ts_type(graph, semantics, id, true)?,
    })
}

fn candid_type_text_ref(graph: &ProgramIrGraph<'_>, reference: TypeRefIr) -> Result<String> {
    match reference {
        TypeRefIr::Type { id } => candid_type_text_id(graph, id),
        TypeRefIr::Decl { id } => Ok(graph.declaration(id)?.name.clone()),
    }
}

fn candid_type_text_id(graph: &ProgramIrGraph<'_>, id: TypeId) -> Result<String> {
    Ok(match graph.type_kind(id)? {
        TypeKindIr::Null => "null".to_string(),
        TypeKindIr::Bool => "bool".to_string(),
        TypeKindIr::Nat => "nat".to_string(),
        TypeKindIr::Int => "int".to_string(),
        TypeKindIr::Nat8 => "nat8".to_string(),
        TypeKindIr::Nat16 => "nat16".to_string(),
        TypeKindIr::Nat32 => "nat32".to_string(),
        TypeKindIr::Nat64 => "nat64".to_string(),
        TypeKindIr::Int8 => "int8".to_string(),
        TypeKindIr::Int16 => "int16".to_string(),
        TypeKindIr::Int32 => "int32".to_string(),
        TypeKindIr::Int64 => "int64".to_string(),
        TypeKindIr::Float32 => "float32".to_string(),
        TypeKindIr::Float64 => "float64".to_string(),
        TypeKindIr::Text => "text".to_string(),
        TypeKindIr::Principal => "principal".to_string(),
        TypeKindIr::Reserved => "reserved".to_string(),
        TypeKindIr::Empty => "empty".to_string(),
        TypeKindIr::Opt { inner } => format!("opt {}", candid_type_text_ref(graph, *inner)?),
        TypeKindIr::Vec { inner } => format!("vec {}", candid_type_text_ref(graph, *inner)?),
        TypeKindIr::Record { fields } => format!(
            "record {{ {} }}",
            fields
                .iter()
                .map(|field| candid_field_text(graph, field, false))
                .collect::<Result<Vec<_>>>()?
                .join("; ")
        ),
        TypeKindIr::Variant { fields } => format!(
            "variant {{ {} }}",
            fields
                .iter()
                .map(|field| candid_field_text(graph, field, true))
                .collect::<Result<Vec<_>>>()?
                .join("; ")
        ),
        TypeKindIr::Func {
            args,
            returns,
            mode,
        } => format!(
            "func ({}) -> ({}){}",
            args.iter()
                .map(|arg| candid_type_text_ref(graph, arg.typ))
                .collect::<Result<Vec<_>>>()?
                .join(", "),
            returns
                .iter()
                .map(|ret| candid_type_text_ref(graph, ret.typ))
                .collect::<Result<Vec<_>>>()?
                .join(", "),
            method_mode_suffix(*mode)
        ),
        TypeKindIr::Service { methods } => format!(
            "service {{ {} }}",
            methods
                .iter()
                .map(|method_id| {
                    let method = graph.method(*method_id)?;
                    Ok(format!(
                        "{} : ({}) -> ({}){}",
                        candid_label(&method.name),
                        method
                            .args
                            .iter()
                            .map(|arg| candid_type_text_ref(graph, arg.typ))
                            .collect::<Result<Vec<_>>>()?
                            .join(", "),
                        method
                            .returns
                            .iter()
                            .map(|ret| candid_type_text_ref(graph, ret.typ))
                            .collect::<Result<Vec<_>>>()?
                            .join(", "),
                        method_mode_suffix(method.mode)
                    ))
                })
                .collect::<Result<Vec<_>>>()?
                .join("; ")
        ),
    })
}

fn candid_field_text(graph: &ProgramIrGraph<'_>, field: &FieldIr, variant: bool) -> Result<String> {
    let label = candid_field_label(&field.label);
    if variant && type_ref_is_direct_null(graph, field.typ)? {
        return Ok(label);
    }
    Ok(format!(
        "{} : {}",
        label,
        candid_type_text_ref(graph, field.typ)?
    ))
}

fn type_ref_is_direct_null(graph: &ProgramIrGraph<'_>, reference: TypeRefIr) -> Result<bool> {
    match reference {
        TypeRefIr::Type { id } => Ok(matches!(graph.type_kind(id)?, TypeKindIr::Null)),
        TypeRefIr::Decl { .. } => Ok(false),
    }
}

fn candid_field_label(label: &FieldLabelIr) -> String {
    match label {
        FieldLabelIr::Named { name } => candid_label(name),
        FieldLabelIr::Id { candid_id } | FieldLabelIr::Unnamed { candid_id } => {
            candid_id.to_string()
        }
    }
}

fn candid_label(name: &str) -> String {
    if is_identifier(name) {
        name.to_string()
    } else {
        json_string(name)
    }
}

fn method_mode_suffix(mode: MethodModeIr) -> &'static str {
    match mode {
        MethodModeIr::Query => " query",
        MethodModeIr::CompositeQuery => " composite_query",
        MethodModeIr::Update => "",
        MethodModeIr::Oneway => " oneway",
    }
}

fn push_service_type_body(
    out: &mut String,
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    methods: &[MethodId],
) -> Result<()> {
    out.push_str("{\n");

    for method_id in methods {
        let method = graph.method(*method_id)?;
        push_doc_comment(out, &doc_block(&method.metadata.raw_docs), "  ");
        out.push_str("  ");
        out.push_str(&object_key(&method.name));
        out.push_str(": ");
        out.push_str(&actor_method_type(graph, semantics, method)?);
        out.push_str(";\n");
    }

    out.push('}');
    Ok(())
}

fn type_ref_ts_type(
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    reference: TypeRefIr,
    inline_service_as_ref: bool,
) -> Result<String> {
    match reference {
        TypeRefIr::Type { id } => type_id_ts_type(graph, semantics, id, inline_service_as_ref),
        TypeRefIr::Decl { id } => Ok(type_name(&graph.declaration(id)?.name)),
    }
}

fn type_id_ts_type(
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    id: TypeId,
    inline_service_as_ref: bool,
) -> Result<String> {
    Ok(match graph.type_kind(id)? {
        TypeKindIr::Null => "null".to_string(),
        TypeKindIr::Bool => "boolean".to_string(),
        TypeKindIr::Nat | TypeKindIr::Int | TypeKindIr::Nat64 | TypeKindIr::Int64 => {
            "bigint".to_string()
        }
        TypeKindIr::Nat8
        | TypeKindIr::Nat16
        | TypeKindIr::Nat32
        | TypeKindIr::Int8
        | TypeKindIr::Int16
        | TypeKindIr::Int32
        | TypeKindIr::Float32
        | TypeKindIr::Float64 => "number".to_string(),
        TypeKindIr::Text => "string".to_string(),
        TypeKindIr::Reserved => "unknown".to_string(),
        TypeKindIr::Empty => "never".to_string(),
        TypeKindIr::Principal => "Principal".to_string(),
        TypeKindIr::Opt { inner } => {
            format!(
                "[] | [{}]",
                type_ref_ts_type(graph, semantics, *inner, inline_service_as_ref)?
            )
        }
        TypeKindIr::Vec { inner } => vec_type(graph, semantics, *inner, inline_service_as_ref)?,
        TypeKindIr::Record { fields } => {
            record_type(graph, semantics, id, fields, inline_service_as_ref)?
        }
        TypeKindIr::Variant { fields } => {
            variant_type(graph, semantics, fields, inline_service_as_ref)?
        }
        TypeKindIr::Func { .. } => "c.CandidFuncReference".to_string(),
        TypeKindIr::Service { methods } => {
            if inline_service_as_ref {
                "Principal".to_string()
            } else {
                let mut body = String::new();
                push_service_type_body(&mut body, graph, semantics, methods)?;
                body
            }
        }
    })
}

fn record_type(
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    id: TypeId,
    fields: &[FieldIr],
    inline_service_as_ref: bool,
) -> Result<String> {
    if matches!(semantics.semantic(id)?, Some(TypeSemanticIr::Tuple)) {
        return tuple_type_from_fields(graph, semantics, fields, inline_service_as_ref);
    }

    let mut out = String::from("{ ");
    for (index, field) in fields.iter().enumerate() {
        if index > 0 {
            out.push_str("; ");
        }
        out.push_str(&property_key(field));
        out.push_str(": ");
        out.push_str(&type_ref_ts_type(
            graph,
            semantics,
            field.typ,
            inline_service_as_ref,
        )?);
    }
    out.push_str(" }");
    Ok(out)
}

fn tuple_type_from_fields(
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    fields: &[FieldIr],
    inline_service_as_ref: bool,
) -> Result<String> {
    let mut parts = Vec::with_capacity(fields.len());
    for field in fields {
        parts.push(type_ref_ts_type(
            graph,
            semantics,
            field.typ,
            inline_service_as_ref,
        )?);
    }
    Ok(format!("[{}]", parts.join(", ")))
}

fn variant_type(
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    fields: &[FieldIr],
    inline_service_as_ref: bool,
) -> Result<String> {
    if fields.is_empty() {
        return Ok("never".to_string());
    }

    let mut arms = Vec::with_capacity(fields.len());
    for field in fields {
        arms.push(format!(
            "{{ {}: {} }}",
            property_key(field),
            type_ref_ts_type(graph, semantics, field.typ, inline_service_as_ref)?
        ));
    }

    Ok(arms.join(" | "))
}

fn vec_type(
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    inner: TypeRefIr,
    inline_service_as_ref: bool,
) -> Result<String> {
    if let TypeRefIr::Type { id } = inner {
        match graph.type_kind(id)? {
            TypeKindIr::Nat8 => return Ok("Uint8Array | number[]".to_string()),
            TypeKindIr::Nat16 => return Ok("Uint16Array | number[]".to_string()),
            TypeKindIr::Nat32 => return Ok("Uint32Array | number[]".to_string()),
            TypeKindIr::Nat64 => return Ok("BigUint64Array | bigint[]".to_string()),
            TypeKindIr::Int8 => return Ok("Int8Array | number[]".to_string()),
            TypeKindIr::Int16 => return Ok("Int16Array | number[]".to_string()),
            TypeKindIr::Int32 => return Ok("Int32Array | number[]".to_string()),
            TypeKindIr::Int64 => return Ok("BigInt64Array | bigint[]".to_string()),
            _ => {}
        }
    }

    Ok(format!(
        "Array<{}>",
        type_ref_ts_type(graph, semantics, inner, inline_service_as_ref)?
    ))
}

fn actor_method_type(
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    method: &MethodIr,
) -> Result<String> {
    let args = method
        .args
        .iter()
        .map(|arg| type_ref_ts_type(graph, semantics, arg.typ, true))
        .collect::<Result<Vec<_>>>()?;
    let ret = return_type(graph, semantics, &method.returns)?;
    Ok(format!(
        "c.CandidActorMethod<[{}], {}>",
        args.join(", "),
        ret
    ))
}

fn return_type(
    graph: &ProgramIrGraph<'_>,
    semantics: &ProgramSemantics,
    rets: &[ArgIr],
) -> Result<String> {
    Ok(match rets.len() {
        0 => "undefined".to_string(),
        1 => type_ref_ts_type(graph, semantics, rets[0].typ, true)?,
        _ => {
            let items = rets
                .iter()
                .map(|arg| type_ref_ts_type(graph, semantics, arg.typ, true))
                .collect::<Result<Vec<_>>>()?;
            format!("[{}]", items.join(", "))
        }
    })
}

fn push_doc_comment(out: &mut String, docs: &DocBlock, indent: &str) {
    if docs.is_empty() {
        return;
    }

    out.push_str(indent);
    out.push_str("/**\n");
    for line in &docs.lines {
        out.push_str(indent);
        out.push_str(" *");
        if !line.is_empty() {
            out.push(' ');
            out.push_str(&line.replace("*/", "*\\/"));
        }
        out.push('\n');
    }
    out.push_str(indent);
    out.push_str(" */\n");
}

fn doc_block(raw_docs: &[String]) -> DocBlock {
    DocBlock::parse(raw_docs)
}

fn property_key(field: &FieldIr) -> String {
    match &field.label {
        FieldLabelIr::Named { name } => object_key(name),
        FieldLabelIr::Id { candid_id } | FieldLabelIr::Unnamed { candid_id } => {
            format!("_{}_", candid_id)
        }
    }
}

fn object_key(name: &str) -> String {
    if is_identifier(name) && !TS_KEYWORDS.contains(&name) {
        name.to_string()
    } else {
        json_string(name)
    }
}

fn type_name(name: &str) -> String {
    sanitize_identifier(name, true)
}

fn canister_export_name(name: &str) -> String {
    let mut out = String::new();
    let mut previous_was_separator = false;

    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '$' {
            if out.is_empty() && ch.is_ascii_digit() {
                out.push_str("canister_");
            }
            out.push(ch);
            previous_was_separator = false;
        } else if !out.is_empty() && !previous_was_separator {
            out.push('_');
            previous_was_separator = true;
        }
    }

    while out.ends_with('_') {
        out.pop();
    }

    if out.is_empty() {
        out.push_str("canister");
    }

    if TS_KEYWORDS.contains(&out.as_str()) {
        out.push('_');
    }

    out
}

fn sanitize_identifier(name: &str, pascal: bool) -> String {
    let mut out = String::new();
    let mut capitalize_next = pascal;

    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' || ch == '$' {
            if out.is_empty() && ch.is_ascii_digit() {
                out.push('_');
            }
            if capitalize_next {
                out.push(ch.to_ascii_uppercase());
                capitalize_next = false;
            } else {
                out.push(ch);
            }
        } else {
            capitalize_next = true;
        }
    }

    if out.is_empty() {
        out.push('_');
    }

    if TS_KEYWORDS.contains(&out.as_str()) {
        out.push('_');
    }

    out
}

fn is_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    (first.is_ascii_alphabetic() || first == '_' || first == '$')
        && chars.all(|ch| ch.is_ascii_alphanumeric() || ch == '_' || ch == '$')
}

fn json_string(value: &str) -> String {
    serde_json::to_string(value).expect("serializing a string cannot fail")
}

#[cfg(test)]
mod tests {
    use crate::{
        generate_typescript, generate_typescript_from_source, ActorIr, ArgIr, DeclId, FieldIr,
        FieldLabelIr, GeneratorConfig, MetadataIr, MethodId, MethodIr, MethodModeIr, ProgramIr,
        TypeDeclIr, TypeId, TypeKindIr, TypeNodeIr, TypeRefIr, PROGRAM_IR_VERSION,
    };

    #[test]
    fn generates_types_with_docs() {
        let source = r#"
// @strict
type User = record {
  // @format email Invalid email
  email : text;
  // @minimum 0
  age : nat8;
  // @elementMinLength 2
  aliases : vec text;
};
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("export const User = c.record({"));
        assert!(ts.contains("export type User = c.Infer<typeof User>;"));
        assert!(ts.contains("import { c } from \"@ic-reactor/cod\";"));
        assert!(!ts.contains("import { c } from \"cod\";"));
        assert!(ts.contains("@format email Invalid email"));
        assert!(ts.contains("email: c.text(),"));
        assert!(ts.contains("age: c.nat8(),"));
        assert!(ts.contains("aliases: c.vec(c.text()),"));
        assert!(!ts.contains("export const candidSource = "));
        assert!(!ts.contains("export function createCandidProgram"));
    }

    #[test]
    fn preserves_custom_jsdoc_format_comments() {
        let source = r#"
type Contact = record {
  // @format phone-number Must be a valid phone number.
  phone : text;
};
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("@format phone-number Must be a valid phone number."));
        assert!(ts.contains("phone: c.text(),"));
    }

    #[test]
    fn preserves_element_doc_comments() {
        let source = r#"
type Contacts = record {
  // @elementFormat email
  // @elementPattern ^admin
  emails : vec text;
};
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("@elementFormat email"));
        assert!(ts.contains("@elementPattern ^admin"));
        assert!(ts.contains("emails: c.vec(c.text()),"));
    }

    #[test]
    fn covers_variants_options_vectors_services_and_actor() {
        let source = r#"
type Result = variant { ok : text; err : text };
type Profile = opt record { name : text; tags : vec text };
service : {
  // Returns a result.
  get : (principal, Profile) -> (Result) query;
}
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("export const Result = c.variant({"));
        assert!(ts.contains("ok: c.text(),"));
        assert!(ts.contains("export type Result = c.Infer<typeof Result>;"));
        assert!(ts.contains("export const Profile = c.opt(c.record({"));
        assert!(ts.contains("tags: c.vec(c.text()),"));
        assert!(ts.contains("export const canister = c.service({"));
        assert!(ts.contains("\"get\": c.query([c.principal(), Profile], Result),"));
        assert!(!ts.contains("export type _SERVICE"));
        assert!(!ts.contains("export const methodNames = {"));
        assert!(!ts.contains("createCandidProgram"));
    }

    #[test]
    fn distinguishes_absent_actor_from_empty_actor() {
        let type_only = generate_typescript_from_source(
            r#"
type User = record { name : text };
"#,
            &GeneratorConfig::default(),
        )
        .unwrap();

        assert!(type_only.contains("export const User = c.record({"));
        assert!(!type_only.contains("export const canister = c.service("));

        let empty_actor =
            generate_typescript_from_source("service : {}", &GeneratorConfig::default()).unwrap();

        assert!(empty_actor.contains("export const canister = c.service({"));
    }

    #[test]
    fn emits_oneway_without_return_schema_argument() {
        let source = r#"
service : {
  notify : (text) -> () oneway;
}
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("notify: c.oneway([c.text()]),"));
        assert!(!ts.contains("notify: c.oneway([c.text()],"));
    }

    #[test]
    fn uses_configured_canister_name_for_actor_service_export() {
        let source = r#"
service : {
  greet : (text) -> (text) query;
}
"#;
        let config = GeneratorConfig {
            canister_name: "hello-world".to_string(),
            ..GeneratorConfig::default()
        };

        let ts = generate_typescript_from_source(source, &config).unwrap();

        assert!(ts.contains("export const hello_world = c.service({"));
        assert!(ts.contains("greet: c.query([c.text()], c.text()),"));
        assert!(!ts.contains("export const service = "));
        assert!(!ts.contains("export type _SERVICE"));
    }

    #[test]
    fn emits_tuple_record_types() {
        let source = "type Pair = record { text; nat64 };";
        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("export const Pair = c.tuple(["));
        assert!(ts.contains("c.text(),"));
        assert!(ts.contains("c.nat64(),"));
        assert!(ts.contains("export type Pair = c.Infer<typeof Pair>;"));
    }

    #[test]
    fn covers_candid_primitive_surface() {
        let source = r#"
type Callback = func (text) -> (nat) query;
type All = record {
  n : nat;
  n8 : nat8;
  n16 : nat16;
  n32 : nat32;
  n64 : nat64;
  i : int;
  i8 : int8;
  i16 : int16;
  i32 : int32;
  i64 : int64;
  f32 : float32;
  f64 : float64;
  b : bool;
  t : text;
  z : null;
  p : principal;
  r : reserved;
  e : empty;
  cb : Callback;
  bytes : vec nat8;
};
"#;

        let ts = generate_typescript_from_source(source, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("export const Callback = c.unsupported<c.CandidFuncReference>(\"func (text) -> (nat) query\");"));
        assert!(ts.contains("n: c.nat(),"));
        assert!(ts.contains("n8: c.nat8(),"));
        assert!(ts.contains("n64: c.nat64(),"));
        assert!(ts.contains("i: c.int(),"));
        assert!(ts.contains("i64: c.int64(),"));
        assert!(ts.contains("f32: c.float32(),"));
        assert!(ts.contains("b: c.bool(),"));
        assert!(ts.contains("t: c.text(),"));
        assert!(ts.contains("z: c.null(),"));
        assert!(ts.contains("p: c.principal(),"));
        assert!(ts.contains("r: c.unsupported(\"reserved\"),"));
        assert!(ts.contains("e: c.unsupported<never>(\"empty\"),"));
        assert!(ts.contains("cb: Callback,"));
        assert!(!ts.contains("cb: c.lazy(() => Callback, \"Callback\"),"));
        assert!(ts.contains("bytes: c.vec(c.nat8()),"));
    }

    #[test]
    fn emits_from_canonical_program_ir_graph() {
        let program = ProgramIr {
            version: PROGRAM_IR_VERSION,
            types: vec![
                TypeNodeIr {
                    kind: TypeKindIr::Nat64,
                },
                TypeNodeIr {
                    kind: TypeKindIr::Record {
                        fields: vec![FieldIr {
                            label: FieldLabelIr::Named {
                                name: "owner".to_string(),
                            },
                            typ: TypeRefIr::Decl { id: DeclId(0) },
                            metadata: MetadataIr::default(),
                        }],
                    },
                },
                TypeNodeIr {
                    kind: TypeKindIr::Service {
                        methods: vec![MethodId(0)],
                    },
                },
            ],
            declarations: vec![
                TypeDeclIr {
                    name: "UserId".to_string(),
                    typ: TypeId(0),
                    metadata: MetadataIr::default(),
                },
                TypeDeclIr {
                    name: "Account".to_string(),
                    typ: TypeId(1),
                    metadata: MetadataIr::default(),
                },
            ],
            methods: vec![MethodIr {
                name: "save".to_string(),
                mode: MethodModeIr::Update,
                args: vec![ArgIr {
                    name: None,
                    typ: TypeRefIr::Decl { id: DeclId(1) },
                    metadata: MetadataIr::default(),
                }],
                returns: vec![ArgIr {
                    name: None,
                    typ: TypeRefIr::Decl { id: DeclId(0) },
                    metadata: MetadataIr::default(),
                }],
                metadata: MetadataIr::default(),
            }],
            actor: Some(ActorIr {
                init_args: vec![],
                service: TypeId(2),
            }),
        };

        program.validate().unwrap();
        let ts = generate_typescript(&program, &GeneratorConfig::default()).unwrap();

        assert!(ts.contains("export const UserId = c.nat64();"));
        assert!(ts.contains("export const Account = c.record({"));
        assert!(ts.contains("owner: UserId,"));
        assert!(ts.contains("save: c.update([Account], UserId),"));
    }

    #[test]
    fn emitter_uses_program_ir_without_compatibility_ast() {
        let source = include_str!("generator.rs");
        let forbidden = [
            concat!("candid", "::"),
            concat!("candid_parser", "::"),
            concat!("Type", "Env"),
            concat!("Type", "Inner"),
            concat!("IDL", "Type"),
            concat!("IDL", "MergedProg"),
            concat!("Emitter", "Program"),
            concat!("Candid", "ActorIr"),
            concat!("Candid", "ServiceIr"),
            concat!("Candid", "MethodIr"),
            concat!("Candid", "ArgIr"),
            concat!("Candid", "TypeIr"),
            concat!("Candid", "Type", "DeclIr"),
            concat!("Candid", "FieldIr"),
            concat!("Candid", "FieldLabelIr"),
            concat!("Candid", "MethodModeIr"),
        ];

        for token in forbidden {
            assert!(
                !source.contains(token),
                "TypeScript emitter must consume ProgramIR directly, not {token}"
            );
        }
    }
}
