/**
 * Codegen Pipeline
 *
 * Orchestrates all generators for a single canister.
 * This is the primary entry point used by @ic-reactor/cli and @ic-reactor/vite-plugin.
 *
 * Pipeline steps (in order):
 *  1. Resolve paths (didFile, outDir)
 *  2. Generate declarations (JS + .d.ts + .did copy)
 *  3. Optionally generate reactor implementation (`index.generated.ts`), and
 *     with `factories: true` the query and mutation factories
 *     (`index.factories.generated.ts`)
 *  4. Optionally create or migrate the user entry (`index.ts`)
 */

import fs from "node:fs"
import path from "node:path"
import { parseDid } from "@ic-reactor/parser"
import type {
  CanisterConfig,
  CodegenConfig,
  CodegenTarget,
  GeneratorResult,
  ReactorClassName,
} from "./types.js"
import {
  formatGenerated,
  generateDeclarations,
  loadPrettier,
  OWNER_FILE,
} from "./generators/declarations.js"
import {
  generateReactorEntryFile,
  generateReactorFile,
} from "./generators/reactor.js"
import {
  FACTORIES_FILE_NAME,
  generateFactoriesFile,
} from "./generators/factories.js"
import {
  assertSafeCanisterConfig,
  CodegenConfigError,
  resolveDeclarationsBaseName,
} from "./validate.js"
import { getReactorName, getServiceTypeName } from "./naming.js"
import {
  copyToNewFile,
  createFile,
  replaceFile,
  replaceFiles,
} from "./write.js"

export interface PipelineOptions {
  /** Canister name and config */
  canisterConfig: CanisterConfig
  /**
   * Absolute path to the project root.
   * Relative paths in `CanisterConfig` are resolved from here.
   */
  projectRoot: string
  /**
   * Global codegen config (for fallback outDir and clientManagerPath).
   */
  globalConfig: Pick<CodegenConfig, "outDir" | "clientManagerPath" | "target">
  /**
   * Whether the managed reactor files should be generated.
   * Defaults to true.
   */
  generateReactor?: boolean
}

function resolveReactorClass(canisterConfig: CanisterConfig): ReactorClassName {
  return canisterConfig.mode ?? "DisplayReactor"
}

function resolveRuntimeTarget(
  canisterConfig: CanisterConfig,
  globalConfig: Pick<CodegenConfig, "outDir" | "clientManagerPath" | "target">
): CodegenTarget {
  return canisterConfig.target ?? globalConfig.target ?? "react"
}

function normalizeFileContent(content: string): string {
  return content.replace(/\r\n/g, "\n").trim()
}

/** Header line every version of this generator has written into its output. */
const GENERATED_MARKER = "Auto-generated by @ic-reactor/codegen"

/**
 * The reactor's `name:` property as this generator emits it. Canister names are
 * restricted to `CANISTER_NAME_PATTERN`. The file is formatted with the
 * project's Prettier, so the indent, the quotes and the trailing comma vary.
 */
const GENERATED_CANISTER_NAME = /^\s*name:\s*["']([A-Za-z0-9_.-]+)["'],?\s*$/m

/** Every `export …` statement, one per line, as the generator writes them. */
const EXPORT_STATEMENT = /^export\b.*$/gm

/**
 * Decide whether an existing `index.ts` is still the pre-split generated
 * reactor file, which this pipeline migrates to the thin wrapper.
 *
 * The old test — the header marker plus the substring `createActorHooks(` —
 * matched any file that had *ever* been generated, including one the user has
 * since filled with their own factories and hooks. Migration would overwrite it
 * with six lines of boilerplate and report the write as an ordinary success.
 *
 * So the shape is checked, not just the header: the file must still declare the
 * reactor and hooks for *this* canister and must export nothing the old
 * generator did not write. Anything the user added — another `export const`, an
 * `export * from`, a re-export — takes the file out of scope and it is
 * preserved. Edits that add no export are still possible, which is why the
 * caller keeps a backup before writing.
 */
function isLegacyGeneratedIndexFile(
  content: string,
  canisterName: string
): boolean {
  if (!content.includes(GENERATED_MARKER)) return false

  const reactorName = getReactorName(canisterName)
  const serviceName = getServiceTypeName(canisterName)

  // The two lines that make this the generated reactor for this canister.
  if (!content.includes(`export const ${reactorName} = new `)) return false
  if (!content.includes(`= createActorHooks(${reactorName})`)) return false

  const allowed = [
    `export type ${serviceName} = _SERVICE`,
    `export const ${reactorName} = new `,
    // Opens the destructured hook block; its members are not export statements.
    "export const {",
  ]

  const statements = normalizeFileContent(content).match(EXPORT_STATEMENT) ?? []

  return statements.every((statement) =>
    allowed.some((prefix) => statement.startsWith(prefix))
  )
}

/**
 * Copy `filePath` next to itself before it is overwritten, and return the
 * backup path.
 *
 * Migration decides from the file's contents that it is safe to replace. That
 * inference can be wrong for an edit that adds no export, and the file being
 * replaced may be the only copy of work the user has not committed, so the
 * original is kept rather than deleted. An existing backup is never clobbered.
 * A dangling link at the chosen name passes the `existsSync` check, so the copy
 * itself refuses any existing entry.
 */
function backUpFile(filePath: string): string {
  let backupPath = `${filePath}.bak`
  for (let n = 2; fs.existsSync(backupPath); n += 1) {
    backupPath = `${filePath}.bak.${n}`
  }
  copyToNewFile(filePath, backupPath)
  return backupPath
}

/**
 * Read the canister name out of an existing `index.generated.ts`, if the file
 * exists and this package wrote it.
 *
 * Two canisters pointed at the same `outDir` overwrite each other's
 * `index.generated.ts` and — since the declarations directory is replaced
 * wholesale — each other's declarations too, with both runs reporting success.
 * The generated file records which canister owns the directory, so the second
 * canister can be stopped before it destroys the first one's output.
 */
function findOutDirOwner(outDir: string): string | undefined {
  // Written by generateDeclarations, so it is present for `--bindgen-only`
  // runs too — those skip index.generated.ts but still replace declarations/,
  // which is the step that destroys the other canister's output.
  try {
    const owner = fs.readFileSync(path.join(outDir, OWNER_FILE), "utf-8").trim()
    if (owner) return owner
  } catch {
    // fall through to the legacy marker
  }

  // Directories generated before the marker existed only carry the canister
  // name inside index.generated.ts.
  let content: string
  try {
    content = fs.readFileSync(path.join(outDir, "index.generated.ts"), "utf-8")
  } catch {
    return undefined
  }

  if (!content.includes(GENERATED_MARKER)) return undefined

  return GENERATED_CANISTER_NAME.exec(content)?.[1]
}

/**
 * Whether `content` is a wrapper this generator wrote: the template as it is
 * written now, or unformatted, as earlier versions wrote it.
 */
function isManagedEntryWrapper(
  content: string,
  expectedEntryContents: string[]
): boolean {
  return expectedEntryContents.some(
    (expected) =>
      normalizeFileContent(content) === normalizeFileContent(expected)
  )
}

/**
 * The methods of the service in the `.did` copy the declarations step wrote,
 * so the factories match the declarations they are typed by even when the
 * source `.did` changes during the run.
 */
function readServiceMethods(didCopyPath: string) {
  // The copy keeps the source's bytes, byte order mark included; see
  // generateDeclarations.
  const source = fs.readFileSync(didCopyPath, "utf-8").replace(/^\uFEFF/, "")
  const service = parseDid(source).service
  if (!service) {
    throw new Error(
      `${didCopyPath} declares no service, so there are no methods to generate factories for.`
    )
  }
  return service.methods
}

/**
 * Remove the factories file an earlier run wrote, once the canister no longer
 * sets `factories`.
 *
 * Nothing regenerates the file after that, so a method later removed from the
 * .did would stay in it and stop it compiling. Only a regular file carrying the
 * generator's header is removed: a link or a file of the user's own is left.
 */
function removeGeneratedFactoriesFile(filePath: string): void {
  let content: string
  try {
    if (!fs.lstatSync(filePath).isFile()) return
    content = fs.readFileSync(filePath, "utf-8")
  } catch {
    // No such file, which is the usual case.
    return
  }
  // A failure to remove it fails the run, rather than leaving it behind.
  if (content.includes(GENERATED_MARKER)) fs.rmSync(filePath)
}

/** Whether an `index.ts` re-exports, or otherwise names, the factories file. */
function mentionsFactoriesFile(content: string): boolean {
  return content.includes(`./${FACTORIES_FILE_NAME.replace(/\.ts$/, "")}`)
}

export interface PipelineResult {
  canisterName: string
  success: boolean
  /** All files the pipeline attempted to write */
  files: GeneratorResult[]
  error?: string
  /**
   * Things the run could not fix for the user, such as an `index.ts` of
   * their own that does not re-export the factories it generated. The CLI
   * and the Vite plugin print them. Absent when there are none.
   */
  warnings?: string[]
}

/**
 * Run the full codegen pipeline for a single canister.
 *
 * @returns PipelineResult with per-file details
 */
export async function runCanisterPipeline(
  options: PipelineOptions
): Promise<PipelineResult> {
  const {
    canisterConfig,
    projectRoot,
    globalConfig,
    generateReactor = true,
  } = options
  const { name, didFile, clientManagerPath } = canisterConfig

  const files: GeneratorResult[] = []

  // ── Validate config ────────────────────────────────────────────────────────
  //
  // Runs before any filesystem work. `name`, `outDir` and `clientManagerPath`
  // come from a checked-in config file, and downstream they become a directory
  // this pipeline recursively deletes and source text it writes into the user's
  // bundle — so they are validated here, at the choke point every entry path
  // (CLI, vite plugin, direct API) goes through.
  let validated: ReturnType<typeof assertSafeCanisterConfig>
  try {
    validated = assertSafeCanisterConfig({
      name,
      canisterOutDir: canisterConfig.outDir,
      globalOutDir: globalConfig.outDir,
      clientManagerPath:
        clientManagerPath ?? globalConfig.clientManagerPath ?? "../../clients",
      projectRoot,
      mode: canisterConfig.mode,
      target: canisterConfig.target ?? globalConfig.target,
      factories: canisterConfig.factories,
    })
  } catch (err) {
    if (err instanceof CodegenConfigError) {
      return {
        canisterName: typeof name === "string" ? name : String(name),
        success: false,
        files,
        error: err.message,
      }
    }
    throw err
  }

  // ── Resolve paths ──────────────────────────────────────────────────────────

  const resolvedDidFile = path.isAbsolute(didFile)
    ? didFile
    : path.resolve(projectRoot, didFile)

  if (!fs.existsSync(resolvedDidFile)) {
    return {
      canisterName: name,
      success: false,
      files: [],
      error: `DID file not found: ${resolvedDidFile}`,
    }
  }

  // The .did basename names the generated declaration files and is the tail of
  // the import specifier the reactor emits, so it is validated here, before any
  // filesystem work, rather than surfacing as a broken import later.
  try {
    resolveDeclarationsBaseName(resolvedDidFile)
  } catch (err) {
    if (err instanceof CodegenConfigError) {
      return {
        canisterName: name,
        success: false,
        files,
        error: `[${name}] ${err.message}`,
      }
    }
    throw err
  }

  // Per-canister outDir overrides global outDir; both are resolved and
  // containment-checked by assertSafeCanisterConfig above.
  const canisterOutDir = validated.outDir

  // Refuse to generate into a directory another canister already owns. This has
  // to happen before the declarations step, which replaces `declarations/`
  // wholesale and would otherwise take the other canister's output with it.
  // generateDeclarations claims the directory before its first await, so no
  // await may come between this check and that call. Concurrent runs rely on it.
  const owner = findOutDirOwner(canisterOutDir)
  if (owner !== undefined && owner !== name) {
    return {
      canisterName: name,
      success: false,
      files,
      error:
        `[${name}] Output directory ${canisterOutDir} was generated for canister ` +
        `"${owner}". Two canisters cannot share an outDir — each run replaces the ` +
        `declarations directory and index.generated.ts, so they would overwrite each ` +
        `other. Give each canister its own "outDir". If you renamed "${owner}" to ` +
        `"${name}", delete that directory and regenerate.`,
    }
  }

  // clientManagerPath falls back to global, then a safe default
  const resolvedClientManagerPath = validated.clientManagerPath

  // ── Step 1: Declarations ───────────────────────────────────────────────────

  try {
    const declResult = await generateDeclarations({
      didFile: resolvedDidFile,
      outDir: canisterOutDir,
      canisterName: name,
      projectRoot,
    })

    if (!declResult.success) {
      return {
        canisterName: name,
        success: false,
        files,
        error: declResult.error,
      }
    }

    files.push(...declResult.files)
  } catch (err) {
    return {
      canisterName: name,
      success: false,
      files,
      error: `Declarations step failed: ${err instanceof Error ? err.message : String(err)}`,
    }
  }

  if (!generateReactor) {
    return {
      canisterName: name,
      success: true,
      files,
    }
  }

  // ── Step 2: Reactor file ───────────────────────────────────────────────────

  const reactorPath = path.join(canisterOutDir, "index.generated.ts")
  const factoriesPath = path.join(canisterOutDir, FACTORIES_FILE_NAME)
  const entryPath = path.join(canisterOutDir, "index.ts")
  const reactorClass = resolveReactorClass(canisterConfig)
  const runtimeTarget = resolveRuntimeTarget(canisterConfig, globalConfig)
  // Validated above as a boolean, and only with target "react".
  const factories = canisterConfig.factories === true
  const warnings: string[] = []

  try {
    // Both wrappers the template writes, the one that re-exports the
    // factories and the one that does not, so a wrapper nobody edited follows
    // the option when it is switched either way.
    const templateEntryContents = [
      generateReactorEntryFile({ factories: false }),
      generateReactorEntryFile({ factories: true }),
    ]

    // Formatted with the project's Prettier, as the declarations are. In the
    // template's own style, both files failed `prettier --check` in any project
    // whose config differs from it, Prettier's defaults included, and in a
    // project that formatted them every run rewrote them.
    const prettier = await loadPrettier(projectRoot)
    const reactorContent = await formatGenerated(
      prettier,
      projectRoot,
      generateReactorFile({
        canisterName: name,
        didFile: resolvedDidFile,
        clientManagerPath: resolvedClientManagerPath,
        canisterId: canisterConfig.canisterId,
        runtimeTarget,
        reactorClass,
      }),
      reactorPath,
      "typescript"
    )
    const factoriesContent = factories
      ? await formatGenerated(
          prettier,
          projectRoot,
          generateFactoriesFile({
            canisterName: name,
            methods: readServiceMethods(
              path.join(
                canisterOutDir,
                "declarations",
                `${resolveDeclarationsBaseName(resolvedDidFile)}.did`
              )
            ),
            reactorClass,
          }),
          factoriesPath,
          "typescript"
        )
      : undefined
    const formattedEntryContents = await Promise.all(
      templateEntryContents.map((content) =>
        formatGenerated(prettier, projectRoot, content, entryPath, "typescript")
      )
    )
    const entryContent = formattedEntryContents[factories ? 1 : 0]

    // Every write below either replaces the entry at its path or creates a new
    // one, so a symbolic link committed into the output directory cannot
    // redirect it. A replace leaves a regular file that already holds the new
    // bytes untouched. See write.ts.
    fs.mkdirSync(canisterOutDir, { recursive: true })
    // One call, so a failed write leaves both managed files as they were
    // rather than factories typed against a reactor file that did not change.
    replaceFiles(
      factoriesContent === undefined
        ? [[reactorPath, reactorContent]]
        : [
            [reactorPath, reactorContent],
            [factoriesPath, factoriesContent],
          ]
    )
    files.push({ success: true, filePath: reactorPath })
    if (factoriesContent !== undefined) {
      files.push({ success: true, filePath: factoriesPath })
    } else {
      removeGeneratedFactoriesFile(factoriesPath)
    }

    if (!fs.existsSync(entryPath)) {
      // A dangling link also lands here, and createFile fails on it.
      createFile(entryPath, entryContent)
      files.push({ success: true, filePath: entryPath })
    } else {
      const existingEntryContent = fs.readFileSync(entryPath, "utf-8")

      if (
        isManagedEntryWrapper(existingEntryContent, [
          ...formattedEntryContents,
          ...templateEntryContents,
        ])
      ) {
        replaceFile(entryPath, entryContent)
        files.push({ success: true, filePath: entryPath })
      } else if (isLegacyGeneratedIndexFile(existingEntryContent, name)) {
        // Migration replaces a file the user owns, on the strength of a
        // content match. Keep the original so a wrong match is recoverable.
        const backupPath = backUpFile(entryPath)
        replaceFile(entryPath, entryContent)
        files.push({ success: true, filePath: backupPath })
        files.push({ success: true, filePath: entryPath })
      } else {
        files.push({ success: true, filePath: entryPath, skipped: true })

        // The wrapper is the user's, so what it exports is theirs to change.
        // Said here, since the missing export otherwise shows up as an import
        // error in whichever module first reaches for a factory.
        const entryName = path.relative(projectRoot, entryPath)
        if (factories && !mentionsFactoriesFile(existingEntryContent)) {
          warnings.push(
            `${entryName} is not the generated wrapper, so codegen left it as it is, and it ` +
              `does not re-export the factories. Add ` +
              `\`export * from "./index.factories.generated"\` to it to import them from ` +
              `the canister's entry point.`
          )
        } else if (
          !factories &&
          mentionsFactoriesFile(existingEntryContent) &&
          !fs.existsSync(factoriesPath)
        ) {
          warnings.push(
            `${entryName} imports ./index.factories.generated, which codegen writes only ` +
              `while the canister sets factories: true. Remove that import, or set ` +
              `factories again.`
          )
        }
      }
    }
  } catch (err) {
    files.push({
      success: false,
      filePath: reactorPath,
      error: `Reactor generation failed: ${err instanceof Error ? err.message : String(err)}`,
    })

    return {
      canisterName: name,
      success: false,
      files,
      error: `Reactor step failed: ${err instanceof Error ? err.message : String(err)}`,
    }
  }

  return {
    canisterName: name,
    success: true,
    files,
    ...(warnings.length > 0 ? { warnings } : {}),
  }
}
