import fs from "node:fs"
import os from "node:os"
import path from "node:path"
import { afterEach, describe, expect, it } from "vitest"
import { runCanisterPipeline } from "./pipeline"

describe("Codegen pipeline", () => {
  const tempDirs: string[] = []

  afterEach(() => {
    for (const dir of tempDirs) {
      fs.rmSync(dir, { recursive: true, force: true })
    }
    tempDirs.length = 0
  })

  function createTempProject() {
    const projectRoot = fs.mkdtempSync(
      path.join(os.tmpdir(), "ic-reactor-codegen-pipeline-")
    )
    tempDirs.push(projectRoot)
    return projectRoot
  }

  function writeDid(projectRoot: string, fileName: string) {
    fs.writeFileSync(
      path.join(projectRoot, fileName),
      `service : {
  greet: (text) -> (text) query;
}`
    )
  }

  it("uses per-canister mode to generate Reactor-based hooks", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "workflow_engine.did")

    const result = await runCanisterPipeline({
      canisterConfig: {
        name: "workflow_engine",
        didFile: "workflow_engine.did",
        mode: "Reactor",
      },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
    })

    expect(result.success).toBe(true)

    const indexPath = path.join(
      projectRoot,
      "src/declarations/workflow_engine/index.generated.ts"
    )
    const generated = fs.readFileSync(indexPath, "utf-8")

    expect(generated).toContain("new Reactor<WorkflowEngineService>")
    expect(generated).not.toContain("new DisplayReactor<WorkflowEngineService>")
    expect(
      fs.readFileSync(
        path.join(projectRoot, "src/declarations/workflow_engine/index.ts"),
        "utf-8"
      )
    ).toContain('export * from "./index.generated"')
  })

  it("writes a configured canisterId into the generated reactor", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "workflow.did")

    const result = await runCanisterPipeline({
      canisterConfig: {
        name: "workflow",
        didFile: "workflow.did",
        canisterId: "yq4ns-hyaaa-aaaap-akbna-cai",
      },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
    })

    expect(result.success).toBe(true)

    const indexPath = path.join(
      projectRoot,
      "src/declarations/workflow/index.generated.ts"
    )
    const generated = fs.readFileSync(indexPath, "utf-8")

    expect(generated).toContain('canisterId: "yq4ns-hyaaa-aaaap-akbna-cai"')
    expect(generated).toContain('name: "workflow"')
  })

  it("does not overwrite user-modified index.ts on regenerate", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "backend.did")

    const options = {
      canisterConfig: {
        name: "backend",
        didFile: "backend.did",
      },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
    } as const

    const first = await runCanisterPipeline(options)
    expect(first.success).toBe(true)

    const indexPath = path.join(
      projectRoot,
      "src/declarations/backend/index.ts"
    )
    fs.writeFileSync(
      indexPath,
      `// user custom canister file
export const customBackendIndex = true
`
    )

    const second = await runCanisterPipeline({
      ...options,
      canisterConfig: {
        ...options.canisterConfig,
        canisterId: "yq4ns-hyaaa-aaaap-akbna-cai",
      },
    })
    expect(second.success).toBe(true)

    const wrapper = fs.readFileSync(indexPath, "utf-8")
    expect(wrapper).toContain("customBackendIndex = true")
    const generatedImpl = fs.readFileSync(
      path.join(projectRoot, "src/declarations/backend/index.generated.ts"),
      "utf-8"
    )
    expect(generatedImpl).toContain('canisterId: "yq4ns-hyaaa-aaaap-akbna-cai"')
    expect(second.files).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          filePath: indexPath,
          skipped: true,
          success: true,
        }),
      ])
    )
  })

  it("migrates a legacy generated index.ts to the managed wrapper", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "backend.did")

    const canisterOutDir = path.join(projectRoot, "src/declarations/backend")
    fs.mkdirSync(canisterOutDir, { recursive: true })

    const existingGeneratedIndex = `import { DisplayReactor, createActorHooks } from "@ic-reactor/react"
import { clientManager } from "../../clients"
import { idlFactory, type _SERVICE } from "./declarations/backend"

export type BackendService = _SERVICE

/**
 * Backend Reactor
 *
 * Auto-generated by @ic-reactor/codegen — do not edit.
 */
export const backendReactor = new DisplayReactor<BackendService>({
  clientManager,
  idlFactory,
  name: "backend",
})

export const {
  useActorQuery: useBackendQuery,
} = createActorHooks(backendReactor)
`
    fs.writeFileSync(
      path.join(canisterOutDir, "index.ts"),
      existingGeneratedIndex
    )

    const result = await runCanisterPipeline({
      canisterConfig: {
        name: "backend",
        didFile: "backend.did",
      },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
    })

    expect(result.success).toBe(true)

    const indexPath = path.join(canisterOutDir, "index.ts")
    const entry = fs.readFileSync(indexPath, "utf-8")
    const generated = fs.readFileSync(
      path.join(canisterOutDir, "index.generated.ts"),
      "utf-8"
    )
    expect(entry).toContain('export * from "./index.generated"')
    expect(entry).not.toBe(existingGeneratedIndex)
    expect(generated).toContain("new DisplayReactor<BackendService>")
    expect(generated).toContain("useBackendMutation")
    expect(result.files).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          filePath: path.join(canisterOutDir, "index.generated.ts"),
          success: true,
        }),
        expect.objectContaining({
          filePath: indexPath,
          success: true,
        }),
      ])
    )
  })
})
