import fs from "node:fs"
import { createRequire } from "node:module"
import os from "node:os"
import path from "node:path"
import { afterEach, describe, expect, it } from "vitest"
import { runCanisterPipeline } from "./pipeline.js"
import { generateReactorEntryFile } from "./generators/reactor.js"
import type { CanisterConfig } from "./types.js"

/** An `index.ts` as the generator wrote it before the index.generated.ts split. */
const LEGACY_BACKEND_INDEX = `import { DisplayReactor, createActorHooks } from "@ic-reactor/react"
import { clientManager } from "../../clients"
import { idlFactory, type _SERVICE } from "./declarations/backend"

export type BackendService = _SERVICE

/**
 * Backend Reactor
 *
 * Auto-generated by @ic-reactor/codegen — do not edit.
 */
export const backendReactor = new DisplayReactor<BackendService>({
  clientManager,
  idlFactory,
  name: "backend",
})

export const {
  useActorQuery: useBackendQuery,
} = createActorHooks(backendReactor)
`

describe("Codegen pipeline", () => {
  const tempDirs: string[] = []

  afterEach(() => {
    for (const dir of tempDirs) {
      fs.rmSync(dir, { recursive: true, force: true })
    }
    tempDirs.length = 0
  })

  function createTempProject() {
    const projectRoot = fs.mkdtempSync(
      path.join(os.tmpdir(), "ic-reactor-codegen-pipeline-")
    )
    tempDirs.push(projectRoot)
    return projectRoot
  }

  function writeDid(projectRoot: string, fileName: string) {
    fs.writeFileSync(
      path.join(projectRoot, fileName),
      `service : {
  greet: (text) -> (text) query;
}`
    )
  }

  /**
   * Inode and mtime of `dir` and of every entry under it, by relative path.
   * Codegen replaces a file by renaming a new one onto it, which gives the path
   * a new inode even when the bytes are the same.
   */
  function statTree(dir: string) {
    const tree: Record<string, { ino: number; mtimeMs: number }> = {}
    const visit = (entryPath: string) => {
      const stat = fs.lstatSync(entryPath)
      tree[path.relative(dir, entryPath) || "."] = {
        ino: stat.ino,
        mtimeMs: stat.mtimeMs,
      }
      if (stat.isDirectory()) {
        for (const entry of fs.readdirSync(entryPath)) {
          visit(path.join(entryPath, entry))
        }
      }
    }
    visit(dir)
    return tree
  }

  it("uses per-canister mode to generate Reactor-based hooks", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "workflow_engine.did")

    const result = await runCanisterPipeline({
      canisterConfig: {
        name: "workflow_engine",
        didFile: "workflow_engine.did",
        mode: "Reactor",
      },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
    })

    expect(result.success).toBe(true)

    const indexPath = path.join(
      projectRoot,
      "src/declarations/workflow_engine/index.generated.ts"
    )
    const generated = fs.readFileSync(indexPath, "utf-8")

    expect(generated).toContain("new Reactor<WorkflowEngineService>")
    expect(generated).not.toContain("new DisplayReactor<WorkflowEngineService>")
    expect(
      fs.readFileSync(
        path.join(projectRoot, "src/declarations/workflow_engine/index.ts"),
        "utf-8"
      )
    ).toContain('export * from "./index.generated"')
  })

  it("writes a configured canisterId into the generated reactor", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "workflow.did")

    const result = await runCanisterPipeline({
      canisterConfig: {
        name: "workflow",
        didFile: "workflow.did",
        canisterId: "yq4ns-hyaaa-aaaap-akbna-cai",
      },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
    })

    expect(result.success).toBe(true)

    const indexPath = path.join(
      projectRoot,
      "src/declarations/workflow/index.generated.ts"
    )
    const generated = fs.readFileSync(indexPath, "utf-8")

    expect(generated).toContain('canisterId: "yq4ns-hyaaa-aaaap-akbna-cai"')
    expect(generated).toContain('name: "workflow"')
  })

  it("can generate declarations without creating reactor files", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "backend.did")

    const result = await runCanisterPipeline({
      canisterConfig: {
        name: "backend",
        didFile: "backend.did",
      },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
      generateReactor: false,
    })

    expect(result.success).toBe(true)
    expect(
      fs.existsSync(
        path.join(
          projectRoot,
          "src/declarations/backend/declarations/backend.js"
        )
      )
    ).toBe(true)
    expect(
      fs.existsSync(
        path.join(
          projectRoot,
          "src/declarations/backend/declarations/backend.d.ts"
        )
      )
    ).toBe(true)
    expect(
      fs.existsSync(
        path.join(
          projectRoot,
          "src/declarations/backend/declarations/backend.did"
        )
      )
    ).toBe(true)
    expect(
      fs.existsSync(
        path.join(projectRoot, "src/declarations/backend/index.generated.ts")
      )
    ).toBe(false)
    expect(
      fs.existsSync(path.join(projectRoot, "src/declarations/backend/index.ts"))
    ).toBe(false)
    expect(
      result.files.some((file) => file.filePath.endsWith("index.generated.ts"))
    ).toBe(false)
    expect(
      result.files.some((file) => file.filePath.endsWith("index.ts"))
    ).toBe(false)
  })

  it("formats declarations with the Prettier installed at projectRoot", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "backend.did")
    fs.mkdirSync(path.join(projectRoot, "node_modules"))
    fs.symlinkSync(
      path.dirname(
        createRequire(import.meta.url).resolve("prettier/package.json")
      ),
      path.join(projectRoot, "node_modules", "prettier"),
      "junction"
    )
    fs.writeFileSync(
      path.join(projectRoot, ".prettierrc"),
      JSON.stringify({ semi: false })
    )

    const result = await runCanisterPipeline({
      canisterConfig: { name: "backend", didFile: "backend.did" },
      projectRoot,
      globalConfig: { outDir: "src/declarations" },
      generateReactor: false,
    })

    expect(result.error).toBeUndefined()
    expect(
      fs.readFileSync(
        path.join(
          projectRoot,
          "src/declarations/backend/declarations/backend.js"
        ),
        "utf-8"
      )
    ).toBe(
      [
        "export const idlFactory = ({ IDL }) => {",
        '  return IDL.Service({ greet: IDL.Func([IDL.Text], [IDL.Text], ["query"]) })',
        "}",
        "export const init = ({ IDL }) => {",
        "  return []",
        "}",
        "",
      ].join("\n")
    )
  })

  describe("with Prettier installed at projectRoot", () => {
    const prettierDir = path.dirname(
      createRequire(import.meta.url).resolve("prettier/package.json")
    )

    /** A project whose Prettier config differs from the templates' style. */
    function createFormattedProject() {
      const projectRoot = createTempProject()
      writeDid(projectRoot, "backend.did")
      fs.mkdirSync(path.join(projectRoot, "node_modules"))
      fs.symlinkSync(
        prettierDir,
        path.join(projectRoot, "node_modules", "prettier"),
        "junction"
      )
      fs.writeFileSync(
        path.join(projectRoot, ".prettierrc"),
        JSON.stringify({ semi: true, singleQuote: true })
      )
      return projectRoot
    }

    /** What `prettier --check` says about a file in the project. */
    async function isFormatted(filePath: string) {
      const prettier = (await import("prettier")).default
      const options = await prettier.resolveConfig(filePath)
      return prettier.check(fs.readFileSync(filePath, "utf-8"), {
        ...options,
        filepath: filePath,
      })
    }

    const options = (projectRoot: string) => ({
      canisterConfig: { name: "backend", didFile: "backend.did" },
      projectRoot,
      globalConfig: { outDir: "src/declarations" },
    })

    // Only the declarations were formatted. index.generated.ts and index.ts
    // came out in the template's style, so `prettier --check` failed on them,
    // and once formatted, every run rewrote index.generated.ts.
    it("formats index.generated.ts and index.ts with the project's config", async () => {
      const projectRoot = createFormattedProject()
      const outDir = path.join(projectRoot, "src/declarations/backend")

      const result = await runCanisterPipeline(options(projectRoot))

      expect(result.error).toBeUndefined()
      expect(await isFormatted(path.join(outDir, "index.generated.ts"))).toBe(
        true
      )
      expect(await isFormatted(path.join(outDir, "index.ts"))).toBe(true)
      expect(
        fs.readFileSync(path.join(outDir, "index.generated.ts"), "utf-8")
      ).toContain("import { clientManager } from '../../clients';")
    })

    // Without the `.ic-reactor-owner` marker, which projects may leave out of
    // version control, the owner is read from index.generated.ts, which is now
    // formatted with the project's quotes and indent.
    it("still finds the owner of a formatted directory that lost its marker", async () => {
      const projectRoot = createFormattedProject()
      fs.writeFileSync(
        path.join(projectRoot, ".prettierrc"),
        JSON.stringify({ singleQuote: true, useTabs: true })
      )
      writeDid(projectRoot, "ledger.did")
      const shared = { outDir: "src/shared" }

      const first = await runCanisterPipeline({
        ...options(projectRoot),
        canisterConfig: { name: "backend", didFile: "backend.did", ...shared },
      })
      expect(first.error).toBeUndefined()
      fs.rmSync(path.join(projectRoot, "src/shared/.ic-reactor-owner"))

      const second = await runCanisterPipeline({
        ...options(projectRoot),
        canisterConfig: { name: "ledger", didFile: "ledger.did", ...shared },
      })

      expect(second.success).toBe(false)
      expect(second.error).toContain('was generated for canister "backend"')
    })

    it("replaces a wrapper an earlier version wrote in the template's style", async () => {
      const projectRoot = createFormattedProject()
      const outDir = path.join(projectRoot, "src/declarations/backend")
      fs.mkdirSync(outDir, { recursive: true })
      fs.writeFileSync(
        path.join(outDir, "index.ts"),
        generateReactorEntryFile()
      )

      const result = await runCanisterPipeline(options(projectRoot))

      expect(result.error).toBeUndefined()
      expect(fs.readFileSync(path.join(outDir, "index.ts"), "utf-8")).toContain(
        "export * from './index.generated';"
      )
    })

    // Formatting has to come out the same on every run for the unchanged
    // output to be recognised as unchanged.
    it("leaves every output untouched when regenerating with nothing changed", async () => {
      const projectRoot = createFormattedProject()
      const outDir = path.join(projectRoot, "src/declarations/backend")

      const first = await runCanisterPipeline(options(projectRoot))
      expect(first.error).toBeUndefined()
      const before = statTree(outDir)

      const second = await runCanisterPipeline(options(projectRoot))

      expect(second.error).toBeUndefined()
      expect(statTree(outDir)).toEqual(before)
    })
  })

  it("leaves existing reactor files untouched when reactor generation is disabled", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "backend.did")

    const canisterOutDir = path.join(projectRoot, "src/declarations/backend")
    fs.mkdirSync(canisterOutDir, { recursive: true })

    const existingGenerated = "// existing generated reactor"
    const existingEntry = "// existing entry wrapper"

    fs.writeFileSync(
      path.join(canisterOutDir, "index.generated.ts"),
      existingGenerated
    )
    fs.writeFileSync(path.join(canisterOutDir, "index.ts"), existingEntry)

    const result = await runCanisterPipeline({
      canisterConfig: {
        name: "backend",
        didFile: "backend.did",
      },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
      generateReactor: false,
    })

    expect(result.success).toBe(true)
    expect(
      fs.readFileSync(path.join(canisterOutDir, "index.generated.ts"), "utf-8")
    ).toBe(existingGenerated)
    expect(
      fs.readFileSync(path.join(canisterOutDir, "index.ts"), "utf-8")
    ).toBe(existingEntry)
  })

  it("supports a core target without generating React hooks", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "backend.did")

    const result = await runCanisterPipeline({
      canisterConfig: {
        name: "backend",
        didFile: "backend.did",
      },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
        target: "core",
      },
    })

    expect(result.success).toBe(true)

    const indexPath = path.join(
      projectRoot,
      "src/declarations/backend/index.generated.ts"
    )
    const generated = fs.readFileSync(indexPath, "utf-8")

    expect(generated).toContain(
      'import { DisplayReactor } from "@ic-reactor/core"'
    )
    expect(generated).not.toContain(
      'import { createActorHooks } from "@ic-reactor/react"'
    )
    expect(generated).not.toContain("useBackendQuery")
  })

  it("does not overwrite user-modified index.ts on regenerate", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "backend.did")

    const options = {
      canisterConfig: {
        name: "backend",
        didFile: "backend.did",
      },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
    } as const

    const first = await runCanisterPipeline(options)
    expect(first.success).toBe(true)

    const indexPath = path.join(
      projectRoot,
      "src/declarations/backend/index.ts"
    )
    fs.writeFileSync(
      indexPath,
      `// user custom canister file
export const customBackendIndex = true
`
    )

    const second = await runCanisterPipeline({
      ...options,
      canisterConfig: {
        ...options.canisterConfig,
        canisterId: "yq4ns-hyaaa-aaaap-akbna-cai",
      },
    })
    expect(second.success).toBe(true)

    const wrapper = fs.readFileSync(indexPath, "utf-8")
    expect(wrapper).toContain("customBackendIndex = true")
    const generatedImpl = fs.readFileSync(
      path.join(projectRoot, "src/declarations/backend/index.generated.ts"),
      "utf-8"
    )
    expect(generatedImpl).toContain('canisterId: "yq4ns-hyaaa-aaaap-akbna-cai"')
    expect(second.files).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          filePath: indexPath,
          skipped: true,
          success: true,
        }),
      ])
    )
  })

  it("fails when the .did declares no service instead of emitting a broken import", async () => {
    const projectRoot = createTempProject()
    fs.writeFileSync(
      path.join(projectRoot, "shared_types.did"),
      "type Foo = record { a : nat };"
    )

    const result = await runCanisterPipeline({
      canisterConfig: {
        name: "backend",
        didFile: "shared_types.did",
      },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
    })

    expect(result.success).toBe(false)
    expect(result.error).toContain("backend")
    expect(result.error).toContain(path.join(projectRoot, "shared_types.did"))
    // The reactor would otherwise import idlFactory and _SERVICE from a module
    // that exports neither.
    expect(
      fs.existsSync(
        path.join(projectRoot, "src/declarations/backend/index.generated.ts")
      )
    ).toBe(false)
  })

  it("fails when the didFile basename is a directory reference", async () => {
    const projectRoot = createTempProject()
    fs.mkdirSync(path.join(projectRoot, "canisters"))

    const result = await runCanisterPipeline({
      canisterConfig: {
        name: "backend",
        // Absolute, so it reaches the pipeline unnormalized and its basename is
        // "..", which would become `import … from "./declarations/.."`.
        didFile: `${projectRoot}/canisters/..`,
      },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
    })

    expect(result.success).toBe(false)
    expect(result.error).toContain("refers to a directory")
  })

  describe("a didFile inside the canister's own declarations directory", () => {
    const globalConfig = {
      outDir: "src/declarations",
      clientManagerPath: "../../clients",
    }
    const source = "service : { greet : (text) -> (text) query }\n"

    function writeDidAt(projectRoot: string, didFile: string) {
      const didPath = path.join(projectRoot, didFile)
      fs.mkdirSync(path.dirname(didPath), { recursive: true })
      fs.writeFileSync(didPath, source)
      return didPath
    }

    // declarations/ is generated output. A run that did not find exactly its
    // own files there replaced the whole directory, so this .did was read and
    // then deleted with its folder, and the next run failed with "DID file not
    // found".
    it("is refused, and the .did and its folder are left in place", async () => {
      const projectRoot = createTempProject()
      const didFile = "src/declarations/backend/declarations/candid/backend.did"
      const didPath = writeDidAt(projectRoot, didFile)
      const notes = path.join(path.dirname(didPath), "notes.md")
      fs.writeFileSync(notes, "kept by the user\n")

      const result = await runCanisterPipeline({
        canisterConfig: { name: "backend", didFile },
        projectRoot,
        globalConfig,
      })

      expect(result.success).toBe(false)
      expect(result.error).toContain("is inside")
      expect(result.error).toContain("Move the .did file out")
      expect(fs.readFileSync(didPath, "utf-8")).toBe(source)
      expect(fs.readFileSync(notes, "utf-8")).toBe("kept by the user\n")
    })

    it("is refused when it sits directly in the directory", async () => {
      const projectRoot = createTempProject()
      const didFile = "src/declarations/backend/declarations/backend.did"
      const didPath = writeDidAt(projectRoot, didFile)

      const result = await runCanisterPipeline({
        canisterConfig: { name: "backend", didFile },
        projectRoot,
        globalConfig,
      })

      expect(result.success).toBe(false)
      expect(result.error).toContain("is inside")
      expect(fs.readFileSync(didPath, "utf-8")).toBe(source)
    })

    it("is refused when the outDir reaches the directory through a link", async () => {
      const projectRoot = createTempProject()
      const didFile = "src/declarations/backend/declarations/candid/backend.did"
      const didPath = writeDidAt(projectRoot, didFile)
      fs.symlinkSync(
        path.join(projectRoot, "src"),
        path.join(projectRoot, "linked"),
        "junction"
      )

      const result = await runCanisterPipeline({
        canisterConfig: {
          name: "backend",
          didFile,
          outDir: "linked/declarations/backend",
        },
        projectRoot,
        globalConfig,
      })

      expect(result.success).toBe(false)
      expect(result.error).toContain("is inside")
      expect(fs.readFileSync(didPath, "utf-8")).toBe(source)
    })

    it.each([
      // dfx generate leaves a copy at src/declarations/<canister>/<canister>.did,
      // in the canister's outDir but not in its declarations directory.
      "src/declarations/backend/backend.did",
      // A sibling whose name only starts like the declarations directory.
      "src/declarations/backend/declarations2/backend.did",
    ])("still generates from %s", async (didFile) => {
      const projectRoot = createTempProject()
      const didPath = writeDidAt(projectRoot, didFile)

      const result = await runCanisterPipeline({
        canisterConfig: { name: "backend", didFile },
        projectRoot,
        globalConfig,
      })

      expect(result.error).toBeUndefined()
      expect(result.success).toBe(true)
      expect(fs.readFileSync(didPath, "utf-8")).toBe(source)
    })
  })

  it("refuses to generate into an outDir another canister already owns", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "backend.did")
    writeDid(projectRoot, "ledger.did")

    const sharedOutDir = "src/declarations/shared"
    const globalConfig = {
      outDir: "src/declarations",
      clientManagerPath: "../../clients",
    }

    const first = await runCanisterPipeline({
      canisterConfig: {
        name: "backend",
        didFile: "backend.did",
        outDir: sharedOutDir,
      },
      projectRoot,
      globalConfig,
    })
    expect(first.success).toBe(true)

    const declarationsDir = path.join(projectRoot, sharedOutDir, "declarations")
    const before = fs.readdirSync(declarationsDir).sort()

    const second = await runCanisterPipeline({
      canisterConfig: {
        name: "ledger",
        didFile: "ledger.did",
        outDir: sharedOutDir,
      },
      projectRoot,
      globalConfig,
    })

    expect(second.success).toBe(false)
    expect(second.error).toContain("backend")
    expect(second.error).toContain("ledger")
    // The first canister's output survives untouched.
    expect(fs.readdirSync(declarationsDir).sort()).toEqual(before)
    expect(
      fs.readFileSync(
        path.join(projectRoot, sharedOutDir, "index.generated.ts"),
        "utf-8"
      )
    ).toContain('name: "backend"')
  })

  // `--bindgen-only` sets generateReactor:false, so index.generated.ts is never
  // written. An ownership guard that keyed off that file therefore had nothing
  // to read on exactly the path that still replaces declarations/ — both runs
  // reported success and the first canister's output vanished.
  it("refuses a shared outDir on the bindgen-only path too", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "backend.did")
    writeDid(projectRoot, "ledger.did")

    const sharedOutDir = "src/declarations/shared"
    const globalConfig = {
      outDir: "src/declarations",
      clientManagerPath: "../../clients",
    }

    const first = await runCanisterPipeline({
      canisterConfig: {
        name: "backend",
        didFile: "backend.did",
        outDir: sharedOutDir,
      },
      projectRoot,
      globalConfig,
      generateReactor: false,
    })
    expect(first.success).toBe(true)

    const declarationsDir = path.join(projectRoot, sharedOutDir, "declarations")
    const before = fs.readdirSync(declarationsDir).sort()
    expect(before).toContain("backend.js")
    // The guard cannot rely on this file existing here.
    expect(
      fs.existsSync(path.join(projectRoot, sharedOutDir, "index.generated.ts"))
    ).toBe(false)

    const second = await runCanisterPipeline({
      canisterConfig: {
        name: "ledger",
        didFile: "ledger.did",
        outDir: sharedOutDir,
      },
      projectRoot,
      globalConfig,
      generateReactor: false,
    })

    expect(second.success).toBe(false)
    expect(second.error).toContain("backend")
    expect(fs.readdirSync(declarationsDir).sort()).toEqual(before)
  })

  // The vite plugin starts every canister's pipeline at once. Formatting added
  // awaits between the ownership check and the marker write, so on a fresh
  // outDir both runs found no owner, both wrote, and both reported success.
  it("refuses a shared outDir when two canisters generate concurrently", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "backend.did")
    writeDid(projectRoot, "ledger.did")

    const sharedOutDir = "src/declarations/shared"
    const globalConfig = {
      outDir: "src/declarations",
      clientManagerPath: "../../clients",
    }

    const [first, second] = await Promise.all([
      runCanisterPipeline({
        canisterConfig: {
          name: "backend",
          didFile: "backend.did",
          outDir: sharedOutDir,
        },
        projectRoot,
        globalConfig,
      }),
      runCanisterPipeline({
        canisterConfig: {
          name: "ledger",
          didFile: "ledger.did",
          outDir: sharedOutDir,
        },
        projectRoot,
        globalConfig,
      }),
    ])

    expect(first.success).toBe(true)
    expect(second.success).toBe(false)
    expect(second.error).toContain("backend")
    expect(
      fs
        .readdirSync(path.join(projectRoot, sharedOutDir, "declarations"))
        .sort()
    ).toEqual(["backend.d.ts", "backend.did", "backend.js"])
    expect(
      fs.readFileSync(
        path.join(projectRoot, sharedOutDir, "index.generated.ts"),
        "utf-8"
      )
    ).toContain('name: "backend"')
  })

  it("preserves an index.ts that kept the generated header but grew its own exports", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "backend.did")

    const canisterOutDir = path.join(projectRoot, "src/declarations/backend")
    fs.mkdirSync(canisterOutDir, { recursive: true })

    // Started life as generated output, then the user added a factory to it.
    const userOwned = `import { DisplayReactor, createActorHooks } from "@ic-reactor/react"
import { createQuery } from "@ic-reactor/react"
import { clientManager } from "../../clients"
import { idlFactory, type _SERVICE } from "./declarations/backend"

export type BackendService = _SERVICE

/**
 * Backend Reactor
 *
 * Auto-generated by @ic-reactor/codegen — do not edit.
 */
export const backendReactor = new DisplayReactor<BackendService>({
  clientManager,
  idlFactory,
  name: "backend",
})

export const {
  useActorQuery: useBackendQuery,
} = createActorHooks(backendReactor)

export const greetQuery = createQuery(backendReactor, "greet")
`
    const indexPath = path.join(canisterOutDir, "index.ts")
    fs.writeFileSync(indexPath, userOwned)

    const result = await runCanisterPipeline({
      canisterConfig: {
        name: "backend",
        didFile: "backend.did",
      },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
    })

    expect(result.success).toBe(true)
    expect(fs.readFileSync(indexPath, "utf-8")).toBe(userOwned)
    expect(result.files).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ filePath: indexPath, skipped: true }),
      ])
    )
  })

  it("migrates a legacy generated index.ts to the managed wrapper", async () => {
    const projectRoot = createTempProject()
    writeDid(projectRoot, "backend.did")

    const canisterOutDir = path.join(projectRoot, "src/declarations/backend")
    fs.mkdirSync(canisterOutDir, { recursive: true })

    const existingGeneratedIndex = LEGACY_BACKEND_INDEX
    fs.writeFileSync(
      path.join(canisterOutDir, "index.ts"),
      existingGeneratedIndex
    )

    const result = await runCanisterPipeline({
      canisterConfig: {
        name: "backend",
        didFile: "backend.did",
      },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
    })

    expect(result.success).toBe(true)

    const indexPath = path.join(canisterOutDir, "index.ts")
    const entry = fs.readFileSync(indexPath, "utf-8")
    const generated = fs.readFileSync(
      path.join(canisterOutDir, "index.generated.ts"),
      "utf-8"
    )
    expect(entry).toContain('export * from "./index.generated"')
    expect(entry).not.toBe(existingGeneratedIndex)
    expect(generated).toContain("new DisplayReactor<BackendService>")
    expect(generated).toContain("useBackendMutation")

    // Migration replaces a file the user owns on the strength of a content
    // match, so the original is kept next to it.
    const backupPath = `${indexPath}.bak`
    expect(fs.readFileSync(backupPath, "utf-8")).toBe(existingGeneratedIndex)

    expect(result.files).toEqual(
      expect.arrayContaining([
        expect.objectContaining({
          filePath: path.join(canisterOutDir, "index.generated.ts"),
          success: true,
        }),
        expect.objectContaining({
          filePath: backupPath,
          success: true,
        }),
        expect.objectContaining({
          filePath: indexPath,
          success: true,
        }),
      ])
    )
  })

  // Every run used to replace every file it generated, identical or not, and
  // each replacement wakes `tsc --watch`, the bundler's watcher and the editor.
  describe("regenerating", () => {
    const backendOptions = (projectRoot: string) => ({
      canisterConfig: { name: "backend", didFile: "backend.did" },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
    })

    it("leaves every output untouched when nothing changed", async () => {
      const projectRoot = createTempProject()
      writeDid(projectRoot, "backend.did")
      const outDir = path.join(projectRoot, "src/declarations/backend")

      const first = await runCanisterPipeline(backendOptions(projectRoot))
      expect(first.error).toBeUndefined()
      const before = statTree(outDir)
      expect(Object.keys(before).sort()).toEqual([
        ".",
        ".ic-reactor-owner",
        "declarations",
        path.join("declarations", "backend.d.ts"),
        path.join("declarations", "backend.did"),
        path.join("declarations", "backend.js"),
        "index.generated.ts",
        "index.ts",
      ])

      const second = await runCanisterPipeline(backendOptions(projectRoot))

      expect(second.error).toBeUndefined()
      expect(statTree(outDir)).toEqual(before)
    })

    it("replaces only the declaration files whose bytes changed", async () => {
      const projectRoot = createTempProject()
      writeDid(projectRoot, "backend.did")
      const outDir = path.join(projectRoot, "src/declarations/backend")

      const first = await runCanisterPipeline(backendOptions(projectRoot))
      expect(first.error).toBeUndefined()
      const before = statTree(outDir)
      const dtsPath = path.join(outDir, "declarations", "backend.d.ts")
      const dts = fs.readFileSync(dtsPath, "utf-8")

      // An update method has the same TypeScript type as a query method, so
      // the .js and the .did copy change and the .d.ts does not.
      const updateDid = `service : {
  greet: (text) -> (text);
}`
      fs.writeFileSync(path.join(projectRoot, "backend.did"), updateDid)
      const second = await runCanisterPipeline(backendOptions(projectRoot))

      expect(second.error).toBeUndefined()
      expect(
        fs.readFileSync(
          path.join(outDir, "declarations", "backend.did"),
          "utf-8"
        )
      ).toBe(updateDid)
      expect(
        fs.readFileSync(
          path.join(outDir, "declarations", "backend.js"),
          "utf-8"
        )
      ).not.toContain('"query"')
      expect(fs.readFileSync(dtsPath, "utf-8")).toBe(dts)

      const after = statTree(outDir)
      expect(Object.keys(after).sort()).toEqual(Object.keys(before).sort())
      const replaced = Object.keys(before).filter(
        (entry) => after[entry].ino !== before[entry].ino
      )
      expect(replaced.sort()).toEqual([
        path.join("declarations", "backend.did"),
        path.join("declarations", "backend.js"),
      ])
    })

    // Updating the declarations in place must not keep a file this run does
    // not generate. Before, every run rebuilt the directory and dropped it.
    it("still removes a file in declarations/ that the run does not generate", async () => {
      const projectRoot = createTempProject()
      writeDid(projectRoot, "backend.did")
      const declarationsDir = path.join(
        projectRoot,
        "src/declarations/backend/declarations"
      )

      const first = await runCanisterPipeline(backendOptions(projectRoot))
      expect(first.error).toBeUndefined()
      fs.writeFileSync(path.join(declarationsDir, "stale.js"), "// stale\n")

      const second = await runCanisterPipeline(backendOptions(projectRoot))

      expect(second.error).toBeUndefined()
      expect(fs.readdirSync(declarationsDir).sort()).toEqual([
        "backend.d.ts",
        "backend.did",
        "backend.js",
      ])
    })
  })

  // The config check resolves the output directory's real location, but the
  // entries inside it come from the repository too. A write that follows a
  // link at its destination lands wherever the link points.
  describe("symbolic links in the output directory", () => {
    const backendOptions = (projectRoot: string) => ({
      canisterConfig: { name: "backend", didFile: "backend.did" },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
    })

    /** A project, its canister's output directory, and a directory outside it. */
    function createProjectWithOutsideDir() {
      const projectRoot = createTempProject()
      writeDid(projectRoot, "backend.did")
      const canisterOutDir = path.join(projectRoot, "src/declarations/backend")
      fs.mkdirSync(canisterOutDir, { recursive: true })
      const outside = fs.mkdtempSync(
        path.join(os.tmpdir(), "ic-reactor-codegen-outside-")
      )
      tempDirs.push(outside)
      return { projectRoot, canisterOutDir, outside }
    }

    it("replaces a linked index.generated.ts instead of writing through it", async () => {
      const { projectRoot, canisterOutDir, outside } =
        createProjectWithOutsideDir()
      const victim = path.join(outside, "victim.ts")
      fs.writeFileSync(victim, "IRREPLACEABLE")
      const reactorPath = path.join(canisterOutDir, "index.generated.ts")
      fs.symlinkSync(victim, reactorPath)

      const first = await runCanisterPipeline(backendOptions(projectRoot))

      expect(fs.readFileSync(victim, "utf-8")).toBe("IRREPLACEABLE")
      expect(first.error).toBeUndefined()
      expect(fs.lstatSync(reactorPath).isFile()).toBe(true)
      const generated = fs.readFileSync(reactorPath, "utf-8")
      expect(generated).toContain('name: "backend"')

      // Running again replaces the regular files it wrote and leaves no
      // temporary files behind.
      const second = await runCanisterPipeline(backendOptions(projectRoot))

      expect(second.error).toBeUndefined()
      expect(fs.readFileSync(reactorPath, "utf-8")).toBe(generated)
      expect(
        fs
          .readdirSync(canisterOutDir)
          .filter((entry) => entry.includes(".tmp-"))
      ).toEqual([])
    })

    // A file that already holds the generated bytes is left alone, but a link
    // never counts as one, whatever its target holds.
    it("replaces a link whose target already holds the generated bytes", async () => {
      const { projectRoot, canisterOutDir, outside } =
        createProjectWithOutsideDir()
      const first = await runCanisterPipeline(backendOptions(projectRoot))
      expect(first.error).toBeUndefined()

      const linked = [
        "index.generated.ts",
        path.join("declarations", "backend.d.ts"),
      ]
      for (const entry of linked) {
        const entryPath = path.join(canisterOutDir, entry)
        const target = path.join(outside, path.basename(entry))
        fs.copyFileSync(entryPath, target)
        fs.rmSync(entryPath)
        fs.symlinkSync(target, entryPath)
      }

      const second = await runCanisterPipeline(backendOptions(projectRoot))

      expect(second.error).toBeUndefined()
      for (const entry of linked) {
        expect(fs.lstatSync(path.join(canisterOutDir, entry)).isFile()).toBe(
          true
        )
      }
    })

    it("fails instead of creating index.ts through a dangling link", async () => {
      const { projectRoot, canisterOutDir, outside } =
        createProjectWithOutsideDir()
      const linkTarget = path.join(outside, "created.ts")
      const entryPath = path.join(canisterOutDir, "index.ts")
      fs.symlinkSync(linkTarget, entryPath)

      const result = await runCanisterPipeline(backendOptions(projectRoot))

      expect(fs.existsSync(linkTarget)).toBe(false)
      expect(result.success).toBe(false)
      expect(result.error).toContain(
        `Refusing to create ${entryPath} because it is a symbolic link to ${linkTarget}.`
      )
      // index.ts belongs to the user, so the link stays for them to remove.
      expect(fs.readlinkSync(entryPath)).toBe(linkTarget)
    })

    it("does not write the owner marker through a link", async () => {
      const { projectRoot, canisterOutDir, outside } =
        createProjectWithOutsideDir()
      const linkTarget = path.join(outside, "owner")
      const markerPath = path.join(canisterOutDir, ".ic-reactor-owner")
      fs.symlinkSync(linkTarget, markerPath)

      const result = await runCanisterPipeline(backendOptions(projectRoot))

      expect(fs.existsSync(linkTarget)).toBe(false)
      expect(result.error).toBeUndefined()
      expect(fs.lstatSync(markerPath).isFile()).toBe(true)
      expect(fs.readFileSync(markerPath, "utf-8")).toBe("backend\n")
    })

    it("fails instead of backing up a legacy index.ts through a dangling link", async () => {
      const { projectRoot, canisterOutDir, outside } =
        createProjectWithOutsideDir()
      const entryPath = path.join(canisterOutDir, "index.ts")
      fs.writeFileSync(entryPath, LEGACY_BACKEND_INDEX)
      const linkTarget = path.join(outside, "backup.ts")
      fs.symlinkSync(linkTarget, `${entryPath}.bak`)

      const result = await runCanisterPipeline(backendOptions(projectRoot))

      expect(fs.existsSync(linkTarget)).toBe(false)
      expect(result.success).toBe(false)
      expect(result.error).toContain(
        `Refusing to create ${entryPath}.bak because it is a symbolic link to ${linkTarget}.`
      )
      // Migration stops before it replaces a file it could not back up.
      expect(fs.readFileSync(entryPath, "utf-8")).toBe(LEGACY_BACKEND_INDEX)
    })

    it("leaves a linked index.ts that the user owns, and its target, untouched", async () => {
      const { projectRoot, canisterOutDir, outside } =
        createProjectWithOutsideDir()
      const userEntry = path.join(outside, "index.ts")
      fs.writeFileSync(userEntry, "export const custom = true\n")
      const entryPath = path.join(canisterOutDir, "index.ts")
      fs.symlinkSync(userEntry, entryPath)

      const result = await runCanisterPipeline(backendOptions(projectRoot))

      expect(result.success).toBe(true)
      expect(fs.readlinkSync(entryPath)).toBe(userEntry)
      expect(fs.readFileSync(userEntry, "utf-8")).toBe(
        "export const custom = true\n"
      )
      expect(result.files).toEqual(
        expect.arrayContaining([
          expect.objectContaining({ filePath: entryPath, skipped: true }),
        ])
      )
    })

    it("removes its temporary file when replacing a generated file fails", async () => {
      const { projectRoot, canisterOutDir } = createProjectWithOutsideDir()
      // A rename cannot put a file where a directory is.
      fs.mkdirSync(path.join(canisterOutDir, "index.generated.ts"))

      const result = await runCanisterPipeline(backendOptions(projectRoot))

      expect(result.success).toBe(false)
      expect(
        fs
          .readdirSync(canisterOutDir)
          .filter((entry) => entry.includes(".tmp-"))
      ).toEqual([])
    })
  })

  describe("factories", () => {
    const COUNTER_DID = `service : {
  get : () -> (nat) query;
  add : (nat) -> ();
}`

    function createCounterProject() {
      const projectRoot = createTempProject()
      fs.writeFileSync(path.join(projectRoot, "backend.did"), COUNTER_DID)
      return projectRoot
    }

    const counterOptions = (
      projectRoot: string,
      canister: Partial<CanisterConfig> = {}
    ) => ({
      canisterConfig: { name: "backend", didFile: "backend.did", ...canister },
      projectRoot,
      globalConfig: {
        outDir: "src/declarations",
        clientManagerPath: "../../clients",
      },
    })

    const outDirOf = (projectRoot: string) =>
      path.join(projectRoot, "src/declarations/backend")

    /** Every file under `dir` and its bytes, by relative path. */
    function readTree(dir: string) {
      const tree: Record<string, string> = {}
      const visit = (entryPath: string) => {
        if (fs.lstatSync(entryPath).isDirectory()) {
          for (const entry of fs.readdirSync(entryPath)) {
            visit(path.join(entryPath, entry))
          }
        } else {
          tree[path.relative(dir, entryPath)] = fs.readFileSync(
            entryPath,
            "utf-8"
          )
        }
      }
      visit(dir)
      return tree
    }

    it("writes index.factories.generated.ts and a wrapper that re-exports it", async () => {
      const projectRoot = createCounterProject()
      const outDir = outDirOf(projectRoot)

      const result = await runCanisterPipeline(
        counterOptions(projectRoot, { factories: true })
      )

      expect(result.error).toBeUndefined()
      expect(result.warnings).toBeUndefined()
      expect(result.files.map((file) => file.filePath)).toContain(
        path.join(outDir, "index.factories.generated.ts")
      )
      const factories = fs.readFileSync(
        path.join(outDir, "index.factories.generated.ts"),
        "utf-8"
      )
      expect(factories).toContain("Auto-generated by @ic-reactor/codegen")
      expect(factories).toContain(
        "export const getQuery = /* @__PURE__ */ createQuery(backendReactor, {"
      )
      expect(factories).toContain(
        "export const addMutation = /* @__PURE__ */ createMutation(backendReactor, {"
      )
      expect(fs.readFileSync(path.join(outDir, "index.ts"), "utf-8")).toBe(
        generateReactorEntryFile({ factories: true })
      )
    })

    it("writes the same files with factories off as without the option", async () => {
      const omitted = createCounterProject()
      const off = createCounterProject()

      await runCanisterPipeline(counterOptions(omitted))
      await runCanisterPipeline(counterOptions(off, { factories: false }))

      const tree = readTree(outDirOf(omitted))
      expect(readTree(outDirOf(off))).toEqual(tree)
      expect(Object.keys(tree).sort()).toEqual([
        ".ic-reactor-owner",
        "declarations/backend.d.ts",
        "declarations/backend.did",
        "declarations/backend.js",
        "index.generated.ts",
        "index.ts",
      ])
      expect(tree["index.ts"]).toBe(generateReactorEntryFile())
    })

    it("leaves every output untouched when regenerating with nothing changed", async () => {
      const projectRoot = createCounterProject()
      const options = counterOptions(projectRoot, { factories: true })

      await runCanisterPipeline(options)
      const before = statTree(outDirOf(projectRoot))
      expect(before["index.factories.generated.ts"]).toBeDefined()

      const result = await runCanisterPipeline(options)

      expect(result.error).toBeUndefined()
      expect(statTree(outDirOf(projectRoot))).toEqual(before)
    })

    it("follows the .did when a method is added, removed or becomes an update", async () => {
      const projectRoot = createCounterProject()
      const options = counterOptions(projectRoot, { factories: true })
      const factoriesPath = path.join(
        outDirOf(projectRoot),
        "index.factories.generated.ts"
      )
      await runCanisterPipeline(options)

      fs.writeFileSync(
        path.join(projectRoot, "backend.did"),
        `service : {
  get : () -> (nat);
  owner : (nat) -> (opt principal) query;
}`
      )
      const result = await runCanisterPipeline(options)

      expect(result.error).toBeUndefined()
      const factories = fs.readFileSync(factoriesPath, "utf-8")
      expect(factories).toContain(
        "export const getMutation = /* @__PURE__ */ createMutation(backendReactor, {"
      )
      expect(factories).toContain(
        "export const ownerQuery = /* @__PURE__ */ createQueryFactory(backendReactor, {"
      )
      expect(factories).not.toContain("getQuery")
      expect(factories).not.toContain("addMutation")
    })

    it("removes the file and restores the plain wrapper once factories is off", async () => {
      const projectRoot = createCounterProject()
      const outDir = outDirOf(projectRoot)
      await runCanisterPipeline(
        counterOptions(projectRoot, { factories: true })
      )
      expect(
        fs.existsSync(path.join(outDir, "index.factories.generated.ts"))
      ).toBe(true)
      expect(fs.readFileSync(path.join(outDir, "index.ts"), "utf-8")).toBe(
        generateReactorEntryFile({ factories: true })
      )

      const result = await runCanisterPipeline(counterOptions(projectRoot))

      expect(result.error).toBeUndefined()
      expect(result.warnings).toBeUndefined()
      expect(
        fs.existsSync(path.join(outDir, "index.factories.generated.ts"))
      ).toBe(false)
      expect(fs.readFileSync(path.join(outDir, "index.ts"), "utf-8")).toBe(
        generateReactorEntryFile()
      )
    })

    it("leaves an index.factories.generated.ts it did not write", async () => {
      const projectRoot = createCounterProject()
      const outDir = outDirOf(projectRoot)
      fs.mkdirSync(outDir, { recursive: true })
      const own = "export const mine = 1\n"
      fs.writeFileSync(path.join(outDir, "index.factories.generated.ts"), own)

      const result = await runCanisterPipeline(counterOptions(projectRoot))

      expect(result.error).toBeUndefined()
      expect(
        fs.readFileSync(
          path.join(outDir, "index.factories.generated.ts"),
          "utf-8"
        )
      ).toBe(own)
    })

    it("leaves the factories file alone when reactor generation is disabled", async () => {
      const projectRoot = createCounterProject()
      const factoriesPath = path.join(
        outDirOf(projectRoot),
        "index.factories.generated.ts"
      )
      await runCanisterPipeline(
        counterOptions(projectRoot, { factories: true })
      )
      const before = fs.readFileSync(factoriesPath, "utf-8")

      const result = await runCanisterPipeline({
        ...counterOptions(projectRoot),
        generateReactor: false,
      })

      expect(result.error).toBeUndefined()
      expect(fs.readFileSync(factoriesPath, "utf-8")).toBe(before)
    })

    it("warns when an index.ts of the user's own does not re-export the factories", async () => {
      const projectRoot = createCounterProject()
      const outDir = outDirOf(projectRoot)
      fs.mkdirSync(outDir, { recursive: true })
      const own = 'export * from "./index.generated"\nexport const mine = 1\n'
      fs.writeFileSync(path.join(outDir, "index.ts"), own)

      const result = await runCanisterPipeline(
        counterOptions(projectRoot, { factories: true })
      )

      expect(result.success).toBe(true)
      expect(fs.readFileSync(path.join(outDir, "index.ts"), "utf-8")).toBe(own)
      expect(result.warnings).toEqual([
        expect.stringContaining(
          'Add `export * from "./index.factories.generated"` to it'
        ),
      ])
      expect(result.warnings?.[0]).toContain(
        path.join("src/declarations/backend", "index.ts")
      )

      fs.appendFileSync(
        path.join(outDir, "index.ts"),
        'export * from "./index.factories.generated"\n'
      )
      const again = await runCanisterPipeline(
        counterOptions(projectRoot, { factories: true })
      )
      expect(again.warnings).toBeUndefined()
    })

    it("warns when an index.ts of the user's own still imports the removed factories", async () => {
      const projectRoot = createCounterProject()
      const outDir = outDirOf(projectRoot)
      fs.mkdirSync(outDir, { recursive: true })
      fs.writeFileSync(
        path.join(outDir, "index.ts"),
        'export * from "./index.generated"\nexport * from "./index.factories.generated"\nexport const mine = 1\n'
      )
      await runCanisterPipeline(
        counterOptions(projectRoot, { factories: true })
      )

      const result = await runCanisterPipeline(counterOptions(projectRoot))

      expect(result.success).toBe(true)
      expect(result.warnings).toEqual([
        expect.stringContaining(
          "imports ./index.factories.generated, which codegen writes only while the canister sets factories: true"
        ),
      ])
    })

    it("refuses factories for a core target", async () => {
      const projectRoot = createCounterProject()

      const result = await runCanisterPipeline(
        counterOptions(projectRoot, { factories: true, target: "core" })
      )

      expect(result.success).toBe(false)
      expect(result.error).toContain('need target "react"')
      expect(fs.existsSync(outDirOf(projectRoot))).toBe(false)
    })

    it("refuses a factories value that is not a boolean", async () => {
      const projectRoot = createCounterProject()

      const result = await runCanisterPipeline(
        counterOptions(projectRoot, {
          factories: "false" as unknown as boolean,
        })
      )

      expect(result.success).toBe(false)
      expect(result.error).toContain(
        'Invalid factories "false" for canister "backend": must be true or false.'
      )
    })

    it("formats the factories file with the project's Prettier config", async () => {
      const projectRoot = createCounterProject()
      fs.mkdirSync(path.join(projectRoot, "node_modules"))
      fs.symlinkSync(
        path.dirname(
          createRequire(import.meta.url).resolve("prettier/package.json")
        ),
        path.join(projectRoot, "node_modules", "prettier"),
        "junction"
      )
      fs.writeFileSync(
        path.join(projectRoot, ".prettierrc"),
        JSON.stringify({ semi: true, singleQuote: true })
      )
      const outDir = outDirOf(projectRoot)

      const result = await runCanisterPipeline(
        counterOptions(projectRoot, { factories: true })
      )

      expect(result.error).toBeUndefined()
      expect(
        fs.readFileSync(
          path.join(outDir, "index.factories.generated.ts"),
          "utf-8"
        )
      ).toContain("import { backendReactor } from './index.generated';")
      expect(fs.readFileSync(path.join(outDir, "index.ts"), "utf-8")).toContain(
        "export * from './index.factories.generated';"
      )

      // The formatted wrapper is still recognised as the template, so turning
      // factories off replaces it.
      await runCanisterPipeline(counterOptions(projectRoot))
      expect(
        fs.readFileSync(path.join(outDir, "index.ts"), "utf-8")
      ).not.toContain("index.factories.generated")
    })
  })
})
