import { Plugin } from "vite"
import fs from "fs"
import path from "path"
import { generate } from "@icp-sdk/bindgen/core"
import { IcReactorPluginOptions } from "./index"

function toPascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("")
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

function extractMethods(didContent: string) {
  // Simple regex to extract method names and types
  // Looks for: name : (...) -> (...) [query]
  const methodRegex =
    /([a-zA-Z0-9_]+)\s*:\s*(?:func\s*)?\(([\s\S]*?)\)\s*->\s*\(([\s\S]*?)\)\s*(query|composite_query)?/g

  const queries: string[] = []
  const mutations: string[] = []

  let match
  while ((match = methodRegex.exec(didContent)) !== null) {
    const name = match[1]
    const isQuery = !!match[4]
    if (isQuery) {
      queries.push(name)
    } else {
      mutations.push(name)
    }
  }

  return { queries, mutations }
}

function generateAdvancedReactorFile(
  canisterName: string,
  useDisplayReactor: boolean,
  clientManagerPath: string,
  didContent: string
): string {
  const pascalName = toPascalCase(canisterName)
  const camelName = toCamelCase(canisterName)
  const reactorType = useDisplayReactor ? "DisplayReactor" : "Reactor"

  const { queries, mutations } = extractMethods(didContent)

  const queryHooks = queries.map((method) => {
    const pascalMethod = toPascalCase(method)
    return `
export const use${pascalMethod}Query = (
  args: Parameters<${pascalName}Service["${method}"]>,
  options?: any
) =>
  createQuery(${camelName}Reactor, {
    functionName: "${method}",
    args,
  }).useQuery(options)
`
  })

  const mutationHooks = mutations.map((method) => {
    const pascalMethod = toPascalCase(method)
    return `
export const use${pascalMethod}Mutation = (
  options?: any
) =>
  createMutation(${camelName}Reactor, {
    functionName: "${method}",
    ...options,
  }).useMutation(options)
`
  })

  return `/**
 * AUTO-GENERATED BY @ic-reactor/vite-plugin
 * DO NOT EDIT MANUALLY
 *
 * Canister: ${canisterName}
 * Generated: ${new Date().toISOString()}
 *
 * This file provides type-safe React hooks for interacting with the
 * ${canisterName} canister using ic-reactor.
 */

import {
  ${reactorType},
  createQuery,
  createMutation,
} from "@ic-reactor/react"

// ═══════════════════════════════════════════════════════════════════════════
// USER-PROVIDED CLIENT MANAGER
// ═══════════════════════════════════════════════════════════════════════════
import { clientManager } from "${clientManagerPath}"

// Import generated declarations from @icp-sdk/bindgen
import {
  idlFactory,
  type _SERVICE,
} from "./declarations/${canisterName}.did"

// ═══════════════════════════════════════════════════════════════════════════
// REACTOR INSTANCE
// ═══════════════════════════════════════════════════════════════════════════
type ${pascalName}Service = _SERVICE

/**
 * ${pascalName} Reactor with ${useDisplayReactor ? "Display" : "Candid"} type transformations.
 * ${useDisplayReactor ? "Automatically converts bigint → string, Principal → string, etc." : "Uses raw Candid types."}
 */
export const ${camelName}Reactor = new ${reactorType}<${pascalName}Service>({
  clientManager,
  idlFactory,
  name: "${canisterName}",
})

// ═══════════════════════════════════════════════════════════════════════════
// QUERY HOOKS
// ═══════════════════════════════════════════════════════════════════════════
${queryHooks.join("")}

// ═══════════════════════════════════════════════════════════════════════════
// MUTATION HOOKS
// ═══════════════════════════════════════════════════════════════════════════
${mutationHooks.join("")}

// ═══════════════════════════════════════════════════════════════════════════
// RE-EXPORTS
// ═══════════════════════════════════════════════════════════════════════════
export { idlFactory }
export type { ${pascalName}Service }
`
}

export function icReactorAdvancedPlugin(
  options: IcReactorPluginOptions
): Plugin {
  const baseOutDir = options.outDir ?? "./src/canisters"

  return {
    name: "ic-reactor-advanced-plugin",
    async buildStart() {
      for (const canister of options.canisters) {
        const outDir = canister.outDir ?? path.join(baseOutDir, canister.name)

        if (!fs.existsSync(outDir)) {
          fs.mkdirSync(outDir, { recursive: true })
        }

        console.log(
          `[ic-reactor] Generating advanced hooks for ${canister.name} from ${canister.didFile}`
        )

        try {
          await generate({
            didFile: canister.didFile,
            outDir,
            output: {
              actor: {
                disabled: true,
              },
              force: true,
            },
          })

          console.log(
            `[ic-reactor] Declarations generated at ${path.join(
              outDir,
              "declarations"
            )}`
          )
        } catch (error) {
          console.error(`[ic-reactor] Failed to generate declarations:`, error)
          continue
        }

        const clientManagerPath =
          canister.clientManagerPath ??
          options.clientManagerPath ??
          "../../lib/client"

        let didContent = ""
        try {
          didContent = fs.readFileSync(canister.didFile, "utf-8")
        } catch (e) {
          console.warn(
            `[ic-reactor] Could not read DID file at ${canister.didFile}, skipping hook generation.`
          )
          continue
        }

        const reactorContent = generateAdvancedReactorFile(
          canister.name,
          canister.useDisplayReactor ?? true,
          clientManagerPath,
          didContent
        )

        const reactorPath = path.join(outDir, "index.ts")
        fs.writeFileSync(reactorPath, reactorContent)

        console.log(
          `[ic-reactor] Advanced reactor hooks generated at ${reactorPath}`
        )
      }
    },
    handleHotUpdate({ file, server }) {
      if (file.endsWith(".did")) {
        const canister = options.canisters.find(
          (c) => path.resolve(c.didFile) === file
        )
        if (canister) {
          console.log(
            `[ic-reactor] Detected change in ${file}, regenerating...`
          )
          server.restart()
        }
      }
    },
  }
}
