import { Plugin } from "vite"
import fs from "fs"
import path from "path"
import { generate } from "@icp-sdk/bindgen/core"
import { IcReactorPluginOptions } from "./index"

function toPascalCase(str: string): string {
  return str
    .split(/[-_]/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("")
}

function toCamelCase(str: string): string {
  const pascal = toPascalCase(str)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

function generateAdvancedReactorFile(
  canisterName: string,
  useDisplayReactor: boolean,
  clientManagerPath: string
): string {
  const pascalName = toPascalCase(canisterName)
  const camelName = toCamelCase(canisterName)
  const reactorType = useDisplayReactor ? "DisplayReactor" : "Reactor"

  return `/**
 * AUTO-GENERATED BY @ic-reactor/vite-plugin
 *
 * Canister: ${canisterName}
 * Generated: ${new Date().toISOString()}
 *
 * This file provides advanced type-safe React hooks for interacting with the
 * ${canisterName} canister using ic-reactor.
 */

import {
  ${reactorType},
  createActorHooks,
  type ReactorParameters,
} from "@ic-reactor/react"

// ═══════════════════════════════════════════════════════════════════════════
// USER-PROVIDED CLIENT MANAGER
// ═══════════════════════════════════════════════════════════════════════════
import { clientManager } from "${clientManagerPath}"

// Import generated declarations from @icp-sdk/bindgen
import {
  idlFactory,
  type _SERVICE,
} from "./declarations/${canisterName}.did"

// ═══════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════

export type ${pascalName}Reactor = ${reactorType}<_SERVICE>

export type Create${pascalName}ReactorOptions = Partial<ReactorParameters>

// ═══════════════════════════════════════════════════════════════════════════
// FACTORIES
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Creates a ${reactorType} instance for the ${canisterName} canister.
 *
 * @param options - partial ReactorParameters to override defaults
 * @returns a new ${reactorType} instance
 */
export function create${pascalName}Reactor(
  options: Create${pascalName}ReactorOptions = {}
): ${pascalName}Reactor {
  return new ${reactorType}<_SERVICE>({
    clientManager,
    idlFactory,
    name: "${canisterName}",
    ...options,
  })
}

/**
 * Creates a full set of React hooks for a ${reactorType} instance.
 *
 * @param reactor - the reactor instance to generate hooks for
 * @returns query, mutation, and subscription hooks
 */
export function create${pascalName}Hooks(reactor: ${pascalName}Reactor) {
  return createActorHooks(reactor)
}

// ═══════════════════════════════════════════════════════════════════════════
// DEFAULT INSTANCE & HOOKS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Default ${reactorType} instance with standard configuration.
 */
export const ${camelName}Reactor = create${pascalName}Reactor()

/**
 * Pre-generated hooks using the default ${camelName}Reactor instance.
 * These are ready to use in your React components.
 */
const defaultHooks = create${pascalName}Hooks(${camelName}Reactor)

export const {
  useActorQuery: use${pascalName}Query,
  useActorSuspenseQuery: use${pascalName}SuspenseQuery,
  useActorInfiniteQuery: use${pascalName}InfiniteQuery,
  useActorSuspenseInfiniteQuery: use${pascalName}SuspenseInfiniteQuery,
  useActorMutation: use${pascalName}Mutation,
  useActorMethod: use${pascalName}Method,
} = defaultHooks

// ═══════════════════════════════════════════════════════════════════════════
// RE-EXPORTS
// ═══════════════════════════════════════════════════════════════════════════

export { idlFactory }
export type { _SERVICE as ${pascalName}Service }
`
}

export function icReactorAdvancedPlugin(
  options: IcReactorPluginOptions
): Plugin {
  const baseOutDir = options.outDir ?? "./src/canisters"

  return {
    name: "ic-reactor-advanced-plugin",
    async buildStart() {
      for (const canister of options.canisters) {
        const outDir = canister.outDir ?? path.join(baseOutDir, canister.name)
        // Pass outDir directly to generate; bindgen appends "declarations"
        // Ensure parent dir exists
        if (!fs.existsSync(outDir)) {
          fs.mkdirSync(outDir, { recursive: true })
        }

        console.log(
          `[ic-reactor] Generating advanced hooks for ${canister.name} from ${canister.didFile}`
        )

        try {
          // Generate declarations using @icp-sdk/bindgen
          await generate({
            didFile: canister.didFile,
            outDir, // bindgen appends "declarations"
            output: {
              actor: {
                disabled: true,
              },
            },
          })

          console.log(
            `[ic-reactor] Declarations generated at ${path.join(
              outDir,
              "declarations"
            )}`
          )
        } catch (error) {
          console.error(`[ic-reactor] Failed to generate declarations:`, error)
          continue
        }

        // Generate the advanced reactor file
        const clientManagerPath =
          canister.clientManagerPath ??
          options.clientManagerPath ??
          "../../lib/client"

        const reactorContent = generateAdvancedReactorFile(
          canister.name,
          canister.useDisplayReactor ?? true,
          clientManagerPath
        )

        const reactorPath = path.join(outDir, "index.ts")
        fs.writeFileSync(reactorPath, reactorContent)

        console.log(
          `[ic-reactor] Advanced reactor hooks generated at ${reactorPath}`
        )
      }
    },
    handleHotUpdate({ file, server }) {
      if (file.endsWith(".did")) {
        const canister = options.canisters.find(
          (c) => path.resolve(c.didFile) === file
        )
        if (canister) {
          console.log(
            `[ic-reactor] Detected change in ${file}, regenerating...`
          )
          server.restart()
        }
      }
    },
  }
}
