/**
 * Ledger Reactor
 *
 * Auto-generated by @ic-reactor/cli
 * This file provides the shared reactor instance for the ledger canister.
 *
 * You can customize this file to add global configuration.
 */

import {
  DisplayReactor,
  createActorHooks,
  createAuthHooks,
} from "@ic-reactor/react"
import { clientManager } from "../../client"
import { idlFactory, type _SERVICE } from "./declarations/icrc1.did"

// ═══════════════════════════════════════════════════════════════════════════
// SERVICE TYPE
// ═══════════════════════════════════════════════════════════════════════════

export type LedgerService = _SERVICE

// ═══════════════════════════════════════════════════════════════════════════
// REACTOR INSTANCE
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Ledger Reactor with Display type transformations.
 * Automatically converts bigint → string, Principal → string, etc.
 */
export const ledgerReactor = new DisplayReactor<LedgerService>({
  clientManager,
  idlFactory,
  name: "ledger",
})

// ═══════════════════════════════════════════════════════════════════════════
// BASE HOOKS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Base actor hooks - use these directly or import method-specific hooks.
 */
export const {
  useActorQuery,
  useActorMutation,
  useActorSuspenseQuery,
  useActorInfiniteQuery,
  useActorSuspenseInfiniteQuery,
  useActorMethod,
} = createActorHooks(ledgerReactor)

/**
 * Auth hooks for the client manager.
 */
export const { useAuth, useAgentState, useUserPrincipal } =
  createAuthHooks(clientManager)

// ═══════════════════════════════════════════════════════════════════════════
// RE-EXPORTS
// ═══════════════════════════════════════════════════════════════════════════

export { idlFactory }
