/**
 * Ledger Reactor
 *
 * Auto-generated by @ic-reactor/cli
 * This file provides the shared reactor instance for the ledger canister.
 *
 * You can customize this file to add global configuration.
 */

import { DisplayReactor, createActorHooks } from "@ic-reactor/react"
import { clientManager } from "../../lib/client"
import { idlFactory, type _SERVICE } from "./declarations/icrc1.did"

// ═══════════════════════════════════════════════════════════════════════════
// SERVICE TYPE
// ═══════════════════════════════════════════════════════════════════════════

export type LedgerService = _SERVICE

// ═══════════════════════════════════════════════════════════════════════════
// REACTOR INSTANCE
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Ledger Reactor with Display type transformations.
 * Automatically converts bigint → string, Principal → string, etc.
 */
export const ledgerReactor = new DisplayReactor<LedgerService>({
  clientManager,
  idlFactory,
  name: "ledger",
})

// ═══════════════════════════════════════════════════════════════════════════
// ACTOR HOOKS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Actor hooks for ledger - use these directly or import method-specific hooks.
 */
export const {
  useActorQuery,
  useActorMutation,
  useActorSuspenseQuery,
  useActorInfiniteQuery,
  useActorSuspenseInfiniteQuery,
  useActorMethod,
} = createActorHooks(ledgerReactor)
