import { createMutation, createQuery } from "@ic-reactor/react"
import { backendReactor } from "./index.generated"

/**
 * Backend Query and Mutation Factories
 *
 * Auto-generated by @ic-reactor/codegen — do not edit.
 * This file is overwritten whenever generation runs.
 *
 * One export per method of the service, bound to `backendReactor`:
 * `createQuery` for a query method that takes no arguments,
 * `createQueryFactory` for a query method that takes arguments, and
 * `createMutation` for an update or oneway method. Pass per-call options to
 * `useQuery()` and `useMutation()`, and define a factory with its own
 * config in the stable `index.ts` wrapper (or an adjacent module).
 */

/** "add": update. */
export const addMutation = createMutation(backendReactor, {
  functionName: "add",
})

/** "get": query, no arguments. */
export const getQuery = createQuery(backendReactor, {
  functionName: "get",
})

/** "inc": update. */
export const incMutation = createMutation(backendReactor, {
  functionName: "inc",
})
