import { ClientManager } from "@ic-reactor/react"
import { QueryClient } from "@tanstack/react-query"

export const queryClient = new QueryClient()

/**
 * IC Reactor Client Manager
 *
 * Auto-generated by @ic-reactor/codegen
 */
export const clientManager = new ClientManager({
  queryClient,
})
