[package]
name = "didjs"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
candid_parser = "0.1"
wasm-bindgen = { version = "0.2", optional = true }

[features]
default = ["js"]
js = ["dep:wasm-bindgen"]
