/**
 * @ic-reactor/start — Scaffold file templates
 *
 * Pure string-template functions for the default V0 generated app. These are
 * kept separate from the filesystem-writing `createApp` so they can be unit
 * tested without touching disk.
 *
 * Conventions for the default layout:
 *
 * ```text
 * <app>/
 *   icp.yaml
 *   ic-reactor.json
 *   backend/
 *     canister.yaml
 *     main.mo
 *     backend.did
 *   frontend/
 *     canister.yaml
 *     package.json
 *     vite.config.ts
 *     tsconfig.json
 *     index.html
 *     src/
 *       main.tsx
 *       styles.css
 *       routeTree.gen.ts        (committed; regenerated by TanStack Router)
 *       routes/__root.tsx
 *       routes/index.tsx
 *       lib/client.ts
 *       lib/auth.ts
 * ```
 *
 * Canister IDs are intentionally never baked into templates. They resolve at
 * runtime via `icp-cli` + the `ic_env` cookie injected by
 * `@ic-reactor/vite-plugin`.
 */

export interface TemplateContext {
  /** npm package name of the app, e.g. "my-app". */
  appName: string
}

const ICP_YAML_SCHEMA_REF =
  "https://github.com/dfinity/icp-cli/raw/refs/tags/v0.1.0-beta.2/docs/schemas/icp-yaml-schema.json"
const CANISTER_YAML_SCHEMA_REF =
  "https://github.com/dfinity/icp-cli/raw/refs/tags/v0.1.0-beta.2/docs/schemas/canister-yaml-schema.json"

/** Root `icp.yaml` — managed local network with II enabled. */
export function icpYamlTemplate(): string {
  return `# yaml-language-server: $schema=${ICP_YAML_SCHEMA_REF}

# ICP CLI project configuration for an @ic-reactor/start app.
# Start a local replica:   icp network start -d
# Deploy all canisters:    icp deploy
# Sync frontend assets:    icp sync
# Deploy to mainnet:       icp deploy -e ic

canisters:
  - backend
  - frontend

networks:
  - name: local
    mode: managed
    ii: true
    gateway:
      port: 8000
`
}

/** `backend/canister.yaml` — Motoko for V0 starter simplicity. */
export function backendCanisterYamlTemplate(): string {
  return `# yaml-language-server: $schema=${CANISTER_YAML_SCHEMA_REF}

name: backend

recipe:
  type: "@dfinity/motoko@v4.1.0"
  configuration:
    main: main.mo
    args: --incremental-gc
    candid: backend.did
`
}

/** `frontend/canister.yaml` — builds the Vite app and syncs `dist`. */
export function frontendCanisterYamlTemplate(): string {
  return `# yaml-language-server: $schema=${CANISTER_YAML_SCHEMA_REF}

name: frontend

recipe:
  type: "@ic-reactor/frontend-asset@v1"
  configuration:
    build: pnpm install --frozen-lockfile && pnpm build
    output: dist
`
}

/** `backend/main.mo` — a tiny counter canister that demonstrates query/update. */
export function backendMainMoTemplate(): string {
  return `import Array "mo:base/Array";
import Principal "mo:base/Principal";

persistent actor {
  // V0 starter backend: a simple counter.
  // Replace this with your own canister logic. Run "icp deploy" to publish.

  stable var count : Nat = 0;
  stable var owners : [Principal] = [];

  public query func get_count() : async Nat {
    return count;
  };

  public shared (msg) func increment() : async Nat {
    count += 1;
    owners := Array.append(owners, [msg.caller]);
    return count;
  };

  public shared (msg) func reset() : async Nat {
    count := 0;
    return count;
  };

  public query func who_called() : async [Principal] {
    return owners;
  };
};
`
}

/** `backend/backend.did` — Candid interface for the starter counter canister. */
export function backendDidTemplate(): string {
  return `service : {
  get_count: () -> (nat) query;
  increment: () -> (nat);
  reset: () -> (nat);
  who_called: () -> (vec principal) query;
}
`
}

/**
 * Root `ic-reactor.json` — configures the backend canister with its `.did`.
 * Consumed by the CLI; the Vite plugin reads config from vite.config.ts.
 */
export function icReactorJsonTemplate(): string {
  return (
    JSON.stringify(
      {
        $schema: "./node_modules/@ic-reactor/codegen/schema.json",
        outDir: "frontend/src/declarations",
        clientManagerPath: "../../lib/client",
        target: "react",
        canisters: {
          backend: {
            name: "backend",
            didFile: "./backend/backend.did",
            clientManagerPath: "../../lib/client",
          },
        },
      },
      null,
      2
    ) + "\n"
  )
}

/** `frontend/package.json` — dependencies for the generated app. */
export function frontendPackageJsonTemplate(ctx: TemplateContext): string {
  return (
    JSON.stringify(
      {
        name: ctx.appName,
        private: true,
        version: "0.0.0",
        type: "module",
        scripts: {
          dev: "vite",
          build: "tsc && vite build",
          preview: "vite preview",
          typecheck: "tsc --noEmit",
          "deploy:local": "icp deploy",
          "deploy:ic": "icp deploy -e ic",
          network: "icp network start -d",
          sync: "icp sync",
        },
        dependencies: {
          "@ic-reactor/react": "^3.6.0",
          "@icp-sdk/auth": "^7.1.0",
          "@icp-sdk/core": "^5.4.0",
          "@tanstack/react-query": "^5.90.0",
          "@tanstack/react-query-devtools": "^5.91.0",
          "@tanstack/react-router": "^1.144.0",
          react: "^19.2.0",
          "react-dom": "^19.2.0",
        },
        devDependencies: {
          "@ic-reactor/start": "latest",
          "@ic-reactor/vite-plugin": "^0.11.1",
          "@tanstack/router-plugin": "^1.145.0",
          "@types/react": "^19.2.0",
          "@types/react-dom": "^19.2.0",
          "@vitejs/plugin-react": "^6.0.0",
          typescript: "^6.0.0",
          vite: "^8.0.0",
        },
      },
      null,
      2
    ) + "\n"
  )
}

/** `frontend/vite.config.ts` — uses the icReactorStart preset. */
export function frontendViteConfigTemplate(): string {
  return `import { defineConfig } from "vite"
import react from "@vitejs/plugin-react"
import { icReactorStart } from "@ic-reactor/start/plugin/vite"

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    ...icReactorStart({
      // Canister IDs are resolved at runtime via icp-cli + the ic_env cookie.
      // Do NOT put canister IDs in a .env file.
      canisters: {
        backend: { didFile: "../backend/backend.did" },
      },
    }),
    react(),
  ],
})
`
}

/** `frontend/tsconfig.json` — strict TS for the app. */
export function frontendTsconfigTemplate(): string {
  return (
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          useDefineForClassFields: true,
          lib: ["ES2022", "DOM", "DOM.Iterable"],
          module: "ESNext",
          skipLibCheck: true,
          moduleResolution: "bundler",
          allowImportingTsExtensions: true,
          resolveJsonModule: true,
          isolatedModules: true,
          noEmit: true,
          jsx: "react-jsx",
          strict: true,
          noUnusedLocals: true,
          noUnusedParameters: true,
          noFallthroughCasesInSwitch: true,
        },
        include: ["src"],
      },
      null,
      2
    ) + "\n"
  )
}

/** `frontend/index.html`. */
export function frontendIndexHtmlTemplate(ctx: TemplateContext): string {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${ctx.appName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`
}

/** `frontend/src/main.tsx` — TanStack Router + QueryClient + IC Reactor bootstrap. */
export function frontendMainTsxTemplate(): string {
  return `import { StrictMode } from "react"
import ReactDOM from "react-dom/client"
import { RouterProvider, createRouter } from "@tanstack/react-router"
import { QueryClientProvider } from "@tanstack/react-query"

import { queryClient } from "./lib/client"
import { routeTree } from "./routeTree.gen"
import "./styles.css"

const router = createRouter({
  routeTree,
  defaultPreload: "intent",
  defaultPreloadStaleTime: 0,
})

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById("root")!
ReactDOM.createRoot(rootElement).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>
)
`
}

/** `frontend/src/styles.css` — minimal styles. */
export function frontendStylesCssTemplate(): string {
  return `:root {
  font-family: system-ui, Avenir, Helvetica, Arial, sans-serif;
  color-scheme: light dark;
}

body {
  margin: 0;
  min-height: 100vh;
  display: flex;
  place-items: center;
  background: #0b0d12;
  color: #e7e9ee;
}

main {
  width: 100%;
  max-width: 720px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

button {
  border-radius: 8px;
  border: 1px solid #2a2f3a;
  background: #1b9e55;
  color: #fff;
  padding: 0.6rem 1.2rem;
  font-size: 1rem;
  font-weight: 600;
  cursor: pointer;
}

button.secondary {
  background: transparent;
  color: #e7e9ee;
}
`
}

/**
 * `frontend/src/routeTree.gen.ts` — committed seed so `tsc` passes before the
 * TanStack Router plugin runs. Regenerated on dev/build by the router plugin.
 */
export function frontendRouteTreeGenTemplate(): string {
  return `/* eslint-disable */
// @ts-nocheck

// This file is automatically generated by TanStack Router.
// Do not edit by hand — it is regenerated on "vite dev" / "vite build".
// Run "pnpm dev" once to populate it from src/routes.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as IndexRouteImport } from "./routes/index"

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export const routeTree = rootRouteImport.addChildren({
  IndexRoute,
} as any)
`
}

/** `frontend/src/routes/__root.tsx`. */
export function frontendRootRouteTemplate(): string {
  return `import { createRootRoute, Outlet } from "@tanstack/react-router"

export const Route = createRootRoute({
  component: RootComponent,
})

function RootComponent() {
  return (
    <main>
      <Outlet />
    </main>
  )
}
`
}

/** `frontend/src/routes/index.tsx` — home route with a sample backend query/update + II login. */
export function frontendIndexRouteTemplate(): string {
  return `import { createFileRoute } from "@tanstack/react-router"
import { useBackendQuery, useBackendMutation } from "../declarations/backend"
import { useAuth } from "../lib/auth"

export const Route = createFileRoute("/")({
  component: HomeComponent,
})

function HomeComponent() {
  const { isAuthenticated, login, logout, principal } = useAuth()
  const { data: count } = useBackendQuery({
    functionName: "get_count",
  })
  const increment = useBackendMutation({
    functionName: "increment",
  })
  const reset = useBackendMutation({
    functionName: "reset",
  })

  return (
    <>
      <h1>IC Reactor Start</h1>
      <p>A fully on-chain React app on the Internet Computer.</p>

      <p>
        {isAuthenticated ? (
          <>
            <span>Authenticated as {principal?.toText()}</span>{" "}
            <button className="secondary" onClick={() => logout()}>
              Logout
            </button>
          </>
        ) : (
          <button className="secondary" onClick={() => login()}>
            Login with Internet Identity
          </button>
        )}
      </p>

      <p>Backend counter: <strong>{count?.toString() ?? "…"}</strong></p>

      <p>
        <button
          onClick={() => increment.mutate({ args: [] })}
          disabled={increment.isPending}
        >
          Increment
        </button>{" "}
        <button
          className="secondary"
          onClick={() => reset.mutate({ args: [] })}
          disabled={reset.isPending}
        >
          Reset
        </button>
      </p>
    </>
  )
}
`
}

/** `frontend/src/lib/client.ts` — exports queryClient + clientManager. */
export function frontendClientTsTemplate(): string {
  return `import { ClientManager } from "@ic-reactor/react"
import { QueryClient } from "@tanstack/react-query"

export const queryClient = new QueryClient()

export const clientManager = new ClientManager({
  queryClient,
})
`
}

/** `frontend/src/lib/auth.ts` — AuthenticationManager + auth hooks (II). */
export function frontendAuthTsTemplate(): string {
  return `import { AuthenticationManager, createAuthHooks } from "@ic-reactor/react"
import { clientManager } from "./client"

export const authentication = new AuthenticationManager({
  clientManager,
})

export const { useAuth, useAgentState, useUserPrincipal } =
  createAuthHooks(authentication)
`
}

/** `.gitignore` for the generated app. */
export function gitignoreTemplate(): string {
  return `node_modules
dist
.dfx
.icp
.mops
*.tsbuildinfo
.env
.env.local
`
}

/** `README.md` for the generated app. */
export function readmeTemplate(ctx: TemplateContext): string {
  return `# ${ctx.appName}

An [IC Reactor Start](https://github.com/B3Pay/ic-reactor) app — a client-rendered,
fully on-chain React frontend for the Internet Computer.

## Quick start

\`\`\`bash
icp network start -d   # start a local replica with Internet Identity
icp deploy             # deploy backend + frontend canisters
pnpm dev               # start Vite (resolves canister IDs via ic_env)
\`\`\`

Open the URL Vite prints. Canister IDs are resolved at runtime through
\`icp-cli\` and the \`ic_env\` cookie — there is no \`.env\` file.

## Deploy to mainnet

\`\`\`bash
icp deploy -e ic
\`\`\`

## Layout

- \`backend/\` — Motoko canister (\`main.mo\`, \`backend.did\`, \`canister.yaml\`).
- \`frontend/\` — React + TanStack Router app deployed to an ICP asset canister.
- \`icp.yaml\` — \`icp-cli\` project config (canisters + local network).
- \`ic-reactor.json\` — Candid codegen config.

## Notes

V0 is CSR/static only. SSR, server functions, and on-chain SEO rendering are
on the roadmap — see the IC Reactor Start plan.
`
}

/**
 * The complete ordered list of files the scaffold writes, as
 * `{ relativePath, content }` pairs. Keeping this declarative makes the
 * filesystem writer trivial and the scaffold test a simple assertion over the
 * list.
 */
export interface ScaffoldFile {
  relativePath: string
  content: string
}

/**
 * Build the full set of files for a new app. `appName` is validated by the
 * caller (`createApp`); templates only substitute it where needed.
 */
export function buildScaffoldFiles(ctx: TemplateContext): ScaffoldFile[] {
  return [
    { relativePath: "icp.yaml", content: icpYamlTemplate() },
    { relativePath: "ic-reactor.json", content: icReactorJsonTemplate() },
    { relativePath: ".gitignore", content: gitignoreTemplate() },
    { relativePath: "README.md", content: readmeTemplate(ctx) },
    {
      relativePath: "backend/canister.yaml",
      content: backendCanisterYamlTemplate(),
    },
    { relativePath: "backend/main.mo", content: backendMainMoTemplate() },
    { relativePath: "backend/backend.did", content: backendDidTemplate() },
    {
      relativePath: "frontend/canister.yaml",
      content: frontendCanisterYamlTemplate(),
    },
    {
      relativePath: "frontend/package.json",
      content: frontendPackageJsonTemplate(ctx),
    },
    {
      relativePath: "frontend/vite.config.ts",
      content: frontendViteConfigTemplate(),
    },
    {
      relativePath: "frontend/tsconfig.json",
      content: frontendTsconfigTemplate(),
    },
    {
      relativePath: "frontend/index.html",
      content: frontendIndexHtmlTemplate(ctx),
    },
    {
      relativePath: "frontend/src/main.tsx",
      content: frontendMainTsxTemplate(),
    },
    {
      relativePath: "frontend/src/styles.css",
      content: frontendStylesCssTemplate(),
    },
    {
      relativePath: "frontend/src/routeTree.gen.ts",
      content: frontendRouteTreeGenTemplate(),
    },
    {
      relativePath: "frontend/src/routes/__root.tsx",
      content: frontendRootRouteTemplate(),
    },
    {
      relativePath: "frontend/src/routes/index.tsx",
      content: frontendIndexRouteTemplate(),
    },
    {
      relativePath: "frontend/src/lib/client.ts",
      content: frontendClientTsTemplate(),
    },
    {
      relativePath: "frontend/src/lib/auth.ts",
      content: frontendAuthTsTemplate(),
    },
  ]
}
