// Generated by candid-core-ts from a candid-core Contract. Do not edit.
import * as $ from "@candid-core/schema";

type $Account = { owner: $.Principal; subaccount: $Subaccount | null };
const $Account: $.Schema<$Account> = $.c.rec(() => $.c.record({ owner: $.c.principal, subaccount: $.c.opt($Subaccount) }));
export { $Account as Account };

type $BlockIndex = bigint;
const $BlockIndex: $.Schema<$BlockIndex> = $.c.rec(() => $.c.nat);
export { $BlockIndex as BlockIndex };

/** Number of nanoseconds between two [Timestamp]s. */
type $Duration = bigint;
/** Number of nanoseconds between two [Timestamp]s. */
const $Duration: $.Schema<$Duration> = $.c.rec(() => $.c.nat64);
export { $Duration as Duration };

/** The initialization parameters of the Ledger */
type $InitArgs = { token_symbol: string; transfer_fee: bigint; metadata: Array<[string, $Value]>; minting_account: $Account; initial_balances: Array<[$Account, bigint]>; archive_options: { num_blocks_to_archive: bigint; trigger_threshold: bigint; max_message_size_bytes: bigint | null; cycles_for_archive_creation: bigint | null; node_max_memory_size_bytes: bigint | null; controller_id: $.Principal }; token_name: string };
/** The initialization parameters of the Ledger */
const $InitArgs: $.Schema<$InitArgs> = $.c.rec(() => $.c.record({ token_symbol: $.c.text, transfer_fee: $.c.nat64, metadata: $.c.vec($.c.tuple([$.c.text, $Value])), minting_account: $Account, initial_balances: $.c.vec($.c.tuple([$Account, $.c.nat64])), archive_options: $.c.record({ num_blocks_to_archive: $.c.nat64, trigger_threshold: $.c.nat64, max_message_size_bytes: $.c.opt($.c.nat64), cycles_for_archive_creation: $.c.opt($.c.nat64), node_max_memory_size_bytes: $.c.opt($.c.nat64), controller_id: $.c.principal }), token_name: $.c.text }));
export { $InitArgs as InitArgs };

type $LedgerArg = { tag: "Upgrade"; value: $UpgradeArgs | null } | { tag: "Init"; value: $InitArgs };
const $LedgerArg: $.Schema<$LedgerArg> = $.c.rec(() => $.c.variant({ Upgrade: $.c.opt($UpgradeArgs), Init: $InitArgs }));
export { $LedgerArg as LedgerArg };

type $Subaccount = Uint8Array;
const $Subaccount: $.Schema<$Subaccount> = $.c.rec(() => $.c.blob());
export { $Subaccount as Subaccount };

/** Number of nanoseconds since the UNIX epoch in UTC timezone. */
type $Timestamp = bigint;
/** Number of nanoseconds since the UNIX epoch in UTC timezone. */
const $Timestamp: $.Schema<$Timestamp> = $.c.rec(() => $.c.nat64);
export { $Timestamp as Timestamp };

type $Tokens = bigint;
const $Tokens: $.Schema<$Tokens> = $.c.rec(() => $.c.nat);
export { $Tokens as Tokens };

type $TransferArg = { to: $Account; fee: bigint | null; memo: $Subaccount | null; from_subaccount: $Subaccount | null; created_at_time: bigint | null; amount: bigint };
const $TransferArg: $.Schema<$TransferArg> = $.c.rec(() => $.c.record({ to: $Account, fee: $.c.opt($.c.nat), memo: $.c.opt($Subaccount), from_subaccount: $.c.opt($Subaccount), created_at_time: $.c.opt($.c.nat64), amount: $.c.nat }));
export { $TransferArg as TransferArg };

type $TransferError = { tag: "GenericError"; value: { message: string; error_code: bigint } } | { tag: "TemporarilyUnavailable" } | { tag: "BadBurn"; value: { min_burn_amount: bigint } } | { tag: "Duplicate"; value: { duplicate_of: bigint } } | { tag: "BadFee"; value: { expected_fee: bigint } } | { tag: "CreatedInFuture"; value: { ledger_time: bigint } } | { tag: "TooOld" } | { tag: "InsufficientFunds"; value: { balance: bigint } };
const $TransferError: $.Schema<$TransferError> = $.c.rec(() => $.c.variant({ GenericError: $.c.record({ message: $.c.text, error_code: $.c.nat }), TemporarilyUnavailable: $.c.null, BadBurn: $.c.record({ min_burn_amount: $.c.nat }), Duplicate: $.c.record({ duplicate_of: $.c.nat }), BadFee: $.c.record({ expected_fee: $.c.nat }), CreatedInFuture: $.c.record({ ledger_time: $.c.nat64 }), TooOld: $.c.null, InsufficientFunds: $.c.record({ balance: $.c.nat }) }));
export { $TransferError as TransferError };

type $TransferResult = { tag: "Ok"; value: bigint } | { tag: "Err"; value: $TransferError };
const $TransferResult: $.Schema<$TransferResult> = $.c.rec(() => $.c.variant({ Ok: $.c.nat, Err: $TransferError }));
export { $TransferResult as TransferResult };

type $UpgradeArgs = { token_symbol: string | null; transfer_fee: bigint | null; metadata: Array<[string, $Value]> | null; token_name: string | null };
const $UpgradeArgs: $.Schema<$UpgradeArgs> = $.c.rec(() => $.c.record({ token_symbol: $.c.opt($.c.text), transfer_fee: $.c.opt($.c.nat64), metadata: $.c.opt($.c.vec($.c.tuple([$.c.text, $Value]))), token_name: $.c.opt($.c.text) }));
export { $UpgradeArgs as UpgradeArgs };

/** The value returned from the [icrc1_metadata] endpoint. */
type $Value = { tag: "Int"; value: bigint } | { tag: "Nat"; value: bigint } | { tag: "Blob"; value: $Subaccount } | { tag: "Text"; value: string };
/** The value returned from the [icrc1_metadata] endpoint. */
const $Value: $.Schema<$Value> = $.c.rec(() => $.c.variant({ Int: $.c.int, Nat: $.c.nat, Blob: $Subaccount, Text: $.c.text }));
export { $Value as Value };

const $actor: $.Schema<$.Principal> = $.c.rec(() => $.c.service({ icrc1_balance_of: $.c.func([$Account], [$.c.nat], "query"), icrc1_decimals: $.c.func([], [$.c.nat8], "query"), icrc1_fee: $.c.func([], [$.c.nat], "query"), icrc1_supported_standards: $.c.func([], [$.c.vec($.c.record({ url: $.c.text, name: $.c.text }))], "query"), icrc1_metadata: $.c.func([], [$.c.vec($.c.tuple([$.c.text, $Value]))], "query"), icrc1_symbol: $.c.func([], [$.c.text], "query"), icrc1_minting_account: $.c.func([], [$.c.opt($Account)], "query"), icrc1_name: $.c.func([], [$.c.text], "query"), icrc1_total_supply: $.c.func([], [$.c.nat], "query"), icrc1_transfer: $.c.func([$TransferArg], [$TransferResult], "update") }));
type $Actor = {
  icrc1_balance_of: (arg0: $Account) => Promise<bigint>;
  icrc1_decimals: () => Promise<number>;
  icrc1_fee: () => Promise<bigint>;
  icrc1_supported_standards: () => Promise<Array<{ url: string; name: string }>>;
  icrc1_metadata: () => Promise<Array<[string, $Value]>>;
  icrc1_symbol: () => Promise<string>;
  icrc1_minting_account: () => Promise<$Account | null>;
  icrc1_name: () => Promise<string>;
  icrc1_total_supply: () => Promise<bigint>;
  icrc1_transfer: (arg0: $TransferArg) => Promise<$TransferResult>;
};
export { $actor as actor, type $Actor as Actor };
// Note: the actor is a service class; init args are install-time metadata not exposed here (issue #104).
