/**
 * Client Manager Generator
 *
 * Generates a central `clients.ts` file that creates a `ClientManager` instance.
 * This file is shared across all canisters in a project.
 *
 * Users typically customize this file once to configure:
 * - Custom host (local vs. mainnet)
 * - Identity provider
 * - Query client options
 */

export interface ClientGeneratorOptions {
  /**
   * Import path to an existing `queryClient` instance.
   * If omitted, a default `QueryClient` will be created.
   */
  queryClientPath?: string
}

/**
 * Generate the content for a central client manager file (`clients.ts`).
 */
export function generateClientFile(
  options: ClientGeneratorOptions = {}
): string {
  const { queryClientPath } = options

  const queryClientImport = queryClientPath
    ? `import { queryClient } from "${queryClientPath}"`
    : `import { QueryClient } from "@tanstack/react-query"

export const queryClient = new QueryClient()`

  return `import { ClientManager } from "@ic-reactor/react"
${queryClientImport}

/**
 * IC Reactor Client Manager
 *
 * Auto-generated by @ic-reactor/codegen — customize as needed.
 * See: https://github.com/B3Pay/ic-reactor#client-manager
 */
export const clientManager = new ClientManager({
  queryClient,
  withCanisterEnv: true,
})
`
}
