/**
 * Reactor File Generator
 *
 * Generates the managed `index.generated.ts` implementation for a canister
 * plus the full set of typed hooks via `createActorHooks`.
 *
 * Generated output example (for canister "backend"):
 *
 *   import { DisplayReactor, createActorHooks } from "@ic-reactor/react"
 *   import { clientManager } from "../../clients"
 *   import { idlFactory, type _SERVICE } from "./declarations/backend"
 *
 *   export type BackendService = _SERVICE
 *
 *   export const backendReactor = new DisplayReactor<BackendService>({ ... })
 *
 *   export const {
 *     useActorQuery: useBackendQuery,
 *     ...
 *   } = createActorHooks(backendReactor)
 */

import path from "node:path"
import { toPascalCase, getReactorName, getServiceTypeName } from "../naming.js"
import type { ReactorClassName } from "../types.js"

export interface ReactorGeneratorOptions {
  /** Canister name (e.g. "backend") */
  canisterName: string
  /**
   * Path to the .did file. Used to derive the declarations import path.
   * Can be relative or absolute — only the basename is used.
   */
  didFile: string
  /**
   * Import path for the client manager, relative from the generated reactor file.
   * Default: "../../clients"
   */
  clientManagerPath?: string
  /** Optional fixed canister ID for the generated reactor */
  canisterId?: string
  /**
   * Which reactor class should back the generated hooks.
   * Default: "DisplayReactor" (backward compatible)
   */
  reactorClass?: ReactorClassName
}

function getReactorClassImportSource(
  reactorClass: ReactorClassName
): "@ic-reactor/react" | "@ic-reactor/candid" {
  switch (reactorClass) {
    case "Reactor":
    case "DisplayReactor":
      return "@ic-reactor/react"
    case "CandidReactor":
    case "CandidDisplayReactor":
    case "MetadataDisplayReactor":
      return "@ic-reactor/candid"
  }
}

/**
 * Generate the content of a canister's managed implementation file.
 */
export function generateReactorFile(options: ReactorGeneratorOptions): string {
  const {
    canisterName,
    didFile,
    clientManagerPath = "../../clients",
    canisterId,
    reactorClass = "DisplayReactor",
  } = options

  const pascalName = toPascalCase(canisterName)
  const reactorName = getReactorName(canisterName)
  const serviceName = getServiceTypeName(canisterName)

  // Derive the declarations import path from the .did filename
  const baseName = path.basename(didFile, ".did")
  const declarationsPath = `./declarations/${baseName}`
  const reactorImportSource = getReactorClassImportSource(reactorClass)
  const canisterIdLine = canisterId
    ? `  canisterId: ${JSON.stringify(canisterId)},\n`
    : ""

  return `import { createActorHooks } from "@ic-reactor/react"
import { ${reactorClass} } from "${reactorImportSource}"
import { clientManager } from "${clientManagerPath}"
import { idlFactory, type _SERVICE } from "${declarationsPath}"

export type ${serviceName} = _SERVICE

/**
 * ${pascalName} Reactor
 *
 * Auto-generated by @ic-reactor/codegen — do not edit.
 * This file is overwritten whenever generation runs.
 */
export const ${reactorName} = new ${reactorClass}<${serviceName}>({
  clientManager,
  idlFactory,
${canisterIdLine}  name: "${canisterName}",
})

export const {
  useActorQuery: use${pascalName}Query,
  useActorSuspenseQuery: use${pascalName}SuspenseQuery,
  useActorInfiniteQuery: use${pascalName}InfiniteQuery,
  useActorSuspenseInfiniteQuery: use${pascalName}SuspenseInfiniteQuery,
  useActorMutation: use${pascalName}Mutation,
  useActorMethod: use${pascalName}Method,
} = createActorHooks(${reactorName})
`
}

/**
 * Generate the user-facing `index.ts` wrapper content.
 */
export function generateReactorEntryFile(): string {
  return `/**
 * Canister entrypoint.
 *
 * Created once by @ic-reactor/codegen and safe to customize.
 * Keep the re-export below if you want generated hooks and types to stay in sync.
 */
export * from "./index.generated"
`
}
