/**
 * Reactor File Generator
 *
 * Generates the managed `index.generated.ts` implementation for a canister.
 * React targets also emit the full set of typed hooks via `createActorHooks`.
 *
 * Generated output example (for canister "backend"):
 *
 *   import { DisplayReactor, createActorHooks } from "@ic-reactor/react"
 *   import { clientManager } from "../../clients"
 *   import { idlFactory, type _SERVICE } from "./declarations/backend"
 *
 *   export type BackendService = _SERVICE
 *
 *   export const backendReactor = new DisplayReactor<BackendService>({ ... })
 *
 *   export const {
 *     useActorQuery: useBackendQuery,
 *     ...
 *   } = createActorHooks(backendReactor)
 */

import path from "node:path"
import { toPascalCase, getReactorName, getServiceTypeName } from "../naming.js"
import type { CodegenTarget, ReactorClassName } from "../types.js"

export interface ReactorGeneratorOptions {
  /** Canister name (e.g. "backend") */
  canisterName: string
  /**
   * Path to the .did file. Used to derive the declarations import path.
   * Can be relative or absolute — only the basename is used.
   */
  didFile: string
  /**
   * Import path for the client manager, relative from the generated reactor file.
   * Default: "../../clients"
   */
  clientManagerPath?: string
  /** Optional fixed canister ID for the generated reactor */
  canisterId?: string
  /** Generated runtime target */
  runtimeTarget?: CodegenTarget
  /**
   * Which reactor class should back the generated hooks.
   * Default: "DisplayReactor" (backward compatible)
   */
  reactorClass?: ReactorClassName
}

function getReactorClassImportSource(
  reactorClass: ReactorClassName,
  runtimeTarget: CodegenTarget
): "@ic-reactor/react" | "@ic-reactor/core" | "@ic-reactor/candid" {
  switch (reactorClass) {
    case "Reactor":
    case "DisplayReactor":
      return runtimeTarget === "core" ? "@ic-reactor/core" : "@ic-reactor/react"
    case "CandidReactor":
    case "CandidDisplayReactor":
    case "MetadataDisplayReactor":
      return "@ic-reactor/candid"
  }
}

/**
 * Check if a reactor class uses display type transformations.
 */
function isDisplayMode(reactorClass: ReactorClassName): boolean {
  return (
    reactorClass === "DisplayReactor" ||
    reactorClass === "CandidDisplayReactor" ||
    reactorClass === "MetadataDisplayReactor"
  )
}

/**
 * Generate the content of a canister's managed implementation file.
 */
export function generateReactorFile(options: ReactorGeneratorOptions): string {
  const {
    canisterName,
    didFile,
    clientManagerPath = "../../clients",
    canisterId,
    runtimeTarget = "react",
    reactorClass = "DisplayReactor",
  } = options

  const pascalName = toPascalCase(canisterName)
  const reactorName = getReactorName(canisterName)
  const serviceName = getServiceTypeName(canisterName)

  // Derive the declarations import path from the .did filename
  const baseName = path.basename(didFile, ".did")
  const useDisplay = isDisplayMode(reactorClass)
  const declarationsPath = useDisplay
    ? `./declarations/${baseName}.display`
    : `./declarations/${baseName}`
  // IDL factory always comes from the standard declarations (has the runtime JS)
  const idlFactoryPath = `./declarations/${baseName}`
  const reactorImportSource = getReactorClassImportSource(
    reactorClass,
    runtimeTarget
  )
  const canisterIdLine = canisterId
    ? `  canisterId: ${JSON.stringify(canisterId)},\n`
    : ""
  const hookExports =
    runtimeTarget === "react"
      ? `

export const {
  useActorQuery: use${pascalName}Query,
  useActorSuspenseQuery: use${pascalName}SuspenseQuery,
  useActorInfiniteQuery: use${pascalName}InfiniteQuery,
  useActorSuspenseInfiniteQuery: use${pascalName}SuspenseInfiniteQuery,
  useActorMutation: use${pascalName}Mutation,
  useActorMethod: use${pascalName}Method,
} = createActorHooks(${reactorName})
`
      : ""

  // When importing from display declarations, also import the IDL factory
  // from the standard declarations (display file is types-only)
  const serviceImport = useDisplay
    ? `import { type _SERVICE } from "${declarationsPath}"
import { idlFactory } from "${idlFactoryPath}"`
    : `import { idlFactory, type _SERVICE } from "${declarationsPath}"`

  return `${runtimeTarget === "react" ? 'import { createActorHooks } from "@ic-reactor/react"\n' : ""}import { ${reactorClass} } from "${reactorImportSource}"
import { clientManager } from "${clientManagerPath}"
${serviceImport}

export type ${serviceName} = _SERVICE

/**
 * ${pascalName} Reactor
 *
 * Auto-generated by @ic-reactor/codegen — do not edit.
 * This file is overwritten whenever generation runs.
 */
export const ${reactorName} = new ${reactorClass}<${serviceName}>({
  clientManager,
  idlFactory,
${canisterIdLine}  name: "${canisterName}",
})${hookExports || "\n"}`
}

/**
 * Generate the user-facing `index.ts` wrapper content.
 */
export function generateReactorEntryFile(): string {
  return `/**
 * Canister entrypoint.
 *
 * Created once by @ic-reactor/codegen and safe to customize.
 * Keep the re-export below if you want generated exports and types to stay in sync.
 */
export * from "./index.generated"
`
}
