/**
 * Reactor File Generator
 *
 * Generates the main `index.ts` for a canister — a DisplayReactor instance
 * plus the full set of typed hooks via `createActorHooks`.
 *
 * Generated output example (for canister "backend"):
 *
 *   import { DisplayReactor, createActorHooks } from "@ic-reactor/react"
 *   import { clientManager } from "../../clients"
 *   import { idlFactory, type _SERVICE } from "./declarations/backend"
 *
 *   export type BackendService = _SERVICE
 *
 *   export const backendReactor = new DisplayReactor<BackendService>({ ... })
 *
 *   export const {
 *     useActorQuery: useBackendQuery,
 *     ...
 *   } = createActorHooks(backendReactor)
 */

import path from "node:path"
import { toPascalCase, getReactorName, getServiceTypeName } from "../naming.js"

export interface ReactorGeneratorOptions {
  /** Canister name (e.g. "backend") */
  canisterName: string
  /**
   * Path to the .did file. Used to derive the declarations import path.
   * Can be relative or absolute — only the basename is used.
   */
  didFile: string
  /**
   * Import path for the client manager, relative from the generated reactor file.
   * Default: "../../clients"
   */
  clientManagerPath?: string
}

/**
 * Generate the content of a canister's `index.ts` reactor file.
 */
export function generateReactorFile(options: ReactorGeneratorOptions): string {
  const { canisterName, didFile, clientManagerPath = "../../clients" } = options

  const pascalName = toPascalCase(canisterName)
  const reactorName = getReactorName(canisterName)
  const serviceName = getServiceTypeName(canisterName)

  // Derive the declarations import path from the .did filename
  const baseName = path.basename(didFile, ".did")
  const declarationsPath = `./declarations/${baseName}`

  return `import { DisplayReactor, createActorHooks } from "@ic-reactor/react"
import { clientManager } from "${clientManagerPath}"
import { idlFactory, type _SERVICE } from "${declarationsPath}"

export type ${serviceName} = _SERVICE

/**
 * ${pascalName} Reactor
 *
 * Auto-generated by @ic-reactor/codegen — do not edit.
 * Re-run \`ic-reactor generate\` (or the Vite plugin) to regenerate.
 */
export const ${reactorName} = new DisplayReactor<${serviceName}>({
  clientManager,
  idlFactory,
  name: "${canisterName}",
})

export const {
  useActorQuery: use${pascalName}Query,
  useActorSuspenseQuery: use${pascalName}SuspenseQuery,
  useActorInfiniteQuery: use${pascalName}InfiniteQuery,
  useActorSuspenseInfiniteQuery: use${pascalName}SuspenseInfiniteQuery,
  useActorMutation: use${pascalName}Mutation,
  useActorMethod: use${pascalName}Method,
} = createActorHooks(${reactorName})
`
}
