/**
 * Query Hook: icrc1_balance_of
 *
 * Auto-generated by @ic-reactor/cli
 * This hook wraps the icrc1_balance_of query method.
 *
 * @example
 * // With the factory (for dynamic args)
 * const query = icrc1BalanceOfQuery([arg1, arg2])
 * const { data } = query.useQuery()
 *
 * // Or use the hook directly
 * const { data } = useIcrc1BalanceOfQuery([arg1, arg2])
 */

import { createQueryFactory } from "@ic-reactor/react"
import { ledgerReactor, type LedgerService } from "../reactor"

// ═══════════════════════════════════════════════════════════════════════════
// QUERY FACTORY
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Query factory for icrc1_balance_of
 *
 * Creates a query instance with the provided arguments.
 * Each unique set of args gets its own cached query.
 */
export const icrc1BalanceOfQuery = createQueryFactory(ledgerReactor, {
  functionName: "icrc1_balance_of",
  // Customize your query options:
  // staleTime: 5 * 60 * 1000,
  // select: (data) => data,
})

// ═══════════════════════════════════════════════════════════════════════════
// CONVENIENCE HOOK
// ═══════════════════════════════════════════════════════════════════════════

/**
 * React hook for icrc1_balance_of
 *
 * @param args - Arguments to pass to the canister method
 * @param options - Additional React Query options
 */
export function useIcrc1BalanceOfQuery(
  args: Parameters<LedgerService["icrc1_balance_of"]>,
  options?: Parameters<ReturnType<typeof icrc1BalanceOfQuery>["useQuery"]>[0]
) {
  return icrc1BalanceOfQuery(args).useQuery(options)
}

// ═══════════════════════════════════════════════════════════════════════════
// UTILITY FUNCTIONS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Fetch icrc1_balance_of directly (for loaders, server components, etc.)
 */
export function fetchIcrc1BalanceOf(
  args: Parameters<LedgerService["icrc1_balance_of"]>
) {
  return icrc1BalanceOfQuery(args).fetch()
}

/**
 * Invalidate icrc1_balance_of query cache
 */
export function invalidateIcrc1BalanceOf(
  args: Parameters<LedgerService["icrc1_balance_of"]>
) {
  return icrc1BalanceOfQuery(args).invalidate()
}

/**
 * Get icrc1_balance_of query key (for cache manipulation)
 */
export function getIcrc1BalanceOfQueryKey(
  args: Parameters<LedgerService["icrc1_balance_of"]>
) {
  return icrc1BalanceOfQuery(args).getQueryKey()
}
