/**
 * Query Hook: icrc1_decimals
 *
 * Auto-generated by @ic-reactor/cli
 * This hook wraps the icrc1_decimals query method.
 *
 * @example
 * // Use the hook
 * const { data, isLoading } = useIcrc1DecimalsQuery()
 *
 * // Or access the query object directly
 * const data = await icrc1DecimalsQuery.fetch()
 * icrc1DecimalsQuery.invalidate()
 */

import { createQuery } from "@ic-reactor/react"
import { ledgerReactor } from "../reactor"

// ═══════════════════════════════════════════════════════════════════════════
// QUERY INSTANCE
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Query for icrc1_decimals
 *
 * Provides:
 * - .useQuery() - React hook
 * - .fetch() - Direct fetch (for loaders)
 * - .invalidate() - Invalidate cache
 * - .getQueryKey() - Get query key
 * - .getCacheData() - Read from cache
 */
export const icrc1DecimalsQuery = createQuery(ledgerReactor, {
  functionName: "icrc1_decimals",
  // Customize your query options:
  // staleTime: 5 * 60 * 1000,
  // select: (data) => data,
})

// ═══════════════════════════════════════════════════════════════════════════
// CONVENIENCE EXPORTS
// ═══════════════════════════════════════════════════════════════════════════

/**
 * React hook for icrc1_decimals
 */
export const useIcrc1DecimalsQuery = icrc1DecimalsQuery.useQuery

/**
 * Fetch icrc1_decimals directly (for loaders, server components, etc.)
 */
export const fetchIcrc1Decimals = icrc1DecimalsQuery.fetch

/**
 * Invalidate icrc1_decimals query cache
 */
export const invalidateIcrc1Decimals = icrc1DecimalsQuery.invalidate

/**
 * Get icrc1_decimals query key (for cache manipulation)
 */
export const getIcrc1DecimalsQueryKey = icrc1DecimalsQuery.getQueryKey

/**
 * Get cached data for icrc1_decimals
 */
export const getIcrc1DecimalsCacheData = icrc1DecimalsQuery.getCacheData
