export const TAMESTAMP_KEYS = [
  "date",
  "deadline",
  "timestamp",
  "statusAt",
  "createdAt",
  "updatedAt",
  "deletedAt",
  "validUntil",
  "status_at",
  "created_at",
  "updated_at",
  "deleted_at",
  "valid_until",
]
