import type { CSSProperties } from "react"

export const styles: Record<string, CSSProperties> = {
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "2rem",
  },
  header: {
    textAlign: "center",
    marginBottom: "3rem",
  },
  title: {
    fontSize: "2.5rem",
    fontWeight: 700,
    background: "linear-gradient(135deg, #60a5fa 0%, #a78bfa 100%)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    marginBottom: "0.5rem",
  },
  subtitle: {
    lineHeight: "1.7rem",
    fontSize: "1.1rem",
    color: "#94a3b8",
  },
  code: {
    background: "rgba(96, 165, 250, 0.15)",
    padding: "0.2rem 0.5rem",
    borderRadius: "4px",
    fontFamily: "monospace",
    color: "#60a5fa",
  },
  main: {
    display: "flex",
    flexDirection: "column",
    gap: "3rem",
  },
  section: {
    background: "rgba(255, 255, 255, 0.03)",
    borderRadius: "16px",
    padding: "2rem",
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  sectionTitle: {
    fontSize: "1.5rem",
    fontWeight: 600,
    marginBottom: "0.5rem",
  },
  description: {
    color: "#94a3b8",
    marginBottom: "1.5rem",
  },
  cardGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "1rem",
    marginBottom: "1.5rem",
  },
  card: {
    background: "rgba(255, 255, 255, 0.05)",
    borderRadius: "12px",
    padding: "1.5rem",
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  cardTitle: {
    fontSize: "0.875rem",
    color: "#94a3b8",
    marginBottom: "0.5rem",
    fontWeight: 500,
  },
  cardValue: {
    fontSize: "1.25rem",
    fontWeight: 600,
    color: "#e8e8e8",
  },
  lookupContainer: {
    marginBottom: "1.5rem",
  },
  inputGroup: {
    display: "flex",
    gap: "0.5rem",
    marginBottom: "1rem",
  },
  input: {
    flex: 1,
    padding: "0.75rem 1rem",
    borderRadius: "8px",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    background: "rgba(255, 255, 255, 0.05)",
    color: "#e8e8e8",
    fontSize: "1rem",
    outline: "none",
  },
  button: {
    padding: "0.75rem 1.5rem",
    borderRadius: "8px",
    border: "none",
    background: "linear-gradient(135deg, #60a5fa 0%, #a78bfa 100%)",
    color: "white",
    fontSize: "1rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  error: {
    color: "#f87171",
    marginBottom: "1rem",
  },
  balanceGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))",
    gap: "1rem",
  },
  balanceCard: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "1.5rem",
    borderRadius: "12px",
    background: "rgba(255, 255, 255, 0.05)",
    borderWidth: "2px",
    borderStyle: "solid",
  },
  tokenLabel: {
    fontSize: "0.875rem",
    fontWeight: 600,
    marginBottom: "0.5rem",
  },
  balanceValue: {
    fontSize: "1.25rem",
    fontWeight: 700,
  },
  codeBlock: {
    background:
      "linear-gradient(135deg, rgba(15, 23, 42, 0.95) 0%, rgba(30, 41, 59, 0.9) 100%)",
    borderRadius: "12px",
    padding: "1.25rem",
    border: "1px solid rgba(99, 102, 241, 0.2)",
    boxShadow:
      "0 4px 6px -1px rgba(0, 0, 0, 0.3), 0 2px 4px -2px rgba(0, 0, 0, 0.3)",
  },
  codeTitle: {
    fontSize: "0.8rem",
    color: "#94a3b8",
    marginBottom: "1rem",
    fontWeight: 600,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  pre: {
    margin: 0,
    overflow: "auto",
    fontSize: "0.85rem",
    lineHeight: 1.7,
    color: "#e2e8f0",
    padding: "0.5rem",
    borderRadius: "6px",
    background: "rgba(0, 0, 0, 0.2)",
  },
  topRight: {
    position: "absolute",
    top: "1rem",
    right: "1rem",
  },
  authContainer: {
    display: "flex",
    alignItems: "center",
  },
  authInfo: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    background: "rgba(255, 255, 255, 0.1)",
    padding: "0.5rem 1rem",
    borderRadius: "20px",
  },
  principal: {
    fontSize: "0.875rem",
    color: "#e2e8f0",
  },
  authButton: {
    padding: "0.5rem 1rem",
    borderRadius: "20px",
    border: "none",
    background: "#3b82f6",
    color: "white",
    fontWeight: 600,
    cursor: "pointer",
    fontSize: "0.875rem",
  },
  // Transfer section styles
  transferContainer: {
    marginBottom: "1.5rem",
  },
  loginPrompt: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "1rem",
    padding: "2rem",
    background: "rgba(255, 255, 255, 0.05)",
    borderRadius: "12px",
    border: "1px dashed rgba(255, 255, 255, 0.2)",
  },
  loginText: {
    color: "#94a3b8",
    fontSize: "1rem",
    margin: 0,
  },
  loginButton: {
    padding: "0.75rem 2rem",
    borderRadius: "8px",
    border: "none",
    background: "linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%)",
    color: "white",
    fontSize: "1rem",
    fontWeight: 600,
    cursor: "pointer",
  },
  userInfo: {
    display: "flex",
    flexDirection: "column",
    gap: "0.25rem",
    marginBottom: "1rem",
    padding: "1rem",
    background: "rgba(255, 255, 255, 0.05)",
    borderRadius: "8px",
  },
  userLabel: {
    fontSize: "0.75rem",
    color: "#94a3b8",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
  },
  userPrincipal: {
    fontSize: "0.875rem",
    color: "#60a5fa",
    wordBreak: "break-all",
  },
  userBalance: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1rem",
    background:
      "linear-gradient(135deg, rgba(96, 165, 250, 0.1) 0%, rgba(167, 139, 250, 0.1) 100%)",
    borderRadius: "8px",
    marginBottom: "1rem",
    border: "1px solid rgba(96, 165, 250, 0.3)",
  },
  balanceLabel: {
    fontSize: "0.875rem",
    color: "#94a3b8",
  },
  balanceLoading: {
    padding: "1rem",
    color: "#94a3b8",
    textAlign: "center",
  },
  transferForm: {
    padding: "1.5rem",
    background: "rgba(255, 255, 255, 0.03)",
    borderRadius: "12px",
    border: "1px solid rgba(255, 255, 255, 0.1)",
  },
  formTitle: {
    fontSize: "1.125rem",
    fontWeight: 600,
    marginBottom: "1rem",
    color: "#e8e8e8",
  },
  formGroup: {
    marginBottom: "1rem",
  },
  formLabel: {
    display: "block",
    fontSize: "0.875rem",
    color: "#94a3b8",
    marginBottom: "0.5rem",
  },
  formInput: {
    width: "100%",
    padding: "0.75rem 1rem",
    borderRadius: "8px",
    border: "1px solid rgba(255, 255, 255, 0.2)",
    background: "rgba(255, 255, 255, 0.05)",
    color: "#e8e8e8",
    fontSize: "1rem",
    outline: "none",
    boxSizing: "border-box",
  },
  errorMessage: {
    color: "#f87171",
    fontSize: "0.875rem",
    marginBottom: "1rem",
    padding: "0.75rem",
    background: "rgba(248, 113, 113, 0.1)",
    borderRadius: "8px",
    border: "1px solid rgba(248, 113, 113, 0.3)",
  },
  successMessage: {
    color: "#4ade80",
    fontSize: "0.875rem",
    marginBottom: "1rem",
    padding: "0.75rem",
    background: "rgba(74, 222, 128, 0.1)",
    borderRadius: "8px",
    border: "1px solid rgba(74, 222, 128, 0.3)",
  },
  transferButton: {
    width: "100%",
    padding: "0.875rem 1.5rem",
    borderRadius: "8px",
    border: "none",
    background: "linear-gradient(135deg, #10b981 0%, #3b82f6 100%)",
    color: "white",
    fontSize: "1rem",
    fontWeight: 600,
    cursor: "pointer",
    marginTop: "0.5rem",
  },
}
