name: Build and Release

on:
  push:
    tags:
      - "@ic-reactor/core@*"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Install wasm-pack
        run: yarn global add wasm-pack

      - name: Build
        run: yarn build

      - name: Get Core Package Version
        id: core-version
        run: echo "CORE_VERSION=$(jq -r '.version' ./packages/core/package.json)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          name: "Core Bundle v${{ env.CORE_VERSION }}"
          tag_name: "v${{ env.CORE_VERSION }}"
          body: |
            For production use:
            ```html
            <script src="https://github.com/B3Pay/ic-reactor/releases/download/v${{ env.CORE_VERSION }}/ic-reactor-core.min.js"></script>
            ```
            For development use:
            ```html
            <script src="https://github.com/B3Pay/ic-reactor/releases/download/v${{ env.CORE_VERSION }}/ic-reactor-core.js"></script>
            ```
          files: |
            ./packages/core/umd/production/ic-reactor-core.min.js
            ./packages/core/umd/development/ic-reactor-core.js
            ./packages/core/umd/development/ic-reactor-core.js.map
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Manually Checkout to a Branch
        run: |
          git checkout main || git switch -c main
          git pull origin main

      - name: Update README.md
        run: |
          sed -i "s/releases\/download\/.*\/ic-reactor-core.min.js/releases\/download\/v${{ env.CORE_VERSION }}\/ic-reactor-core.min.js/" ./packages/core/README.md

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "./packages/core/README.md"
          default_author: github_actions
          message: "Update README.md to point to the latest release(v${{ env.CORE_VERSION }})"
