name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Activate Corepack
        run: npx corepack enable

      - name: Set Yarn version to berry
        run: yarn set version berry

      - name: Install dependencies
        run: yarn install

      - name: Install wasm-pack
        run: yarn global add wasm-pack

      - name: Build
        run: yarn build

      - name: Generate Documentation
        run: yarn docs:build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs
