name: Build and Release

on:
  push:
    tags:
      - "@ic-reactor/core@*"
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          cache: "yarn"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Get Core Package Version
        id: core-version
        run: echo "CORE_VERSION=$(jq -r '.version' ./packages/core/package.json)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          name: "Core Bundle v${{ env.CORE_VERSION }}"
          tag_name: "v${{ env.CORE_VERSION }}"
          body: "https://github.com/B3Pay/ic-reactor/releases/download/v${{ env.CORE_VERSION }}/ic-reactor-core.min.js"
          files: |
            ./packages/core/umd/production/ic-reactor-core.min.js
            ./packages/core/umd/development/ic-reactor-core.js
            ./packages/core/umd/development/ic-reactor-core.js.map
          draft: false
          prerelease: false
          generate_release_notes: true
