name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - uses: crrashh1542/action-setup-yarn-berry@v1
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Install wasm-pack
        run: yarn global add wasm-pack

      - name: Build
        run: yarn build

      - name: Generate Documentation
        run: yarn docs:build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs
